const state={sport:1,date:todayTR(),search:'',matches:[],source:'',fetchedAt:null,loading:false,analyses:new Map()};
function dateTR(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function todayTR(){return dateTR()}
function tomorrowTR(){const d=new Date();d.setDate(d.getDate()+1);return dateTR(d)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function timeTR(ts,fallback=''){if(!ts)return fallback;return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))}
function fmtDate(s){try{return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',weekday:'long',day:'numeric',month:'long'}).format(new Date(s+'T12:00:00+03:00'))}catch{return s}}
function flatOdds(m){const o=[];for(const mk of m.markets||[])for(const x of mk.outcomes||[])if(x.odds)o.push({name:mk.name,label:x.label,odds:x.odds});return o}
function previewOdds(m){return flatOdds(m).filter(x=>/maç sonucu|1x2|kazanan/i.test(x.name)).slice(0,3)}
function quickRadar(m){const all=flatOdds(m);const med=all.some(x=>x.odds>=5&&x.odds<8);const agg=all.some(x=>x.odds>=10&&x.odds<21);const special=all.some(x=>/oyuncu|şut|isabet|korner|kart|ace|servis|set/i.test(x.name));return Math.min(99,Math.round(34+(med?22:0)+(agg?22:0)+(special?12:0)+Math.min(9,(m.markets||[]).length/5)))}
async function load(){
 state.loading=true;renderList();
 try{const q=new URLSearchParams({sport:String(state.sport),date:state.date});if(state.search)q.set('search',state.search);const r=await fetch('/api/bulletin?'+q,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Bülten alınamadı');state.matches=(j.matches||[]).sort((a,b)=>(a.startTimestamp||9e15)-(b.startTimestamp||9e15));state.source=j.source;state.fetchedAt=j.fetchedAt;document.querySelector('#err').innerHTML='';}
 catch(e){state.matches=[];document.querySelector('#err').innerHTML=`<div class="error"><b>${escapeHtml(e.message)}</b><br>Sahte maç/oran gösterilmiyor. Veri kaynağı erişilemiyor.</div>`}
 finally{state.loading=false;renderAll()}
}
function renderAll(){renderToolbar();renderStatus();renderRadar();renderList()}
function renderToolbar(){document.querySelectorAll('[data-sport]').forEach(b=>b.classList.toggle('active',Number(b.dataset.sport)===state.sport));document.querySelectorAll('[data-date]').forEach(b=>b.classList.toggle('active',b.dataset.date===state.date));document.querySelector('#customDate').value=state.date;}
function renderStatus(){document.querySelector('#status').innerHTML=state.fetchedAt?`<b>● CANLI BÜLTEN</b><br>${escapeHtml(state.source)} · ${timeTR(Date.parse(state.fetchedAt))} güncellendi`:'Gerçek veri bekleniyor';}
function renderRadar(){const top=state.matches.map(m=>({m,s:quickRadar(m)})).sort((a,b)=>b.s-a.s).slice(0,3);document.querySelector('#radarGrid').innerHTML=top.length?top.map(({m,s})=>`<div class="radarcard" data-id="${escapeHtml(m.id)}"><small>${escapeHtml(m.league)} · ${timeTR(m.startTimestamp,m.time)}</small><div class="score">${s}</div><b>${escapeHtml(m.home)} — ${escapeHtml(m.away)}</b><small>NEÇ sürpriz radar skoru</small></div>`).join(''):'<div class="empty">Bu tarih için radar adayı yok.</div>';document.querySelectorAll('.radarcard').forEach(x=>x.onclick=()=>openMatch(x.dataset.id));}
function renderList(){const box=document.querySelector('#matches');document.querySelector('#count').textContent=`${state.matches.length} karşılaşma`;document.querySelector('#dayTitle').textContent=fmtDate(state.date);if(state.loading){box.innerHTML='<div class="loading">Bülten yükleniyor…</div>';return}if(!state.matches.length){box.innerHTML='<div class="empty">Bu filtrede karşılaşma bulunamadı.</div>';return}box.innerHTML=state.matches.map(m=>{const po=previewOdds(m);return `<div class="match" data-id="${escapeHtml(m.id)}"><div><div class="time">${timeTR(m.startTimestamp,m.time)}</div><div class="sports">${escapeHtml(m.sport)}</div></div><div><div class="league">${escapeHtml(m.league)} · ${m.marketCount} market</div><div class="teams">${escapeHtml(m.home)} — ${escapeHtml(m.away)}</div></div><div class="oddbox">${po.map(o=>`<span class="odd">${escapeHtml(o.label)} <b>${Number(o.odds).toFixed(2)}</b></span>`).join('')}</div></div>`}).join('');document.querySelectorAll('.match').forEach(x=>x.onclick=()=>openMatch(x.dataset.id));}
async function openMatch(id){const m=state.matches.find(x=>x.id===id);if(!m)return;const back=document.querySelector('#modalBack');const body=document.querySelector('#modalBody');back.classList.add('show');body.innerHTML=`<div class="modaltop"><div><div class="meta">${escapeHtml(m.league)} · ${timeTR(m.startTimestamp,m.time)}</div><h2>${escapeHtml(m.home)} — ${escapeHtml(m.away)}</h2></div><button class="close" id="closeModal">×</button></div><div class="loading">NEÇ 5’li analiz hazırlanıyor…</div>`;document.querySelector('#closeModal').onclick=closeModal;
 try{let a=state.analyses.get(id);if(!a){const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(m)});a=await r.json();if(!r.ok)throw new Error(a.error||'Analiz alınamadı');state.analyses.set(id,a)}renderAnalysis(m,a)}catch(e){body.innerHTML+=`<div class="error">${escapeHtml(e.message)}</div>`}}
function renderAnalysis(m,a){const body=document.querySelector('#modalBody');body.innerHTML=`<div class="modaltop"><div><div class="meta">${escapeHtml(m.league)} · ${timeTR(m.startTimestamp,m.time)}</div><h2>${escapeHtml(m.home)} — ${escapeHtml(m.away)}</h2></div><button class="close" id="closeModal">×</button></div><div class="scoreline"><span class="pill lime">NEÇ RADAR ${a.radar}/99</span><span class="pill">${m.marketCount} gerçek market</span>${a.form?'<span class="pill">Son-10 best effort</span>':'<span class="pill">Form verisi yok</span>'}</div><div class="picks">${a.picks.map(p=>`<div class="pick ${p.available?'':'na'}"><div class="tag">${escapeHtml(p.tag)}</div><h3>${escapeHtml(p.label)}</h3>${p.available?`<div class="sel"><span>${escapeHtml(p.market)} · ${escapeHtml(p.selection)}</span><span class="oddnum">${Number(p.odds).toFixed(2)}</span></div><div class="reason">${escapeHtml(p.reason)}</div>`:`<div class="reason">${escapeHtml(p.reason)}</div>`}</div>`).join('')}</div><div class="insights">${a.insights.map(i=>`<div class="insight"><b>${escapeHtml(i.title)}</b><p>${escapeHtml(i.text)}</p></div>`).join('')}</div><div class="warn">${escapeHtml(a.disclaimer)}</div>`;document.querySelector('#closeModal').onclick=closeModal;}
function closeModal(){document.querySelector('#modalBack').classList.remove('show')}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-sport]').forEach(b=>b.onclick=()=>{state.sport=Number(b.dataset.sport);load()});document.querySelector('#todayBtn').dataset.date=todayTR();document.querySelector('#tomorrowBtn').dataset.date=tomorrowTR();document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.date=b.dataset.date;load()});document.querySelector('#customDate').onchange=e=>{state.date=e.target.value;load()};let t;document.querySelector('#search').oninput=e=>{clearTimeout(t);t=setTimeout(()=>{state.search=e.target.value;load()},350)};document.querySelector('#modalBack').onclick=e=>{if(e.target.id==='modalBack')closeModal()};load();setInterval(()=>{const d=todayTR();if(state.date===state._lastToday&&d!==state._lastToday)state.date=d;state._lastToday=d;load()},120000);state._lastToday=todayTR()});
