const state={sport:1,date:todayTR(),search:'',matches:[],source:'',fetchedAt:null,loading:false,analyses:new Map(),bulletinSignature:''};
function dateTR(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function todayTR(){return dateTR()}function tomorrowTR(){const d=new Date();d.setDate(d.getDate()+1);return dateTR(d)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function timeTR(ts,fallback=''){if(!ts)return fallback;return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))}
function fmtDate(s){try{return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',weekday:'long',day:'numeric',month:'long'}).format(new Date(s+'T12:00:00+03:00'))}catch{return s}}
function technicalText(v){return /^(market|bahis|seçenek|secenek|option|outcome|selection)\s*[#:_-]?\s*\d+\b/i.test(String(v||'').trim())}
function flatOdds(m,verifiedOnly=true){const out=[];for(const mk of m.markets||[]){if(mk.known===false||technicalText(mk.name))continue;for(const o of mk.outcomes||[]){if(!(Number(o.odds)>1))continue;if(verifiedOnly&&o.labelVerified!==true&&!o.sourceLabel)continue;out.push({name:mk.name,label:o.label,odds:Number(o.odds),kind:mk.kind,verified:o.labelVerified===true||!!o.sourceLabel})}}return out}
function previewOdds(m){const all=flatOdds(m,true),main=all.filter(x=>/maç sonucu|1x2|maç kazananı/i.test(x.name)).slice(0,3);return main.length?main:all.slice(0,3)}
function quickRadar(m){const all=flatOdds(m,true),medium=all.some(x=>x.odds>=2.5&&x.odds<5),high=all.some(x=>x.odds>=5&&x.odds<12),special=all.some(x=>/ilk yarı|devre|gol|korner|kart|şut|set|oyun/i.test(x.name));return Math.min(78,Math.round(22+(medium?13:0)+(high?14:0)+(special?11:0)+Math.min(18,(m.markets||[]).length/4)))}
function analysisKey(m){return `${m.id}|${(m.markets||[]).flatMap(mk=>(mk.outcomes||[]).map(o=>`${mk.id??mk.typeId}:${o.n}:${o.odds}`)).join('|')}`}
function bulletinSignature(ms){return ms.map(analysisKey).join('||')}
function metric(label,value,cls=''){return `<span class="metric ${cls}"><small>${escapeHtml(label)}</small><b>${escapeHtml(value)}</b></span>`}
function marketStats(m){const markets=(m.markets||[]).filter(x=>x&&x.known!==false&&Array.isArray(x.outcomes)&&x.outcomes.some(o=>Number(o.odds)>1));return{markets,total:markets.reduce((s,x)=>s+x.outcomes.filter(o=>Number(o.odds)>1).length,0)}}
function allMarketsHtml(m,opened=true){const {markets,total}=marketStats(m);return `<details class="all-markets" ${opened?'open':''}><summary>📡 Nesine Tam Oran Havuzu · ${markets.length} market / ${total} oran</summary><div class="market-grid">${markets.map(mk=>`<div class="market-group"><b>${escapeHtml(mk.name)}</b><div>${mk.outcomes.filter(o=>Number(o.odds)>1).map(o=>`<span class="market-odd ${o.labelVerified?'':'unverified'}" title="${o.labelVerified?'Nesine etiketi doğrulandı':'Oran gerçek; seçim etiketi ham feed’de doğrulanamadı ve analizde kullanılmaz'}"><i>${escapeHtml(o.label)}</i><strong>${Number(o.odds).toFixed(2)}</strong>${o.labelVerified?'':'<em>etiket?</em>'}</span>`).join('')}</div></div>`).join('')}</div><div class="market-note">“etiket?” görünen oran Nesine akışından gelir; seçim adı güvenle doğrulanamadığı için NEÇ analizine sokulmaz.</div></details>`}
function clientFallback(m,message){return{radar:0,formStatus:'client-fallback',scenario:{title:'Analiz bağlantısı kesildi',summary:'Nesine oranları görünmeye devam ediyor; analiz isteği tamamlanamadı.',formText:'',confidence:0,specialComment:'',specialOdds:null},picks:[],insights:[{title:'⚠️ Teknik not',text:message||'Analiz servisi yanıt vermedi.'}],disclaimer:'Teknik hata halinde sahte seçim üretilmez.'}}
async function requestAnalysis(m){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),50000);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(m),cache:'no-store',signal:ctrl.signal}),text=await r.text();let a;try{a=JSON.parse(text)}catch{throw new Error(`Analiz servisi geçersiz cevap verdi (${r.status})`)}if(!r.ok)throw new Error(a.error||`Analiz alınamadı (${r.status})`);return a}finally{clearTimeout(timer)}}
async function load(){state.loading=true;renderList();try{const q=new URLSearchParams({sport:String(state.sport),date:state.date});if(state.search)q.set('search',state.search);const r=await fetch('/api/bulletin?'+q,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Bülten alınamadı');const next=(j.matches||[]).sort((a,b)=>(a.startTimestamp||9e15)-(b.startTimestamp||9e15)),sig=bulletinSignature(next);if(sig!==state.bulletinSignature){state.analyses.clear();state.bulletinSignature=sig}state.matches=next;state.source=j.source;state.fetchedAt=j.fetchedAt;document.querySelector('#err').innerHTML=''}catch(e){state.matches=[];state.analyses.clear();state.bulletinSignature='';document.querySelector('#err').innerHTML=`<div class="error"><b>${escapeHtml(e.message)}</b><br>Sahte maç veya oran gösterilmiyor.</div>`}finally{state.loading=false;renderAll()}}
function renderAll(){renderToolbar();renderStatus();renderRadar();renderList()}
function renderToolbar(){document.querySelectorAll('[data-sport]').forEach(b=>b.classList.toggle('active',Number(b.dataset.sport)===state.sport));document.querySelectorAll('[data-date]').forEach(b=>b.classList.toggle('active',b.dataset.date===state.date));document.querySelector('#customDate').value=state.date}
function renderStatus(){document.querySelector('#status').innerHTML=state.fetchedAt?`<b>● CANLI BÜLTEN</b><br>${escapeHtml(state.source)} · ${timeTR(Date.parse(state.fetchedAt))} güncellendi · 60 sn yenileme`:'Gerçek veri bekleniyor'}
function renderRadar(){const top=state.matches.map(m=>({m,s:quickRadar(m)})).sort((a,b)=>b.s-a.s).slice(0,3);document.querySelector('#radarGrid').innerHTML=top.length?top.map(({m,s})=>`<div class="radarcard" data-id="${escapeHtml(m.id)}"><small>${escapeHtml(m.league)} · ${timeTR(m.startTimestamp,m.time)}</small><div class="score">${s}</div><b>${escapeHtml(m.home)} — ${escapeHtml(m.away)}</b><small>Flashscore son form + Nesine oranları</small></div>`).join(''):'<div class="empty">Bu tarih için radar adayı yok.</div>';document.querySelectorAll('.radarcard').forEach(x=>x.onclick=()=>openMatch(x.dataset.id))}
function renderList(){const box=document.querySelector('#matches');document.querySelector('#count').textContent=`${state.matches.length} karşılaşma`;document.querySelector('#dayTitle').textContent=fmtDate(state.date);if(state.loading){box.innerHTML='<div class="loading">Nesine bülteni güncelleniyor…</div>';return}if(!state.matches.length){box.innerHTML='<div class="empty">Bu filtrede karşılaşma bulunamadı.</div>';return}box.innerHTML=state.matches.map(m=>{const po=previewOdds(m);return `<div class="match" data-id="${escapeHtml(m.id)}"><div><div class="time">${timeTR(m.startTimestamp,m.time)}</div><div class="sports">${escapeHtml(m.sport)}</div></div><div><div class="league">${escapeHtml(m.league)} · ${m.marketCount} market · ${m.outcomeCount} oran · ${m.verifiedOutcomeCount??0} etiket doğrulandı</div><div class="teams">${escapeHtml(m.home)} — ${escapeHtml(m.away)}</div></div><div class="oddbox">${po.map(o=>`<span class="odd">${escapeHtml(o.label)} <b>${Number(o.odds).toFixed(2)}</b></span>`).join('')}</div></div>`}).join('');document.querySelectorAll('.match').forEach(x=>x.onclick=()=>openMatch(x.dataset.id))}
function modalHeader(m){return `<div class="modaltop"><div><div class="meta">${escapeHtml(m.league)} · ${timeTR(m.startTimestamp,m.time)}</div><h2>${escapeHtml(m.home)} — ${escapeHtml(m.away)}</h2></div><button class="close" id="closeModal">×</button></div>`}
async function openMatch(id){const m=state.matches.find(x=>x.id===id);if(!m)return;const back=document.querySelector('#modalBack'),body=document.querySelector('#modalBody');back.classList.add('show');body.innerHTML=`${modalHeader(m)}<div class="scoreline"><span class="pill lime">📡 ORANLAR CANLI</span><span class="pill">${m.marketCount} market</span><span class="pill">${m.outcomeCount} oran</span></div>${allMarketsHtml(m,true)}<div class="loading"><b>NEÇ analiz hazırlanıyor</b><br>Son maç formu ile gerçek Nesine oranları birlikte hesaplanıyor…</div>`;document.querySelector('#closeModal').onclick=closeModal;const key=analysisKey(m);let a=state.analyses.get(key);if(!a){try{a=await requestAnalysis(m)}catch(e){a=clientFallback(m,e.name==='AbortError'?'Analiz zaman aşımına uğradı.':e.message)}state.analyses.set(key,a)}renderAnalysis(m,a)}
function sourceHtml(a){const s=a?.research?.sources||[];if(!s.length)return'';return `<details class="all-markets"><summary>🔗 Veri Kaynağı · ${s.length}</summary><div class="market-grid">${s.map(x=>`<div class="market-group"><a href="${escapeHtml(x.url)}" target="_blank" rel="noopener">${escapeHtml(x.title||x.url)}</a></div>`).join('')}</div></details>`}
function renderAnalysis(m,a){const body=document.querySelector('#modalBody'),picks=Array.isArray(a.picks)?a.picks:[],s=a.scenario||{},special=picks.find(p=>p.label==='NEÇ Özel'&&p.available),fallback=a.formStatus==='fallback'||a.formStatus==='client-fallback'||a.degraded;body.innerHTML=`${modalHeader(m)}<div class="scoreline"><span class="pill lime">📡 ${m.outcomeCount} NESİNE ORANI</span><span class="pill lime">NEÇ RADAR ${Number(a.radar||0)}/99</span><span class="pill">${a.researchMode?'⚡ Flashscore son form':'📊 NEÇ piyasa modeli'}</span><span class="pill">Güven %${Number(s.confidence||0)}</span>${fallback?'<span class="pill fallback">Yedek mod</span>':''}</div>${allMarketsHtml(m,true)}<section class="scenario"><div class="scenario-kicker">🧭 NEÇ MAÇ ANALİZİ</div><h3>${escapeHtml(s.title||'Maç senaryosu')}</h3><p>${escapeHtml(s.summary||'')}</p><div class="formline"><b>Veri özeti:</b> ${escapeHtml(s.formText||'Ek veri yok')}</div></section>${picks.length?`<section class="nec-special"><div><small>⭐ NEÇ ÖZEL YORUMU</small><p>${escapeHtml(s.specialComment||'')}</p></div><div class="special-price"><small>NEÇ ÖZEL ORAN</small><b>${special?Number(special.odds).toFixed(2):s.specialOdds?Number(s.specialOdds).toFixed(2):'—'}</b><span>${special?`${escapeHtml(special.market)} · ${escapeHtml(special.selection)}`:'Uygun seçim yok'}</span></div></section><div class="picks">${picks.map(p=>`<div class="pick ${p.available?'':'na'} ${p.recommended?'recommended':''}"><div class="tag">${escapeHtml(p.tag||'NEÇ')}</div><h3>${escapeHtml(p.label)}</h3>${p.available?`<div class="sel"><span>${escapeHtml(p.market)} · ${escapeHtml(p.selection)}</span><span class="oddnum">${Number(p.odds).toFixed(2)}</span></div><div class="metrics">${p.av===null||p.av===undefined?'':metric('NEÇ AV',`${Number(p.av)>=0?'+':''}${Number(p.av||0).toFixed(1)} puan`,Number(p.av)>0?'positive':Number(p.av)<0?'negative':'muted')}${metric('Güven',`%${Number(p.confidencePct||0).toFixed(0)}`,'confidence')}</div><div class="reason">${escapeHtml(p.reason)}</div>`:`<div class="reason">${escapeHtml(p.reason)}</div>`}</div>`).join('')}</div>`:'<div class="error"><b>Bu maç için seçim üretilemedi.</b><br>Teknik veri hatası devam ediyorsa logdan görülebilir.</div>'}${sourceHtml(a)}<div class="insights">${(a.insights||[]).map(i=>`<div class="insight"><b>${escapeHtml(i.title)}</b><p>${escapeHtml(i.text)}</p></div>`).join('')}</div>${a.researchWarning?`<div class="warn"><b>Veri notu:</b> ${escapeHtml(a.researchWarning)}</div>`:''}${a.formWarning?`<div class="warn"><b>Veri notu:</b> ${escapeHtml(a.formWarning)}</div>`:''}<div class="warn">${escapeHtml(a.disclaimer||'')}</div>`;document.querySelector('#closeModal').onclick=closeModal}
function closeModal(){document.querySelector('#modalBack').classList.remove('show')}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-sport]').forEach(b=>b.onclick=()=>{state.sport=Number(b.dataset.sport);load()});document.querySelector('#todayBtn').dataset.date=todayTR();document.querySelector('#tomorrowBtn').dataset.date=tomorrowTR();document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.date=b.dataset.date;load()});document.querySelector('#customDate').onchange=e=>{state.date=e.target.value;load()};let t;document.querySelector('#search').oninput=e=>{clearTimeout(t);t=setTimeout(()=>{state.search=e.target.value;load()},350)};document.querySelector('#modalBack').onclick=e=>{if(e.target.id==='modalBack')closeModal()};load();setInterval(load,60000)});