function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[ı]/g,'i').replace(/[ş]/g,'s').replace(/[ç]/g,'c').replace(/[ğ]/g,'g').replace(/[ö]/g,'o').replace(/[ü]/g,'u').replace(/[^a-z0-9\s+.-]/g,' ').replace(/\s+/g,' ').trim()}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function verified(o){return o?.labelVerified===true||Boolean(o?.sourceLabel)}
function formOk(f){return !!(f?.home?.played>=4&&f?.away?.played>=4)}
function playerSide(label,match){const l=norm(label),h=norm(match.home),a=norm(match.away);if(l===h||l.includes(h)||h.includes(l))return'home';if(l===a||l.includes(a)||a.includes(l))return'away';return null}
function sideName(s,m){return s==='home'?m.home:m.away}
function fairMarket(m){const rows=(m.outcomes||[]).filter(o=>Number(o.odds)>1&&verified(o)).map(o=>({outcome:o,odds:Number(o.odds)}));const sum=rows.reduce((s,r)=>s+1/r.odds,0);for(const r of rows)r.fair=sum?(1/r.odds)/sum*100:100/r.odds;return rows}
function winPct(x){return x?.played?x.wins/x.played*100:50}
function straightPct(x){return x?.played?(x.straightWins||0)/x.played*100:0}
function deciderPct(x){return x?.played?(x.deciders||0)/x.played*100:0}
function firstMarket(match){return(match.markets||[]).find(m=>m.kind==='match_winner'||Number(m.typeId)===182)}
function chooseDirection(match,form,m){const rows=fairMarket(m);if(!rows.length)return null;const marketLead=[...rows].sort((a,b)=>b.fair-a.fair)[0];if(!formOk(form))return{rows,row:marketLead,leader:playerSide(marketLead.outcome.label,match)||'home',conflict:false,homeWin:50,awayWin:50};const homeWin=winPct(form.home),awayWin=winPct(form.away),formLeader=homeWin>=awayWin?'home':'away',marketLeader=playerSide(marketLead.outcome.label,match)||formLeader;let scored=rows.map(r=>{const s=playerSide(r.outcome.label,match),fw=s==='home'?homeWin:awayWin;return{...r,side:s,score:r.fair*.64+fw*.36}}).sort((a,b)=>b.score-a.score);let row=scored[0]||marketLead;if(marketLead.odds<=1.25)row=marketLead;return{rows,row,leader:playerSide(row.outcome.label,match)||marketLeader,formLeader,marketLeader,conflict:formLeader!==marketLeader,homeWin,awayWin}}
function marketSide(label,match){return playerSide(label,match)}
function isOver(label){const l=norm(label);return l.includes('ust')||l.includes('over')}
function isUnder(label){const l=norm(label);return l.includes('alt')||l.includes('under')}
function scoreLabel(label){const z=String(label||'').match(/([20-3])\s*[-:]\s*([0-3])/);return z?[+z[1],+z[2]]:null}
function rowModel(c,dir,form,match){const side=marketSide(c.outcome.label,match),own=dir.leader==='home'?form?.home:form?.away,opp=dir.leader==='home'?form?.away:form?.home;let m=c.fair,evidence=0;const k=c.market.kind,l=c.outcome.label;if(k==='match_winner'){if(side){const fw=side==='home'?dir.homeWin:dir.awayWin;m=c.fair*.62+fw*.38;evidence=(side===dir.leader?10:-12)+Math.abs(dir.homeWin-dir.awayWin)*.15}}else if(['first_set_winner','set_winner'].includes(k)){if(side){const fw=side==='home'?dir.homeWin:dir.awayWin;m=c.fair*.74+fw*.26;evidence=side===dir.leader?5:-6}}else if(['set_handicap','game_handicap'].includes(k)){if(side){const fw=side==='home'?dir.homeWin:dir.awayWin,marg=Math.abs(dir.homeWin-dir.awayWin);m=c.fair*.72+fw*.28;evidence=(side===dir.leader?5:-5)+marg*.08}}else if(k==='set_score'){const sc=scoreLabel(l),ss=own?straightPct(own):0,dc=own?deciderPct(own):0;if(sc){const chosenWins=sc[0]>sc[1];if(chosenWins&&side===dir.leader){m=sc[1]===0?clamp(ss*.75+c.fair*.25,5,85):clamp(dc*.5+dir.row.fair*.25+c.fair*.25,5,75);evidence=sc[1]===0?Math.max(0,ss-35)*.2:Math.max(0,dc-30)*.15}}}else if(k==='total_games'){const dec=own&&opp?(deciderPct(own)+deciderPct(opp))/2:50;if(isOver(l)){m=c.fair*.65+dec*.35;evidence=(dec-45)*.18}else if(isUnder(l)){m=c.fair*.65+(100-dec)*.35;evidence=(55-dec)*.18}}if(!Number.isFinite(m))m=c.fair;return{fair:c.fair,model:clamp(m,3,96),av:clamp(m-c.fair,-20,20),evidence}}
function allCandidates(match,dir,form){const allowed=new Set(['match_winner','first_set_winner','set_winner','set_handicap','game_handicap','total_games','set_score']),a=[];for(const market of match.markets||[]){if(!allowed.has(market.kind))continue;for(const r of fairMarket(market)){const c={market,outcome:r.outcome,odds:r.odds,fair:r.fair,key:`${market.id??market.typeId}:${r.outcome.n}`};const side=marketSide(r.outcome.label,match);if(side&&side!==dir.leader&&market.kind!=='total_games')continue;c.x=rowModel(c,dir,form,match);a.push(c)}}return a}
function prose(match,form,dir){const lead=sideName(dir.leader,match);if(!formOk(form)){const prices=dir.rows.map(r=>`${r.outcome.label} ${r.odds.toFixed(2)}`).join(' · ');return `${lead} fiyatlamada önde: ${prices}. Son maç verisi bu istekte eşleşmediği için ekstra performans hikâyesi uydurmuyorum; bu karşılaşmada sadece fiyat tarafında ${lead} yönüne daha yakınım.`}const h=form.home,a=form.away,hs=straightPct(h),as=straightPct(a),hd=deciderPct(h),ad=deciderPct(a);let t=`${match.home} son ${h.played} maçta ${h.wins} kez, ${match.away} ise ${a.wins} kez kazandı. ${match.home} bu süreçte ${h.straightWins||0} maçı set vermeden bitirdi; ${match.away} ${a.straightWins||0} kez 2-0/straight-set galibiyet aldı.`;t+=` Karar setine giden maç oranları yaklaşık %${hd.toFixed(0)} ve %${ad.toFixed(0)}.`;if(dir.conflict)t+=` Piyasa ile son form farklı tarafa işaret ediyor; bu nedenle tek tarafı ezici üstün görmüyorum.`;else t+=` Piyasa ve son form ${lead} tarafında aynı yöne bakıyor.`;return t}
function reason(c,match,form,dir,role){const lead=sideName(dir.leader,match),k=c.market.kind,l=c.outcome.label;if(k==='match_winner')return `${lead} bu maçta benim kazanan tarafım. ${formOk(form)?`Son 10 maç kazanma profili ${match.home} %${dir.homeWin.toFixed(0)}, ${match.away} %${dir.awayWin.toFixed(0)}; `:''}${l} @ ${c.odds.toFixed(2)} fiyatını bu ana görüş için değerlendiriyorum.`;if(k==='first_set_winner')return `${lead} maç geneli için önde. İlk sete de daha iyi girmesini bekliyorsam ${l} @ ${c.odds.toFixed(2)} mantıklı ikinci açı; fakat ilk set tek başına maç sonucundan daha oynaktır.`;if(k==='set_winner')return `${l} @ ${c.odds.toFixed(2)} ana oyuncu yönümü set bazında taşıyor. Rakibin maç içinde bir setlik yükseliş ihtimali olduğu için bunu maç kazananından ayrı riskte tutuyorum.`;if(k==='set_handicap'||k==='game_handicap')return `Burada sadece kazanmasını değil fark yaratmasını istiyorum. ${lead} form avantajını sete/oyuna çevirebilirse ${l} @ ${c.odds.toFixed(2)} daha yüksek fiyat veriyor; bu nedenle sürpriz katmanında anlamlı.`;if(k==='set_score'){const sc=scoreLabel(l),own=dir.leader==='home'?form?.home:form?.away;return `${l} @ ${c.odds.toFixed(2)} tam set senaryosu. ${formOk(form)&&own?`${lead} son ${own.played} maçın ${own.straightWins||0}'ini set vermeden kazandı; `:''}${sc&&sc[1]===0?'bu nedenle düz set galibiyeti düşünülebilir':'maçın karar setine uzama ihtimali bu fiyatın ana riski'}.`;if(k==='total_games'){const own=dir.leader==='home'?form?.home:form?.away,opp=dir.leader==='home'?form?.away:form?.home,dec=own&&opp?(deciderPct(own)+deciderPct(opp))/2:null;return `Bu seçim taraf değil maç uzunluğu fikri. ${dec!==null?`İki oyuncunun son maçlarında karar setine gitme ortalaması yaklaşık %${dec.toFixed(0)}. `:''}${l} @ ${c.odds.toFixed(2)} bu nedenle setlerin ne kadar uzayacağına dair ayrı bir bahis.`}return `${c.market.name} · ${l} @ ${c.odds.toFixed(2)} ana tenis görüşümden farklı ama aynı maç profilini kullanan bir fiyat.`}
function scoreRole(c,role){let s=c.x.model*.36+c.x.av*.9+c.x.evidence*.65;if(role==='main'){if(c.market.kind==='match_winner')s+=12;if(c.odds>3.2)s-=20}else if(role==='safe'){if(c.odds>1.9)s-=15;if(['match_winner','first_set_winner'].includes(c.market.kind))s+=4}else if(role==='surprise'){if(c.odds<1.8||c.odds>5.5)s-=24;if(['set_handicap','game_handicap','set_score'].includes(c.market.kind))s+=5}else if(role==='big'){if(c.odds<3||c.odds>14)s-=28;if(c.market.kind==='set_score')s+=8}else if(role==='special'){if(c.odds<1.5||c.odds>7)s-=20;if(c.market.kind==='total_games')s+=6}return s}
function choose(cands,used,role){return cands.filter(c=>!used.has(c.key)).map(c=>({c,s:scoreRole(c,role)})).filter(z=>z.s>-8).sort((a,b)=>b.s-a.s)[0]?.c||null}
function priceOpinion(match,form,dir,picks){const main=picks.find(p=>p.available),lead=sideName(dir.leader,match);if(!main)return `Bu maçta güvenilir fiyat bulamadım; ${lead} yönüne yakın olsam da bahis yerine pas daha doğru.`;if(main.odds<=1.28)return `${lead} maç görüşüm ama ${main.odds.toFixed(2)} çok kısa. Böyle bir fiyatta hata payı az; farklı set/handikap marketinde daha iyi değer yoksa tekli bahis olarak PAS ederim.`;if(formOk(form)){const own=dir.leader==='home'?dir.homeWin:dir.awayWin,opp=dir.leader==='home'?dir.awayWin:dir.homeWin;if(own-opp>=20&&main.odds>=1.4&&main.odds<=2.2)return `${lead} son formda belirgin avantajlı (%${own.toFixed(0)} - %${opp.toFixed(0)}) ve ${main.odds.toFixed(2)} fiyatı ezilmiş değil. Bu maçta ilk tercihim bu; daha yüksek oran ararsam aynı oyuncunun set/handikap tarafına geçerim.`}if(dir.conflict)return `${lead} piyasa tarafında önde ama son form tam destek vermiyor. ${main.odds.toFixed(2)} için agresif değilim; küçük risk veya PAS daha doğru.`;return `${lead} tarafına yakınım ve ${main.odds.toFixed(2)} fiyatı kabul edilebilir. Maçta farklı set/oyun marketleri varsa ana oyuncu yönünü bozmadan onları daha yüksek fiyat alternatifi olarak değerlendiririm.`}
function analyzeTennis(match,form){const mainMarket=firstMarket(match);if(!mainMarket)return null;const dir=chooseDirection(match,form,mainMarket);if(!dir)return null;const cands=allCandidates(match,dir,form),used=new Set(),defs=[['Ana Tenis Görüşü','🎾 ANA YÖN','main'],['Kontrollü Tenis Fikri','🛡️ KONTROLLÜ','safe'],['Tenis Sürprizi','🎯 TENİS SÜRPRİZİ','surprise'],['Yüksek Oran Tenis','🔥 YÜKSEK ORAN','big'],['NEÇ Tenis Özel','⭐ TENİS ÖZEL','special']],picks=[];for(const [label,tag,role] of defs){const c=choose(cands,used,role);if(!c){if(role==='main')continue;else continue}used.add(c.key);const conf=Math.round(clamp(c.x.model*.58+c.x.evidence*.7+(formOk(form)?6:0),32,80));picks.push({label,tag,available:true,market:c.market.name,selection:c.outcome.label,odds:c.odds,av:+c.x.av.toFixed(1),model:+c.x.model.toFixed(1),fair:+c.x.fair.toFixed(1),confidencePct:conf,recommended:c.x.av>=2&&conf>=52,reason:reason(c,match,form,dir,role)})}
 if(!picks.some(p=>p.market===mainMarket.name)){const r=dir.row,c={market:mainMarket,outcome:r.outcome,odds:r.odds,fair:r.fair,x:{model:r.fair,av:0,evidence:0}};picks.unshift({label:'Ana Tenis Görüşü',tag:'🎾 ANA YÖN',available:true,market:mainMarket.name,selection:r.outcome.label,odds:r.odds,av:0,confidencePct:formOk(form)?58:42,recommended:false,reason:reason(c,match,form,dir,'main')})}
 const summary=prose(match,form,dir),op=priceOpinion(match,form,dir,picks),special=picks.find(x=>x.label==='NEÇ Tenis Özel');return{radar:Math.round(clamp(38+Math.max(0,...picks.map(x=>x.av||0))*1.7+(formOk(form)?8:0),1,90)),form,formStatus:formOk(form)?'flashscore-tennis':'market-only-tennis',scenario:{title:`${sideName(dir.leader,match)} tarafı önde`,summary,formText:formOk(form)?`${match.home}: ${form.home.wins}/${form.home.played} galibiyet, ${form.home.straightWins||0} düz set; ${match.away}: ${form.away.wins}/${form.away.played} galibiyet, ${form.away.straightWins||0} düz set.`:'Son maç formu eşleşmedi; açık Nesine fiyatlarıyla düşük güvenli okuma yapıldı.',confidence:picks[0]?.confidencePct||42,betOpinion:op,betOpinionTitle:'🎾 NEÇ TENİS FİKRİ',specialComment:special?.reason||'',specialOdds:special?.odds??null},picks,ideas:[],insights:[{title:'🎾 Maçın ritmi',text:summary},{title:'💸 Benim fiyat fikrim',text:op}],research:{engine:form?.source||'Nesine tenis fiyatları',sources:form?.flashscoreUrl?[{url:form.flashscoreUrl,title:'Flashscore tenis maç merkezi'}]:[]},analyzedAt:new Date().toISOString(),disclaimer:'NEÇ tenis yorumları olasılık ve fiyat değerlendirmesidir; sonuç garantisi değildir.'}}
module.exports={analyzeTennis};
