const base=require('./analyzer-final');
function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim()}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function avg(n,d){return d>0?n/d:0}
function verified(o){return o?.labelVerified===true||Boolean(o?.sourceLabel)}
function id(m,o){return `${m.name}|${o.label}`}
function fair(m,o){const xs=(m.outcomes||[]).filter(x=>Number(x.odds)>1&&verified(x));const sum=xs.reduce((s,x)=>s+1/Number(x.odds),0);return sum?((1/Number(o.odds))/sum)*100:100/Number(o.odds)}
function side(label,m){const l=norm(label),h=norm(m.home),a=norm(m.away);if(l==='1'||l==='ev sahibi'||l==='home'||(h&&(l===h||l.includes(h))))return'home';if(l==='x'||l.includes('beraber')||l==='draw')return'draw';if(l==='2'||l==='deplasman'||l==='away'||(a&&(l===a||l.includes(a))))return'away';return null}
function htft(label){const z=String(label||'').toUpperCase().match(/([12X])\s*[\/-]\s*([12X])/);if(!z)return null;const cv=x=>x==='1'?'home':x==='2'?'away':'draw';return[cv(z[1]),cv(z[2])]}
function resultPart(label){const z=String(label||'').toUpperCase().match(/(^|\s|\+)(1|X|2)(?=\s|\+|\/|$)/);if(!z)return null;return z[2]==='1'?'home':z[2]==='2'?'away':'draw'}
function totalDir(label){const l=norm(label);if(l.includes('üst')||l.includes('ust')||l.includes('over'))return'over';if(l.includes('alt')||l.includes('under'))return'under';return null}
function bttsDir(label){const l=norm(label);if(l.includes('var')||l.includes('evet')||l.includes('yes'))return'yes';if(l.includes('yok')||l.includes('hayır')||l.includes('hayir')||l.includes('no'))return'no';return null}
function rangeMid(label){const l=norm(label),z=l.match(/(\d+)\s*[-:]\s*(\d+)/);if(z)return(+z[1]+ +z[2])/2;if(l.includes('6+'))return 6.5;return null}
function profile(match,form){if(!(form?.home?.played>=4&&form?.away?.played>=4))return null;const h=form.home,a=form.away,total=h.played+a.played||1,hp=avg(h.wins,h.played)*.55+avg(a.losses,a.played)*.45,ap=avg(a.wins,a.played)*.55+avg(h.losses,h.played)*.45,leader=hp>=ap?'home':'away',over=(h.over25+a.over25)/total,btts=(h.btts+a.btts)/total,expH=clamp(((h.avgGF||0)+(a.avgGA||0))/2,.2,4.2),expA=clamp(((a.avgGF||0)+(h.avgGA||0))/2,.2,4.2);return{h,a,leader,over,btts,expH,expA,totalExp:expH+expA}}
function evidence(c,p,match){if(!p)return 0;const k=c.market.kind,l=c.outcome.label;let s=0;if(k==='htft'){const z=htft(l);if(!z)return-4;if(z[1]===p.leader)s+=4.5;if(z[0]===p.leader)s+=1;else if(z[0]!==z[1])s-=1;return s}if(k==='first_goal_team'){const x=side(l,match);if(x===p.leader)s+=4;if(x==='home'&&p.expH>p.expA)s+=2;if(x==='away'&&p.expA>p.expH)s+=2;return s}if(k==='goal_range'){const mid=rangeMid(l);return mid===null?0:clamp(5-Math.abs(mid-p.totalExp)*2,-3,5)}if(k==='result_total_combo'){const r=resultPart(l),d=totalDir(l);if(r===p.leader)s+=4;else if(r)s-=4;if(d==='over')s+=(p.over-.5)*9;if(d==='under')s+=(0.5-p.over)*9;return s}if(k==='result_btts_combo'){const r=resultPart(l),b=bttsDir(l);if(r===p.leader)s+=4;else if(r)s-=4;if(b==='yes')s+=(p.btts-.5)*9;if(b==='no')s+=(0.5-p.btts)*9;return s}if(k==='total_btts_combo'){const d=totalDir(l),b=bttsDir(l);if(d==='over')s+=(p.over-.5)*10;if(d==='under')s+=(0.5-p.over)*10;if(b==='yes')s+=(p.btts-.5)*10;if(b==='no')s+=(0.5-p.btts)*10;return s}if(k==='total_goals'){const d=totalDir(l);return d==='over'?(p.over-.5)*8:d==='under'?(0.5-p.over)*8:0}if(k==='btts'){const b=bttsDir(l);return b==='yes'?(p.btts-.5)*8:b==='no'?(0.5-p.btts)*8:0}const x=side(l,match);return x===p.leader?2:x?-2:0}
function novelty(k){return({result_total_combo:10,result_btts_combo:9.8,total_btts_combo:9.6,first_goal_team:9,goal_range:8.6,htft:8.2,btts:5.4,total_goals:5.2,double_chance:3,match_result:2.5,match_winner:2.5})[k]||2}
function sweet(o){if(o>=2.2&&o<=7)return 5;if(o>7&&o<=12)return 3;if(o>=1.7)return 2.5;return 1}
function all(match){const kinds=new Set(['match_result','match_winner','double_chance','total_goals','btts','htft','goal_range','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo']),out=[];for(const m of match.markets||[]){if(!kinds.has(m.kind))continue;for(const o of m.outcomes||[]){if(Number(o.odds)>1&&verified(o))out.push({market:m,outcome:o,odds:Number(o.odds)})}}return out}
function explain(c,p,match,label,e,av){const base=p?`${match.home} ${p.h.wins}G-${p.h.draws}B-${p.h.losses}M, ${match.away} ${p.a.wins}G-${p.a.draws}B-${p.a.losses}M; Üst %${(p.over*100).toFixed(0)}, KG Var %${(p.btts*100).toFixed(0)}, gol beklentisi ${p.expH.toFixed(2)}-${p.expA.toFixed(2)}.`:'Form eşleşmesi yok.';const risk=label==='Çok Sürpriz'?'Bu oran yüksek olduğu için uç senaryo; ana tahmin değil.':label==='Sürpriz Seçim'?'Bu seçim orta-yüksek oranlı alternatif senaryo.':'Bu seçim özel kartta veri desteği ve farklı market açısı birlikte değerlendirildi.';return `NEÇ yorumu: ${c.market.name} · ${c.outcome.label} (${c.odds.toFixed(2)}). ${base} ${risk} Veri desteği ${e.toFixed(1)}; hesaplanan AV ${av>=0?'+':''}${av.toFixed(1)} puan.`}
function candidate(c,p,match){const f=fair(c.market,c.outcome),e=evidence(c,p,match),model=p?clamp(f+e*1.6,1,99):f,av=model-f;return{...c,fair:f,evidence:e,model,av,score:e*2.7+novelty(c.market.kind)+sweet(c.odds)-(c.odds>15?3:0)}}
function replaceRole(result,label,band,pool,p,match,blocked){const idx=result.picks.findIndex(x=>x.label===label);if(idx<0)return;const current=result.picks[idx];if(band(current.odds))return;const cand=pool.filter(x=>!blocked.has(id(x.market,x.outcome))&&band(x.odds)&&x.evidence>=0&&x.av>=0).sort((a,b)=>(b.av*2+b.evidence+sweet(b.odds))-(a.av*2+a.evidence+sweet(a.odds)))[0];if(!cand)return;blocked.delete(`${current.market}|${current.selection}`);blocked.add(id(cand.market,cand.outcome));result.picks[idx]={...current,market:cand.market.name,selection:cand.outcome.label,odds:cand.odds,av:+cand.av.toFixed(1),model:+cand.model.toFixed(1),fair:+cand.fair.toFixed(1),confidencePct:label==='Çok Sürpriz'?38:48,recommended:cand.av>1,reason:explain(cand,p,match,label,cand.evidence,cand.av)}}
function polish(result,match,form){if(!result||Number(match?.sportType)!==1||!Array.isArray(result.picks))return result;const p=profile(match,form);if(!p)return result;const pool=all(match).map(c=>candidate(c,p,match)),blocked=new Set(result.picks.map(x=>`${x.market}|${x.selection}`));replaceRole(result,'Sürpriz Seçim',o=>o>=2&&o<=5.5,pool,p,match,blocked);replaceRole(result,'Çok Sürpriz',o=>o>=3.5&&o<=15,pool,p,match,blocked);
 const spIdx=result.picks.findIndex(x=>x.label==='NEÇ Özel');if(spIdx>=0){const current=result.picks[spIdx];blocked.delete(`${current.market}|${current.selection}`);const best=pool.filter(x=>!blocked.has(id(x.market,x.outcome))&&x.odds>=1.7&&x.odds<=12&&x.evidence>0.25&&x.av>0.3&&(x.market.outcomes||[]).filter(o=>Number(o.odds)>1&&verified(o)).length>=2).sort((a,b)=>b.score-a.score)[0];if(best){blocked.add(id(best.market,best.outcome));const confidence=Math.round(clamp(48+best.evidence*2+(best.odds<=7?4:0),32,72));result.picks[spIdx]={label:'NEÇ Özel',tag:'⭐ NEÇ ÖZEL',available:true,market:best.market.name,selection:best.outcome.label,odds:best.odds,av:+best.av.toFixed(1),model:+best.model.toFixed(1),fair:+best.fair.toFixed(1),confidencePct:confidence,recommended:best.av>1.5,ideaScore:+best.score.toFixed(1),ideaEvidence:+best.evidence.toFixed(1),reason:`NEÇ Özel fikri: ${best.market.name} · ${best.outcome.label} (${best.odds.toFixed(2)}). ${match.home} ${p.h.wins}G-${p.h.draws}B-${p.h.losses}M, ${match.away} ${p.a.wins}G-${p.a.draws}B-${p.a.losses}M; Üst %${(p.over*100).toFixed(0)}, KG Var %${(p.btts*100).toFixed(0)}, gol beklentisi ${p.expH.toFixed(2)}-${p.expA.toFixed(2)}. Bu seçim yalnızca yüksek oranlı olduğu için değil; veri desteği ${best.evidence.toFixed(1)} pozitif, diğer dört karttan farklı ve kendi AV'si +${best.av.toFixed(1)} puan olduğu için seçildi.`};result.scenario.specialComment=result.picks[spIdx].reason;result.scenario.specialOdds=best.odds;result.scenario.specialMarket=best.market.name;result.scenario.specialSelection=best.outcome.label}else{result.picks[spIdx]={...current,recommended:false,av:0,ideaEvidence:0,reason:`NEÇ Özel: Bu maçta diğer dört karttan farklı, aynı zamanda pozitif veri desteği ve pozitif AV taşıyan ek bir market bulunamadı. Bu nedenle bu kart değer iddiası taşımıyor; sırf beşinci seçim olsun diye yüksek oran kovalanmadı.`};result.scenario.specialComment=result.picks[spIdx].reason}}
 return result}
function analyzeMatch(match,form){return polish(base.analyzeMatch(match,form),match,form)}
module.exports={analyzeMatch};
