const base=require('./analyzer-coherent');
function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[ı]/g,'i').replace(/[ş]/g,'s').replace(/[ç]/g,'c').replace(/[ğ]/g,'g').replace(/[ö]/g,'o').replace(/[ü]/g,'u').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function verified(o){return o?.labelVerified===true||Boolean(o?.sourceLabel)}
function side(label,m){const l=norm(label),h=norm(m.home),a=norm(m.away);if(l==='1'||(h&&l.includes(h)))return'home';if(l==='2'||(a&&l.includes(a)))return'away';if(l==='x'||l.includes('beraber'))return'draw';return null}
function dc(label){const l=norm(label).replace(/\s/g,'');if(l.startsWith('1x'))return['home','draw'];if(l.startsWith('x2'))return['draw','away'];if(l.startsWith('12'))return['home','away'];return[]}
function htft(label){const z=String(label||'').toUpperCase().match(/([12X])\s*[\/-]\s*([12X])/);if(!z)return null;const cv=x=>x==='1'?'home':x==='2'?'away':'draw';return[cv(z[1]),cv(z[2])]}
function totalDir(label){const l=norm(label);return l.includes('ust')?'over':l.includes('alt')?'under':null}
function bttsDir(label){const l=norm(label);return l.includes('var')?'yes':l.includes('yok')||l.includes('hayir')?'no':null}
function range(label){const l=norm(label);if(l.includes('6+'))return[6,20];const z=l.match(/(\d+)\s*[-:]\s*(\d+)/);return z?[+z[1],+z[2]]:null}
const SAFE=new Set(['match_result','match_winner','double_chance','htft','total_goals','btts','goal_range','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo']);
function profile(form){if(!(form?.home?.played>=4&&form?.away?.played>=4))return null;const h=form.home,a=form.away,T=h.played+a.played,eh=((h.avgGF||0)+(a.avgGA||0))/2,ea=((a.avgGF||0)+(h.avgGA||0))/2;return{over:(h.over25+a.over25)/T,btts:(h.btts+a.btts)/T,totalExp:eh+ea}}
function good(c,main,p,m){if(!SAFE.has(c.market.kind)||/^Nesine Market\b/i.test(c.market.name))return false;const k=c.market.kind,l=c.outcome.label;if(['match_result','match_winner'].includes(k))return side(l,m)===main;if(k==='double_chance')return dc(l).includes(main);if(k==='htft')return htft(l)?.[1]===main;if(k==='first_goal_team'){const x=side(l,m);if(x&&x!==main)return false}if(!p)return true;if(k==='total_goals'){const d=totalDir(l);return p.over>=.55?d==='over':p.over<=.45?d==='under':true}if(k==='btts'){const d=bttsDir(l);return p.btts>=.52?d==='yes':p.btts<=.48?d==='no':true}if(k==='goal_range'){const r=range(l);return !r||p.totalExp>=r[0]-.65&&p.totalExp<=r[1]+.65}return true}
function band(label,o){if(label==='Temkinli Seçim')return o<=2;if(label==='Sürpriz Seçim')return o>=2&&o<=5.5;if(label==='Çok Sürpriz')return o>=3.5&&o<=15;if(label==='NEÇ Özel')return o>=1.65&&o<=12;return true}
function why(c,label,main,p,m){const lead=main==='home'?m.home:main==='away'?m.away:'beraberlik';if(c.market.kind==='double_chance')return `NEÇ düşüncesi: Ana yön ${lead}. ${c.outcome.label} bu tarafı beraberlik ihtimaliyle birlikte koruyor; Temkinli kartta beraberliği dışlayan 12 yerine bu korumayı tercih ediyorum.`;if(c.market.kind==='htft'){const z=htft(c.outcome.label);return `NEÇ düşüncesi: ${c.outcome.label}, ilk yarı ${z?.[0]==='home'?m.home:z?.[0]==='away'?m.away:'beraberlik'} / maç sonu ${lead}. Final ayağı ana maç hikâyesiyle aynı; ilk yarı şartı oranı yükselten ekstra risk.`}if(c.market.kind==='total_goals')return `NEÇ düşüncesi: Ana yön ${lead}; son formda 2.5 Üst eğilimi yaklaşık %${p?(p.over*100).toFixed(0):'—'}. ${c.outcome.label} bu tempo yönüyle aynı tarafta.`;if(c.market.kind==='btts')return `NEÇ düşüncesi: KG Var eğilimi yaklaşık %${p?(p.btts*100).toFixed(0):'—'}. ${c.outcome.label} ana maç hikâyesine ters düşmeden iki takımın skor katkısını ayrıca fiyatlıyor.`;if(c.market.kind==='goal_range')return `NEÇ düşüncesi: Toplam gol beklentisi ${p?p.totalExp.toFixed(2):'—'} civarı. ${c.outcome.label} bu merkeze yakın dar ve daha yüksek oranlı skor senaryosu.`;return `NEÇ düşüncesi: Ana yön ${lead}; ${c.market.name} · ${c.outcome.label} bu omurgayı bozmadan farklı bir risk katmanı ekliyor.`}
function analyzeMatch(match,form){const r=base.analyzeMatch(match,form);if(!r?.picks||Number(match?.sportType)!==1)return r;const mainPick=r.picks.find(x=>x.label==='Ana Senaryo'),main=mainPick?side(mainPick.selection,match):null;if(!main)return r;const p=profile(form),all=[];for(const market of match.markets||[])for(const outcome of market.outcomes||[]){const odds=Number(outcome.odds);if(odds>1&&verified(outcome))all.push({market,outcome,odds})}const used=new Set(r.picks.map(x=>`${x.market}|${x.selection}`));const safeIdx=r.picks.findIndex(x=>x.label==='Temkinli Seçim');if(safeIdx>=0&&main!=='draw'){const want=main==='home'?'1x':'x2',best=all.filter(c=>c.market.kind==='double_chance'&&dc(c.outcome.label).includes(main)&&dc(c.outcome.label).includes('draw')&&c.odds<=2).sort((a,b)=>a.odds-b.odds)[0];if(best){const old=r.picks[safeIdx];used.delete(`${old.market}|${old.selection}`);used.add(`${best.market.name}|${best.outcome.label}`);r.picks[safeIdx]={...old,market:best.market.name,selection:best.outcome.label,odds:best.odds,av:0,recommended:false,confidencePct:64,reason:why(best,'Temkinli Seçim',main,p,match)}}for(const label of ['Sürpriz Seçim','Çok Sürpriz','NEÇ Özel']){const i=r.picks.findIndex(x=>x.label===label);if(i<0)continue;const cur=r.picks[i],mk=(match.markets||[]).find(x=>x.name===cur.market),o=mk?.outcomes?.find(x=>x.label===cur.selection&&Number(x.odds)===Number(cur.odds)),cc=mk&&o?{market:mk,outcome:o,odds:Number(o.odds)}:null;if(cc&&band(label,cc.odds)&&good(cc,main,p,match)){cur.reason=why(cc,label,main,p,match);continue}used.delete(`${cur.market}|${cur.selection}`);let q=all.filter(c=>!used.has(`${c.market.name}|${c.outcome.label}`)&&band(label,c.odds)&&good(c,main,p,match));q.sort((a,b)=>{const score=x=>(x.market.kind==='htft'?9:x.market.kind==='goal_range'?8:x.market.kind==='total_goals'?7:x.market.kind==='btts'?6:4)+Math.log(x.odds);return score(b)-score(a)});const best=q[0];if(!best)continue;used.add(`${best.market.name}|${best.outcome.label}`);r.picks[i]={...cur,market:best.market.name,selection:best.outcome.label,odds:best.odds,av:0,recommended:false,reason:why(best,label,main,p,match)}}const sp=r.picks.find(x=>x.label==='NEÇ Özel');if(sp&&r.scenario){r.scenario.specialComment=sp.reason;r.scenario.specialOdds=sp.odds;r.scenario.specialMarket=sp.market;r.scenario.specialSelection=sp.selection}return r}
module.exports={analyzeMatch};
