const base=require('./analyzer-v3');
function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim()}
function verified(o){return o?.labelVerified===true||Boolean(o?.sourceLabel)}
function key(m,o){return `${m.id??m.typeId}:${o.n}`}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function avg(n,d){return d>0?n/d:0}
function side(label,match){const l=norm(label),h=norm(match.home),a=norm(match.away);if(l==='1'||l==='ev sahibi'||l==='home'||(h&&(l===h||l.includes(h))))return'home';if(l==='x'||l.includes('beraber')||l==='draw')return'draw';if(l==='2'||l==='deplasman'||l==='away'||(a&&(l===a||l.includes(a))))return'away';return null}
function sideName(x,m){return x==='home'?m.home:x==='away'?m.away:'beraberlik'}
function htft(label){const z=String(label||'').toUpperCase().match(/([12X])\s*[\/-]\s*([12X])/);if(!z)return null;const cv=x=>x==='1'?'home':x==='2'?'away':'draw';return[cv(z[1]),cv(z[2])]}
function resultPart(label){const z=String(label||'').toUpperCase().match(/(^|\s|\+)(1|X|2)(?=\s|\+|\/|$)/);if(!z)return null;return z[2]==='1'?'home':z[2]==='2'?'away':'draw'}
function totalDir(label){const l=norm(label);if(l.includes('üst')||l.includes('ust')||l.includes('over'))return'over';if(l.includes('alt')||l.includes('under'))return'under';return null}
function bttsDir(label){const l=norm(label);if(l.includes('var')||l.includes('evet')||l.includes('yes'))return'yes';if(l.includes('yok')||l.includes('hayır')||l.includes('hayir')||l.includes('no'))return'no';return null}
function goalRangeMid(label){const l=norm(label),m=l.match(/(\d+)\s*[-:]\s*(\d+)/);if(m)return(+m[1]+ +m[2])/2;if(l.includes('6+'))return 6.5;return null}
function formOk(f){return !!(f?.home?.played>=4&&f?.away?.played>=4)}
function profile(match,form){if(!formOk(form))return null;const h=form.home,a=form.away,total=h.played+a.played||1;const hp=avg(h.wins,h.played)*.55+avg(a.losses,a.played)*.45,ap=avg(a.wins,a.played)*.55+avg(h.losses,h.played)*.45;const leader=hp>=ap?'home':'away';const over=(h.over25+a.over25)/total,btts=(h.btts+a.btts)/total;const expH=clamp(((h.avgGF||0)+(a.avgGA||0))/2,.2,4.2),expA=clamp(((a.avgGF||0)+(h.avgGA||0))/2,.2,4.2);return{leader,over,btts,expH,expA,totalExp:expH+expA,leaderGap:Math.abs(hp-ap),h,a}}
function candidates(match){const specialKinds=new Set(['htft','goal_range','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo','total_goals','btts','double_chance','match_result','match_winner']);const out=[];for(const m of match.markets||[]){if(!specialKinds.has(m.kind))continue;for(const o of m.outcomes||[]){const odds=Number(o.odds);if(!(odds>1)||!verified(o))continue;out.push({market:m,outcome:o,odds,key:key(m,o)})}}return out}
function novelty(kind){return({result_total_combo:9.5,result_btts_combo:9.4,total_btts_combo:9.2,first_goal_team:8.7,goal_range:8.4,htft:8.1,btts:5.6,total_goals:5.4,double_chance:3.2,match_result:2.8,match_winner:2.8})[kind]||2}
function priceScore(odds){if(odds>=2.2&&odds<=7)return 5;if(odds>7&&odds<=12)return 3.6;if(odds>12)return 1.2;if(odds>=1.7)return 3;return 1.5}
function evidenceScore(c,p,match){if(!p)return 0;const k=c.market.kind,l=c.outcome.label;let s=0;if(k==='htft'){const z=htft(l);if(!z)return-5;if(z[1]===p.leader)s+=4.5;if(z[0]===p.leader&&z[1]===p.leader)s+=1.5;if(z[0]!==z[1])s-=1.2;return s}
 if(k==='first_goal_team'){const x=side(l,match);if(x===p.leader)s+=5;if(x==='home'&&p.expH>p.expA)s+=2;if(x==='away'&&p.expA>p.expH)s+=2;return s}
 if(k==='goal_range'){const mid=goalRangeMid(l);if(mid===null)return 0;const d=Math.abs(mid-p.totalExp);return clamp(5-d*2.1,-3,5)}
 if(k==='result_total_combo'){const r=resultPart(l),d=totalDir(l);if(r===p.leader)s+=4;else if(r&&r!==p.leader)s-=4;if(d==='over')s+=(p.over-.5)*9;if(d==='under')s+=(0.5-p.over)*9;return s}
 if(k==='result_btts_combo'){const r=resultPart(l),b=bttsDir(l);if(r===p.leader)s+=4;else if(r&&r!==p.leader)s-=4;if(b==='yes')s+=(p.btts-.5)*9;if(b==='no')s+=(0.5-p.btts)*9;return s}
 if(k==='total_btts_combo'){const d=totalDir(l),b=bttsDir(l);if(d==='over')s+=(p.over-.5)*10;if(d==='under')s+=(0.5-p.over)*10;if(b==='yes')s+=(p.btts-.5)*10;if(b==='no')s+=(0.5-p.btts)*10;return s}
 if(k==='total_goals'){const d=totalDir(l);return d==='over'?(p.over-.5)*8:d==='under'?(0.5-p.over)*8:0}
 if(k==='btts'){const b=bttsDir(l);return b==='yes'?(p.btts-.5)*8:b==='no'?(0.5-p.btts)*8:0}
 const x=side(l,match);return x===p.leader?2:x?-2:0}
function specialReason(c,p,match){const k=c.market.kind,l=c.outcome.label;if(!p)return `NEÇ Özel fikri: ${c.market.name} · ${l} (${c.odds.toFixed(2)}). Son form eşleşmediği için bunu kanıtlanmış form seçimi gibi göstermiyorum; diğer dört karttan farklı bir gerçek Nesine senaryosu olduğu ve fiyatı ilginç bir risk/ödül sunduğu için ayırıyorum.`;
 const leader=sideName(p.leader,match),trend=`${match.home} son ${p.h.played} maçta ${p.h.wins}G-${p.h.draws}B-${p.h.losses}M, ${match.away} ${p.a.wins}G-${p.a.draws}B-${p.a.losses}M. Birleşik 2.5 Üst oranı %${(p.over*100).toFixed(0)}, KG Var %${(p.btts*100).toFixed(0)}; basit gol beklentisi ${p.expH.toFixed(2)}-${p.expA.toFixed(2)}.`;
 if(k==='result_total_combo')return `NEÇ Özel fikri: ${l} tek bir tahmini değil iki şartı birlikte istiyor. ${trend} Sonuç tarafında ${leader} önde; gol eğilimi de seçimin Alt/Üst ayağıyla aynı yöne baktığı için bu kombinasyonu diğer dört karttan daha ilginç buluyorum. Oran ${c.odds.toFixed(2)} olduğu için ana seçim değil, özel değer fikri.`;
 if(k==='result_btts_combo')return `NEÇ Özel fikri: ${l} için hem maç sonucu hem KG şartı gerekiyor. ${trend} Sonuç yönü ${leader}; KG eğilimi de bu marketin ikinci ayağını destekliyorsa iki bağımsız fikri tek yüksek fiyatlı senaryoda birleştiriyoruz. Bu yüzden sırf oran yüksek diye değil, iki veri aynı hikâyeye bağlandığı için seçtim.`;
 if(k==='total_btts_combo')return `NEÇ Özel fikri: ${l} gol temposu ve karşılıklı gol şartını aynı anda fiyatlıyor. ${trend} Bu iki eğilim aynı tarafa baktığında normal Üst/KG kartının daha seçici ve daha yüksek oranlı versiyonu oluşuyor; NEÇ Özel için aradığım fark tam olarak bu.`;
 if(k==='first_goal_team')return `NEÇ Özel fikri: ${l} maç sonucundan önce ilk darbeyi kimin vuracağını soruyor. ${trend} Hücum beklentisi ${p.expH>p.expA?match.home:match.away} tarafında daha yüksek; bu yüzden ilk gol marketinde bu gerçek oranı ayrı bir fikir olarak değerlendiriyorum.`;
 if(k==='goal_range')return `NEÇ Özel fikri: ${l} dar bir skor bandı istiyor. ${trend} Toplam gol beklentisi ${p.totalExp.toFixed(2)} ve bu aralığın merkezine yakın; bu nedenle klasik Üst/Alt yerine daha cesur ama matematiksel olarak açıklanabilir bir fiyat seçiyorum.`;
 if(k==='htft'){const z=htft(l);return `NEÇ Özel fikri: ${l}, ilk yarı ${z?sideName(z[0],match):'farklı yön'} / maç sonu ${z?sideName(z[1],match):leader} demek. ${trend} Maç sonu ayağı ana güç yönüyle uyumlu; ilk yarı ayağı ise ekstra risk ekliyor. Bu yüzden bunu güvenli tahmin değil, kontrollü ters senaryo olarak görüyorum.`}
 return `NEÇ Özel fikri: ${c.market.name} · ${l}. ${trend} Bu seçim diğer dört karttan farklı bir market açısı sunuyor ve form eğilimiyle çelişmediği için özel karta taşındı.`}
function upgrade(result,match,form){if(!result||!Array.isArray(result.picks)||Number(match?.sportType)!==1)return result;const used=new Set(result.picks.filter(p=>p.label!=='NEÇ Özel').map(p=>`${p.market}|${p.selection}`)),p=profile(match,form);let pool=candidates(match).filter(c=>!used.has(`${c.market.name}|${c.outcome.label}`));if(!pool.length)return result;pool=pool.map(c=>{const evidence=evidenceScore(c,p,match),distinct=novelty(c.market.kind),price=priceScore(c.odds),extremePenalty=c.odds>15?2.2:0;return{c,score:evidence*2.3+distinct+price-extremePenalty,evidence,distinct,price}}).sort((a,b)=>b.score-a.score);const best=pool[0];if(!best)return result;let sp=result.picks.find(x=>x.label==='NEÇ Özel');const confidence=Math.round(clamp((p?46:30)+best.evidence*2+(best.c.odds<=8?4:0),24,72));const replacement={label:'NEÇ Özel',tag:'⭐ NEÇ ÖZEL',available:true,market:best.c.market.name,selection:best.c.outcome.label,odds:best.c.odds,av:sp?.av??0,confidencePct:confidence,recommended:p?best.evidence>1.5:false,model:sp?.model??null,fair:sp?.fair??null,reason:specialReason(best.c,p,match),ideaScore:+best.score.toFixed(1),ideaEvidence:+best.evidence.toFixed(1)};const idx=result.picks.findIndex(x=>x.label==='NEÇ Özel');if(idx>=0)result.picks[idx]=replacement;else if(result.picks.length>=5)result.picks[4]=replacement;else result.picks.push(replacement);result.picks=result.picks.slice(0,5);result.scenario=result.scenario||{};result.scenario.specialComment=replacement.reason;result.scenario.specialOdds=replacement.odds;result.scenario.specialMarket=replacement.market;result.scenario.specialSelection=replacement.selection;result.insights=Array.isArray(result.insights)?result.insights:[];result.insights.push({title:'⭐ NEÇ Özel Nasıl Seçildi?',text:`Özel kart; veri desteği + diğer kartlardan farklılık + oran dengesiyle puanlandı. Fikir skoru ${replacement.ideaScore}; veri desteği ${replacement.ideaEvidence}. Sırf en yüksek oran olduğu için seçilmez.`});return result}
function analyzeMatch(match,form){return upgrade(base.analyzeMatch(match,form),match,form)}
module.exports={analyzeMatch};
