function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim()}
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function implied(o){return o>1?100/o:0}
function avg(n,d){return d>0?n/d:0}
function technical(s){return /^(market|bahis|seçenek|secenek|option|outcome|selection)\s*[#:_-]?\s*\d+\b/i.test(String(s||'').trim())}
const RESULT_KINDS=new Set(['match_result','match_winner']);
const FOOTBALL_SPECIAL=new Set(['double_chance','total_goals','btts','htft','first_half_total','goal_range','odd_even','handicap_result','handicap','asian_handicap','corners_total','corner_handicap','most_corners','cards_total','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo','player_goal','player_first_goal','player_assist','player_card','player_sot','player_shot','player_fouled','player_foul','player_offside','player_goal_assist','goalkeeper_saves','team_sot_total','team_shots_total','other']);
const TENNIS_OK=new Set(['match_winner','set1_winner','set2_winner','set_score','total_games','home_games_total','away_games_total','game_handicap','set_handicap','winner_total_combo','set_match','tennis_special','other']);

function kindOf(c){return c?.market?.kind||'other'}
function flat(match){const out=[];for(const market of match?.markets||[]){if(!market||market.known===false||technical(market.name))continue;for(const outcome of market.outcomes||[]){const odds=Number(outcome?.odds);if(!(odds>1)||technical(outcome?.label))continue;out.push({market,outcome,odds})}}return out}
function fair(c){const valid=(c?.market?.outcomes||[]).map(o=>Number(o.odds)).filter(o=>o>1),sum=valid.reduce((s,o)=>s+1/o,0);return sum>0?((1/c.odds)/sum)*100:implied(c.odds)}
function sideOf(c,match){const l=norm(c?.outcome?.label),h=norm(match?.home),a=norm(match?.away);if(l==='1'||(h&&(l===h||l.includes(h))))return'home';if(l==='x'||l==='beraberlik'||l==='draw'||l==='eşit')return'draw';if(l==='2'||(a&&(l===a||l.includes(a))))return'away';return null}
function totalDir(c){const l=norm(c?.outcome?.label);if(l.includes('üst')||l.includes('ust')||l.includes('over'))return'over';if(l.includes('alt')||l.includes('under'))return'under';return null}
function bttsDir(c){const l=norm(c?.outcome?.label);if(l==='var'||l.includes('evet')||l.includes('yes'))return'yes';if(l==='yok'||l.includes('hayır')||l.includes('hayir')||l.includes('no'))return'no';return null}
function htftCombo(c){const m=String(c?.outcome?.label||'').toUpperCase().match(/([12X])\s*[\/-]\s*([12X])/);return m?`${m[1]}/${m[2]}`:null}
function finalSide(combo){const f=String(combo||'').split('/')[1];return f==='1'?'home':f==='2'?'away':f==='X'?'draw':null}
function dcSides(label){const l=norm(label).replace(/\s/g,'');if(l==='1x')return new Set(['home','draw']);if(l==='x2')return new Set(['draw','away']);if(l==='12')return new Set(['home','away']);return null}
function formOk(form){return !!(form?.home?.played>=4&&form?.away?.played>=4)}
function normalize3(o){const s=(o.home||0)+(o.draw||0)+(o.away||0);return s>0?{home:o.home/s*100,draw:o.draw/s*100,away:o.away/s*100}:{home:33.3,draw:33.4,away:33.3}}
function extractResultFromLabel(label){const l=String(label||'').toUpperCase().trim();const m=l.match(/(^|\s)(1|X|2)(?=\s|\/|\+|$)/);return m?m[2]==='1'?'home':m[2]==='2'?'away':'draw':null}
function comboCompatible(c,s){const k=kindOf(c),label=c.outcome.label;if(k==='result_total_combo'){const rs=extractResultFromLabel(label),td=totalDir(c);return(!rs||rs===s.primary)&&(!td||!s.goalLean||td===s.goalLean)}if(k==='result_btts_combo'){const rs=extractResultFromLabel(label),bd=bttsDir(c);return(!rs||rs===s.primary)&&(!bd||!s.bttsLean||bd===s.bttsLean)}if(k==='total_btts_combo'){const td=totalDir(c),bd=bttsDir(c);return(!td||!s.goalLean||td===s.goalLean)&&(!bd||!s.bttsLean||bd===s.bttsLean)}return true}
function resultProbabilities(cands,match){const r={home:0,draw:0,away:0};for(const c of cands){if(!RESULT_KINDS.has(kindOf(c)))continue;const side=sideOf(c,match);if(side)r[side]=Math.max(r[side],fair(c))}return normalize3(r)}
function empirical(form){if(!formOk(form))return null;const h=form.home,a=form.away,hr=h.roleStats?.home,ar=a.roleStats?.away;const base={home:(avg(h.wins,h.played)+avg(a.losses,a.played))/2,draw:(avg(h.draws,h.played)+avg(a.draws,a.played))/2,away:(avg(a.wins,a.played)+avg(h.losses,h.played))/2};if(hr?.played>=2&&ar?.played>=2){const role={home:(avg(hr.wins,hr.played)+avg(ar.losses,ar.played))/2,draw:(avg(hr.draws,hr.played)+avg(ar.draws,ar.played))/2,away:(avg(ar.wins,ar.played)+avg(hr.losses,hr.played))/2};return normalize3({home:base.home*.65+role.home*.35,draw:base.draw*.65+role.draw*.35,away:base.away*.65+role.away*.35})}return normalize3(base)}
function marketLean(cands,kind,dirFn){const rows=cands.filter(c=>kindOf(c)===kind&&dirFn(c));if(!rows.length)return null;return rows.map(c=>({d:dirFn(c),p:fair(c)})).sort((a,b)=>b.p-a.p)[0]?.d||null}
function formText(form,match){if(!formOk(form))return'Bağımsız takım formu yeterli eşleşmedi; yorum yalnızca gerçek legal market yönüyle sınırlandırıldı.';const h=form.home,a=form.away,hr=h.roleStats?.home,ar=a.roleStats?.away;let t=`${match.home} son ${h.played} maçta ${h.wins}G ${h.draws}B ${h.losses}M; maç başı ${h.avgGF.toFixed(2)} gol atıp ${h.avgGA.toFixed(2)} gol yedi. ${match.away} son ${a.played} maçta ${a.wins}G ${a.draws}B ${a.losses}M; maç başı ${a.avgGF.toFixed(2)} gol atıp ${a.avgGA.toFixed(2)} gol yedi.`;if(hr?.played>=2&&ar?.played>=2)t+=` Ev/deplasman rolünde ${match.home} evinde ${hr.wins}G/${hr.played}, ${match.away} deplasmanda ${ar.wins}G/${ar.played}.`;t+=` Son örneklerde 2.5 Üst toplam ${h.over25+a.over25}/${h.played+a.played}, KG Var ${h.btts+a.btts}/${h.played+a.played}.`;return t}
function scenario(match,cands,form){if(Number(match.sportType)===5){const w=cands.filter(c=>kindOf(c)==='match_winner').sort((a,b)=>fair(b)-fair(a)),lead=w[0]||cands[0]||null,primary=sideOf(lead,match)||'home';return{primary,goalLean:null,bttsLean:null,probabilities:null,confidence:24,title:`${primary==='home'?match.home:match.away} ana yön`,summary:'Teniste bağımsız oyuncu-form modeli sınırlı; zıt maç kazananı üretmeden legal marketler kullanılır.',formText:'Tenis özel istatistik kaynağı henüz sınırlı.'}}
 const mp=resultProbabilities(cands,match),ep=empirical(form),p=ep?normalize3({home:mp.home*.48+ep.home*.52,draw:mp.draw*.48+ep.draw*.52,away:mp.away*.48+ep.away*.52}):mp,primary=Object.entries(p).sort((a,b)=>b[1]-a[1])[0][0];let goalLean=null,bttsLean=null;if(formOk(form)){const over=(avg(form.home.over25,form.home.played)+avg(form.away.over25,form.away.played))/2,kg=(avg(form.home.btts,form.home.played)+avg(form.away.btts,form.away.played))/2;if(over>=.55)goalLean='over';else if(over<=.45)goalLean='under';if(kg>=.55)bttsLean='yes';else if(kg<=.45)bttsLean='no'}if(!goalLean)goalLean=marketLean(cands,'total_goals',totalDir);if(!bttsLean)bttsLean=marketLean(cands,'btts',bttsDir);const vals=Object.values(p).sort((a,b)=>b-a),lead=vals[0]-vals[1],confidence=clamp(Math.round((formOk(form)?48:24)+lead*.75),20,84),sideName=primary==='home'?match.home:primary==='away'?match.away:'beraberlik';let summary=`NEÇ ana yön: ${sideName}. Sonuç/çifte şans/İY-MS kartları bu yönün tersine çıkamaz.`;if(goalLean)summary+=` Gol kilidi ${goalLean==='over'?'Üst':'Alt'}.`;if(bttsLean)summary+=` KG kilidi ${bttsLean==='yes'?'Var':'Yok'}.`;return{primary,goalLean,bttsLean,probabilities:p,confidence,title:primary==='draw'?'Beraberlik / dengeli maç ekseni':`${sideName} ana yön`,summary,formText:formText(form,match)}}
function compatible(c,s,match){const k=kindOf(c);if(Number(match.sportType)===5){if(k==='match_winner')return sideOf(c,match)===s.primary;return TENNIS_OK.has(k)}if(RESULT_KINDS.has(k))return sideOf(c,match)===s.primary;if(k==='double_chance'){const sides=dcSides(c.outcome.label);if(!sides)return false;if(s.primary==='home')return sides.has('home')&&!sides.has('away');if(s.primary==='away')return sides.has('away')&&!sides.has('home');return sides.has('draw')}if(k==='htft')return finalSide(htftCombo(c))===s.primary;if(k==='total_goals'&&s.goalLean)return totalDir(c)===s.goalLean;if(k==='btts'&&s.bttsLean)return bttsDir(c)===s.bttsLean;if(['result_total_combo','result_btts_combo','total_btts_combo'].includes(k))return comboCompatible(c,s);return FOOTBALL_SPECIAL.has(k)}
function model(c,s,form,match){const f=fair(c),k=kindOf(c);let m=f,source='market';if(Number(match.sportType)===1){if(RESULT_KINDS.has(k)&&s.probabilities){const side=sideOf(c,match);if(side){m=s.probabilities[side];source='form+market'}}else if(k==='double_chance'&&s.probabilities){const sides=dcSides(c.outcome.label);if(sides){m=[...sides].reduce((x,y)=>x+(s.probabilities[y]||0),0);source='form+market'}}else if(k==='total_goals'&&formOk(form)){const d=totalDir(c),over=(avg(form.home.over25,form.home.played)+avg(form.away.over25,form.away.played))/2*100;if(d){m=d==='over'?over:100-over;source='form'}}else if(k==='btts'&&formOk(form)){const d=bttsDir(c),yes=(avg(form.home.btts,form.home.played)+avg(form.away.btts,form.away.played))/2*100;if(d){m=d==='yes'?yes:100-yes;source='form'}}else if(k==='htft'&&formOk(form)){const combo=htftCombo(c),hr=form.home?.htftByRole?.home,ar=form.away?.htftByRole?.away,n=Number(hr?.played||0)+Number(ar?.played||0),hits=Number(hr?.counts?.[combo]||0)+Number(ar?.counts?.[combo]||0);if(combo&&n>=4){m=f*.72+(hits/n*100)*.28;source='htft-history'}}}
 m=clamp(m,.5,99.5);const av=m-f,confidence=source==='market'?18:source==='htft-history'?Math.min(58,30+(Number(form?.home?.played||0)+Number(form?.away?.played||0))*1.4):source==='form'?Math.min(76,s.confidence+4):s.confidence;return{fair:f,model:m,av,confidence:clamp(Math.round(confidence),12,84),source}}
function specialText(c,s,form,match){const k=kindOf(c),label=c.outcome.label;if(['player_first_goal','player_goal','player_goal_assist','player_sot','player_shot','player_assist','player_card'].includes(k)){const type=k==='player_first_goal'?'ilk gol':k==='player_goal'?'gol':k==='player_goal_assist'?'gol/asist':k==='player_sot'?'kaleyi bulan şut':k==='player_shot'?'şut':k==='player_assist'?'asist':'kart';return `${label} için ${type} marketi Nesine bülteninde gerçekten açık. Ana maç hikâyesiyle doğrudan çelişmediği için sürpriz havuzuna alındı. Oyuncu bazlı xG/şut ortalaması bağımsız olarak doğrulanmadı; bu yüzden güven düşük tutuluyor.`}
 if(['corners_total','corner_handicap','most_corners'].includes(k))return `${c.market.name} · ${label}: ana sonuç yönü baskı senaryosuyla uyumlu olabilir; fakat korner ortalaması ayrı veri kaynağından doğrulanmadığı için yorum legal oran + takım formu ile sınırlı.`;
 if(['team_sot_total','team_shots_total'].includes(k))return `${c.market.name} · ${label}: bu çizgi resmi bültende açık. Takımın son gol üretimi baskı ihtimalini destekleyebilir; kesin şut ortalaması bağımsız kaynaktan gelmediği için uydurulmadı.`;
 if(k==='first_goal_team')return `${c.market.name} · ${label}: ilk gol marketi maç sonucuyla birebir aynı şey değildir; bu nedenle ana yönle zorunlu çelişki sayılmaz.`;
 return `${c.market.name} · ${label} gerçek bültende açık ve ana maç senaryosuyla mantıksal olarak çelişmiyor.`}
function reason(c,s,form,match,role){const k=kindOf(c),m=model(c,s,form,match),parts=[];parts.push(role==='main'?`Ana sonuç yönü: ${s.title}.`:role==='safe'?'Ana senaryonun daha temkinli seçimi.':role==='surprise'?'Gerçek bültendeki daha yüksek oranlı sürpriz seçimi.':role==='big'?'Gerçek bültendeki en agresif ama çelişki filtresinden geçen seçeneklerden biri.':'NEÇ Özel, tüm açık legal marketler arasından senaryo uyumu ve veri gücüne göre seçildi.');if(RESULT_KINDS.has(k)||k==='double_chance')parts.push(formText(form,match));else if(k==='total_goals'&&formOk(form))parts.push(`Son ${form.home.played+form.away.played} takım-maç örneğinde 2.5 Üst ${form.home.over25+form.away.over25} kez görüldü.`);else if(k==='btts'&&formOk(form))parts.push(`KG Var son örneklerde ${form.home.btts+form.away.btts}/${form.home.played+form.away.played}.`);else if(k==='htft'){const combo=htftCombo(c),hr=form?.home?.htftByRole?.home,ar=form?.away?.htftByRole?.away,n=Number(hr?.played||0)+Number(ar?.played||0),hits=Number(hr?.counts?.[combo]||0)+Number(ar?.counts?.[combo]||0);if(n>=4)parts.push(hits?`Rol uyumlu ${n} örnekte ${combo} ${hits} kez görüldü.`:`Rol uyumlu ${n} örnekte ${combo} hiç görülmedi; “artık olur” mantığı kullanılmaz.`)}else parts.push(specialText(c,s,form,match));parts.push(m.source==='market'?'Bu özel market için bağımsız olasılık modeli yok; NEÇ AV 0.0 civarında tutulur ve veri uydurulmaz.':m.av>0.5?`NEÇ AV +${m.av.toFixed(1)} puan.`:m.av<-0.5?`NEÇ AV ${m.av.toFixed(1)} puan; fiyat güçlü değer göstermiyor.`:`NEÇ AV ${m.av.toFixed(1)} puan; model ile fiyat yakın.`);return parts.join(' ')}
function id(c){return `${c?.market?.id??c?.market?.typeId}:${c?.outcome?.n}:${c?.odds}`}
function marketId(c){return String(c?.market?.id??c?.market?.typeId??c?.market?.name)}
function roleScore(c,s,form,match,role){if(!compatible(c,s,match))return-9999;const m=model(c,s,form,match),k=kindOf(c);let z=m.av*5+m.confidence*.18;if(role==='main')z+=RESULT_KINDS.has(k)?100:-80;if(role==='safe'){if(k==='double_chance')z+=70;if(c.odds<=2.4)z+=22;if(['total_goals','btts'].includes(k))z+=12}if(role==='surprise'){if(c.odds>=2&&c.odds<=8)z+=50-Math.abs(c.odds-3.5)*3;else z-=20;if(['player_goal','player_sot','player_shot','first_goal_team','htft','result_total_combo','result_btts_combo','total_goals','btts'].includes(k))z+=16}if(role==='big'){z+=Math.min(50,Math.log2(Math.max(c.odds,1.01))*11);if(c.odds>=4)z+=35;if(['player_first_goal','htft','player_goal','result_total_combo','result_btts_combo'].includes(k))z+=22}if(role==='special'){if(m.source!=='market')z+=35;if(m.av>0)z+=25;if(c.odds>=1.5&&c.odds<=12)z+=10;if(['player_first_goal','player_goal','player_sot','team_sot_total','corners_total','htft','total_goals','btts'].includes(k))z+=12}return z}
function choose(cands,s,form,match,role,used,usedMarkets){let rows=cands.filter(c=>!used.has(id(c))&&compatible(c,s,match));const diverse=rows.filter(c=>!usedMarkets.has(marketId(c)));if(diverse.length)rows=diverse;if(role==='main')rows=rows.filter(c=>RESULT_KINDS.has(kindOf(c)));if(role==='safe'){const dc=rows.filter(c=>kindOf(c)==='double_chance');if(dc.length)rows=dc;else{const low=rows.filter(c=>c.odds<=2.8);if(low.length)rows=low}}if(role==='surprise'){const band=rows.filter(c=>c.odds>=2&&c.odds<=8);if(band.length)rows=band}if(role==='big'){const band=rows.filter(c=>c.odds>=4&&c.odds<=50);if(band.length)rows=band;else rows=rows.sort((a,b)=>b.odds-a.odds).slice(0,12)}if(!rows.length)return null;return rows.map(c=>({c,z:roleScore(c,s,form,match,role)})).sort((a,b)=>b.z-a.z)[0].c}
function makePick(label,c,s,form,match,role,tag){if(!c)return{label,available:false,tag,av:0,confidencePct:0,reason:'Bu maçta çelişki yaratmadan kullanılabilecek gerçek bir ek market bulunamadı.'};const m=model(c,s,form,match);return{label,available:true,tag,market:c.market.name,selection:c.outcome.label,odds:c.odds,av:+m.av.toFixed(1),confidencePct:m.confidence,model:+m.model.toFixed(1),fair:+m.fair.toFixed(1),recommended:m.source!=='market'&&m.av>0.5&&m.confidence>=30,kind:kindOf(c),reason:reason(c,s,form,match,role)}}
function analyzeMatch(match,form){const cands=flat(match),s=scenario(match,cands,form),used=new Set(),usedMarkets=new Set();const take=role=>{const c=choose(cands,s,form,match,role,used,usedMarkets);if(c){used.add(id(c));usedMarkets.add(marketId(c))}return c};const main=take('main'),safe=take('safe'),surprise=take('surprise'),big=take('big');let special=choose(cands,s,form,match,'special',used,usedMarkets);if(!special)special=cands.find(c=>compatible(c,s,match)&&!used.has(id(c)))||main||safe||surprise||big||null;const picks=[makePick('Ana Senaryo',main,s,form,match,'main','ANA YÖN'),makePick('Temkinli Seçim',safe,s,form,match,'safe','TEMKİNLİ'),makePick('Sürpriz Seçim',surprise,s,form,match,'surprise','🎯 SÜRPRİZ'),makePick('Çok Sürpriz',big,s,form,match,'big','🔥 ÇOK SÜRPRİZ'),makePick('NEÇ Özel',special,s,form,match,'special','⭐ NEÇ ÖZEL')];const avail=picks.filter(p=>p.available);return{radar:clamp(Math.round(22+s.confidence*.58+Math.max(0,...avail.map(p=>p.av))*3),1,99),form:form||null,scenario:{title:s.title,summary:s.summary,formText:s.formText,confidence:s.confidence,locks:{result:s.primary,goals:s.goalLean,btts:s.bttsLean},specialComment:avail.length?`${s.summary} ${s.formText} NEÇ Özel: ${picks[4].available?`${picks[4].market} — ${picks[4].selection} (${Number(picks[4].odds).toFixed(2)}). ${picks[4].reason}`:'uygun market bulunamadı.'}`:s.summary,specialOdds:picks[4].available?picks[4].odds:null,specialMarket:picks[4].available?picks[4].market:null,specialSelection:picks[4].available?picks[4].selection:null,av:picks[4].available?picks[4].av:0},picks,insights:[{title:'📚 Tam Market Havuzu',text:`Bu maçta ${match.marketCount||match.markets?.length||0} legal market ve ${match.outcomeCount||cands.length} fiyat seçeneği bültenden alındı; analiz yalnızca beş kart değil bu tam havuzu tarar.`},{title:'🧭 Çelişki Kilidi',text:`Sonuç yönü ${s.primary==='home'?match.home:s.primary==='away'?match.away:'Beraberlik'}; gol ${s.goalLean==='over'?'Üst':s.goalLean==='under'?'Alt':'nötr'}; KG ${s.bttsLean==='yes'?'Var':s.bttsLean==='no'?'Yok':'nötr'}.`},{title:'📋 Takım Formu',text:s.formText}],analyzedAt:new Date().toISOString(),disclaimer:'Gösterilen oranlar bültenden gelen seçim-oran eşleşmesiyle değiştirilmeden kullanılır. Oyuncu/şut/korner gibi bağımsız istatistiği bağlı olmayan özel marketlerde güven düşük tutulur; istatistik uydurulmaz.'}}
module.exports={analyzeMatch};