const base=require('./analyzer-v2');
function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim()}
function verified(o){return o?.labelVerified===true||Boolean(o?.sourceLabel)}
function fair(c){const xs=(c.market.outcomes||[]).map(o=>Number(o.odds)).filter(x=>x>1);const sum=xs.reduce((s,x)=>s+1/x,0);return sum?((1/c.odds)/sum)*100:100/c.odds}
function key(c){return `${c.market.id??c.market.typeId}:${c.outcome.n}`}
function rows(match){const a=[];for(const market of match.markets||[])for(const outcome of market.outcomes||[]){const odds=Number(outcome.odds);if(odds>1&&verified(outcome))a.push({market,outcome,odds})}return a}
function side(c,m){const l=norm(c.outcome.label),h=norm(m.home),a=norm(m.away);if(l==='1'||l==='ev sahibi'||l==='home'||(h&&(l===h||l.includes(h))))return'home';if(l==='x'||l.includes('beraber')||l==='draw')return'draw';if(l==='2'||l==='deplasman'||l==='away'||(a&&(l===a||l.includes(a))))return'away';return null}
function name(x,m){return x==='home'?m.home:x==='away'?m.away:'beraberlik'}
function dc(label){const l=norm(label).replace(/\s/g,'');if(l.startsWith('1x'))return['home','draw'];if(l.startsWith('x2'))return['draw','away'];if(l.startsWith('12'))return['home','away'];return[]}
function htft(label){const z=String(label||'').toUpperCase().match(/([12X])\s*[\/-]\s*([12X])/);if(!z)return null;const cv=x=>x==='1'?'home':x==='2'?'away':'draw';return[cv(z[1]),cv(z[2])]}
function resultPart(label){const z=String(label||'').toUpperCase().match(/(^|\s|\+)(1|X|2)(?=\s|\+|\/|$)/);if(!z)return null;return z[2]==='1'?'home':z[2]==='2'?'away':'draw'}
function resultEstimate(match,all){const r=all.filter(c=>['match_result','match_winner'].includes(c.market.kind));const p={home:null,draw:null,away:null},shown=[];for(const c of r){const x=side(c,match);if(!x)continue;const q=100/c.odds;if(p[x]===null||q>p[x])p[x]=q;shown.push(`${c.outcome.label} ${c.odds.toFixed(2)}`)}const missing=Object.keys(p).filter(x=>p[x]===null);if(missing.length===1){const used=Object.values(p).filter(Number.isFinite).reduce((a,b)=>a+b,0);p[missing[0]]=Math.max(1,100-used)}else for(const x of missing)p[x]=0;const sum=Object.values(p).reduce((a,b)=>a+b,0)||1;for(const x of Object.keys(p))p[x]=p[x]/sum*100;const primary=Object.entries(p).sort((a,b)=>b[1]-a[1])[0][0];return{p,primary,shown,missing}}
function compatible(c,primary,match){const k=c.market.kind;if(['match_result','match_winner'].includes(k))return side(c,match)===primary;if(k==='double_chance')return dc(c.outcome.label).includes(primary);if(k==='htft'){const z=htft(c.outcome.label);return !!z&&z[1]===primary}if(['result_total_combo','result_btts_combo'].includes(k)){const r=resultPart(c.outcome.label);return !r||r===primary}return true}
function priceList(c){return(c.market.outcomes||[]).filter(o=>Number(o.odds)>1&&verified(o)).map(o=>`${o.label} ${Number(o.odds).toFixed(2)}`).join(' · ')}
function reason(c,e,match,label){const direction=name(e.primary,match),missing=e.missing.length?` 1X2 akışında ${e.missing.map(x=>name(x,match)).join(', ')} fiyatı eksik; eksik olasılığı kalan payla hesaba kattım.`:'';const k=c.market.kind,tail=label==='Çok Sürpriz'?' Bu yüzden bunu yüksek oranlı uç senaryo olarak görüyorum.':label==='Sürpriz Seçim'?' Ana tahmin değil; fiyatı nedeniyle sürpriz kartta tutuyorum.':label==='Temkinli Seçim'?' Bu kartta amaç ana yönü mümkün olduğunca korumak.':label==='NEÇ Özel'?' NEÇ Özel’de ana kartı tekrar etmek yerine farklı bir gerçek market arıyorum.':'';if(['match_result','match_winner'].includes(k))return `NEÇ yorumu: Görünen 1X2 fiyatları ${e.shown.join(' · ')}.${missing} Piyasa olasılık dağılımı ${direction} yönünü öne çıkarıyor. ${c.outcome.label} gerçek fiyatı mevcut olduğu için bu kartta kullanılabiliyor.${tail}`;if(k==='double_chance')return `NEÇ yorumu: Görünen ana fiyatlardan hesaplanan yön ${direction}. ${c.outcome.label}, ${dc(c.outcome.label).map(x=>name(x,match)).join(' / ')} sonuçlarını kapsıyor; bu nedenle ana yönü tek sonuca göre daha geniş koruyor. Market fiyatları: ${priceList(c)}.${missing}${tail}`;if(k==='htft'){const z=htft(c.outcome.label);return `NEÇ yorumu: ${c.outcome.label}, ilk yarı ${z?name(z[0],match):'seçilen sonuç'} / maç sonu ${z?name(z[1],match):'seçilen sonuç'} demek. Ana piyasa yönü ${direction}; maç sonu ayağı aynı yöne geldiği için bu dönüş senaryosunu değerlendiriyorum. İlk yarı formu doğrulanmadığından güvenli seçim değil.${tail}`};if(k==='total_goals')return `NEÇ yorumu: Son form henüz eşleşmedi; bu yüzden gol marketini form varmış gibi anlatmıyorum. ${priceList(c)} fiyat dağılımında ${c.outcome.label} gerçek seçeneği mevcut. Ana 1X2 yönü ${direction}; bu kart maç sonucundan bağımsız olarak tempo ihtimalini fiyatlıyor.${missing}${tail}`;if(k==='btts')return `NEÇ yorumu: KG marketinde görünen fiyatlar ${priceList(c)}. ${c.outcome.label} iki takımın da gol bulup bulmaması üzerine ayrı bir senaryo. Form gelmediği için bunu yalnızca piyasa okuması olarak tutuyorum; ana sonuç yönü ${direction}.${missing}${tail}`;if(k==='goal_range')return `NEÇ yorumu: ${c.outcome.label} gol aralığı ${c.odds.toFixed(2)} oranla açık. Dar aralık olduğu için normal Alt/Üst'e göre daha zor; fakat gerçek oranı daha yüksek. Form henüz yok, bu yüzden bunu sonuç tahmini değil ayrı bir skor-tempo senaryosu olarak görüyorum.${tail}`;return `NEÇ yorumu: ${c.market.name} · ${c.outcome.label} ${c.odds.toFixed(2)}. Ana piyasa yönü ${direction}; bu gerçek market ana sonuçla doğrudan çelişmediği için alternatif risk kartına girdi.${missing}${tail}`}
function build(match){const allowed=new Set(['match_result','match_winner','double_chance','total_goals','btts','htft','goal_range','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo']),all=rows(match).filter(c=>allowed.has(c.market.kind));if(!all.length)return null;const e=resultEstimate(match,all),used=new Set(),defs=[['Ana Senaryo','ANA YÖN','main'],['Temkinli Seçim','TEMKİNLİ','safe'],['Sürpriz Seçim','🎯 SÜRPRİZ','surprise'],['Çok Sürpriz','🔥 ÇOK SÜRPRİZ','big'],['NEÇ Özel','⭐ NEÇ ÖZEL','special']],picks=[];
 function pool(){return all.filter(c=>!used.has(key(c))&&compatible(c,e.primary,match))}
 function choose(role){let p=pool();if(role==='main'){let q=p.filter(c=>['match_result','match_winner'].includes(c.market.kind)&&side(c,match)===e.primary);if(!q.length)q=p.filter(c=>c.market.kind==='double_chance'&&dc(c.outcome.label).includes(e.primary));if(!q.length)q=p.filter(c=>c.market.kind==='htft'&&htft(c.outcome.label)?.[1]===e.primary);if(q.length)p=q}else if(role==='safe'){const q=p.filter(c=>c.market.kind==='double_chance'||c.odds<=1.9);if(q.length)p=q}else if(role==='surprise'){const q=p.filter(c=>c.odds>=2&&c.odds<=5);if(q.length)p=q}else if(role==='big'){const q=p.filter(c=>c.odds>=4);if(q.length)p=q}else if(role==='special'){const q=p.filter(c=>['htft','goal_range','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo'].includes(c.market.kind));if(q.length)p=q}if(!p.length)p=all.filter(c=>!used.has(key(c)));p.sort((a,b)=>role==='big'?b.odds-a.odds:fair(b)-fair(a));return p[0]||null}
 for(const [label,tag,role] of defs){const c=choose(role);if(!c)break;used.add(key(c));const fp=fair(c);picks.push({label,tag,available:true,market:c.market.name,selection:c.outcome.label,odds:c.odds,av:0,confidencePct:role==='main'?42:role==='safe'?40:role==='surprise'?34:role==='big'?28:32,recommended:false,model:+fp.toFixed(1),fair:+fp.toFixed(1),reason:reason(c,e,match,label)})}
 const sp=picks.find(p=>p.label==='NEÇ Özel')||picks[picks.length-1],missing=e.missing.length?` Eksik 1X2 ayağı: ${e.missing.map(x=>name(x,match)).join(', ')}; bu seçim için oran uydurulmadı.`:'';return{radar:38,form:null,formStatus:'market-only-football',scenario:{title:`${name(e.primary,match)} yönlü düşük güvenli piyasa hikâyesi`,summary:`Görünen 1X2 fiyatları: ${e.shown.join(' · ')||'tam fiyat yok'}. Hesaplanan piyasa yönü ${name(e.primary,match)}.${missing} Form eşleşene kadar beş kart yalnızca adı doğrulanmış gerçek oranlardan oluşturulur.`,formText:'Son maç formu bu istekte eşleşmedi; fiyatı olmayan seçim gösterilmez ve AV 0.0 nötr tutulur.',confidence:38,specialComment:sp?`NEÇ Özel: ${sp.market} · ${sp.selection}. Bu seçim ana kartın kopyası değil.`:'',specialOdds:sp?.odds??null,specialMarket:sp?.market??null,specialSelection:sp?.selection??null},picks,insights:[{title:'📡 Görünen 1X2',text:e.shown.join(' · ')||'Tam 1X2 fiyatı yok'},{title:'🧮 Eksik Fiyat Mantığı',text:missing||'1X2 tam.'},{title:'🧠 NEÇ AV',text:'Form olmadığı için AV 0.0 nötr; değer avantajı iddia edilmiyor.'}],research:{engine:'Nesine market model',sources:[]},analyzedAt:new Date().toISOString(),disclaimer:'Form verisi olmayan piyasa okuması düşük güvenlidir; sonuç garantisi değildir.'}}
function analyzeMatch(match,form){if(Number(match?.sportType)===1&&!form)return build(match)||base.analyzeMatch(match,form);return base.analyzeMatch(match,form)}
module.exports={analyzeMatch};
