function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim()}
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function implied(o){return o>1?100/o:0}
function avg(n,d){return d>0?n/d:0}
function technical(s){return /^(market|bahis|seçenek|secenek|option|outcome|selection)\s*[#:_-]?\s*\d+\b/i.test(String(s||'').trim())}
const RESULT_KINDS=new Set(['match_result','match_winner']);
const MODELED_KINDS=new Set(['match_result','match_winner','double_chance','total_goals','btts','htft','goal_range','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo']);
const VERIFIED_FALLBACK_MTIDS=new Set([1,3,5,7,8,9,11,12,13,14,15,20,29,38,43,48,49,100,101,155,161,164,185,216,272,291,299,301,338,342,343,414,416,418,424,426,438,446,450,452,459,461,583,601,602,656,801,822,823,824,866,867,884,887]);

function kindOf(c){return c?.market?.kind||'other'}
function verified(c){return c?.outcome?.labelVerified===true||Boolean(c?.outcome?.sourceLabel)||VERIFIED_FALLBACK_MTIDS.has(Number(c?.market?.typeId||0))}
function flat(match){const out=[];for(const market of match?.markets||[]){if(!market||market.known===false||technical(market.name))continue;for(const outcome of market.outcomes||[]){const odds=Number(outcome?.odds);if(!(odds>1)||technical(outcome?.label))continue;const c={market,outcome,odds};if(!verified(c))continue;if(Number(match.sportType)===1&&!MODELED_KINDS.has(kindOf(c)))continue;out.push(c)}}return out}
function fair(c){const valid=(c?.market?.outcomes||[]).filter(o=>Number(o.odds)>1).map(o=>1/Number(o.odds));const sum=valid.reduce((a,b)=>a+b,0);return sum>0?((1/c.odds)/sum)*100:implied(c.odds)}
function sideOf(c,match){const l=norm(c?.outcome?.label),h=norm(match?.home),a=norm(match?.away);if(l==='1'||l==='ev sahibi'||l==='home'||(h&&(l===h||l.includes(h))))return'home';if(l==='x'||l==='beraberlik'||l==='draw'||l==='eşit')return'draw';if(l==='2'||l==='deplasman'||l==='away'||(a&&(l===a||l.includes(a))))return'away';return null}
function dcSides(label){const l=norm(label).replace(/\s/g,'');if(l.startsWith('1x'))return new Set(['home','draw']);if(l.startsWith('x2'))return new Set(['draw','away']);if(l.startsWith('12'))return new Set(['home','away']);return null}
function totalDir(c){const l=norm(c?.outcome?.label);if(l.includes('üst')||l.includes('ust')||l.includes('over'))return'over';if(l.includes('alt')||l.includes('under'))return'under';return null}
function bttsDir(c){const l=norm(c?.outcome?.label);if(l.includes('var')||l.includes('evet')||l.includes('yes'))return'yes';if(l.includes('yok')||l.includes('hayır')||l.includes('hayir')||l.includes('no'))return'no';return null}
function parseLine(c){const spread=Number(c?.market?.spread);if(Number.isFinite(spread)&&spread>0)return spread;const m=String(c?.outcome?.label||'').replace(',','.').match(/(\d+(?:\.\d+)?)/);return m?Number(m[1]):null}
function htftCombo(c){const m=String(c?.outcome?.label||'').toUpperCase().match(/([12X])\s*[\/-]\s*([12X])/);return m?`${m[1]}/${m[2]}`:null}
function finalSide(combo){const f=String(combo||'').split('/')[1];return f==='1'?'home':f==='2'?'away':f==='X'?'draw':null}
function extractResult(label){const l=String(label||'').toUpperCase().trim();const m=l.match(/(^|\s)(1|X|2)(?=\s|\/|\+|$)/);return m?m[2]==='1'?'home':m[2]==='2'?'away':'draw':null}
function formOk(form){return !!(form?.home?.played>=4&&form?.away?.played>=4)}
function normalize3(o){const s=(o.home||0)+(o.draw||0)+(o.away||0);return s>0?{home:o.home/s*100,draw:o.draw/s*100,away:o.away/s*100}:{home:33.3,draw:33.4,away:33.3}}
function poisson(k,l){let p=Math.exp(-l);for(let i=1;i<=k;i++)p*=l/i;return p}
function totalDist(lambda,max=10){const a=[];let sum=0;for(let k=0;k<=max;k++){const p=poisson(k,lambda);a.push(p);sum+=p}if(sum<1)a[max]+=1-sum;return a}
function totalProb(lambda,line,dir){if(!(lambda>0)||!(line>0)||!dir)return null;const d=totalDist(lambda,12);const frac=Math.round((line-Math.floor(line))*100)/100;if(Math.abs(frac-.5)<.01){const cut=Math.floor(line);const under=d.slice(0,cut+1).reduce((a,b)=>a+b,0);return (dir==='under'?under:1-under)*100}if(Math.abs(frac)<.01){const n=Math.round(line),under=d.slice(0,n).reduce((a,b)=>a+b,0)-d[n],over=1-d.slice(0,n+1).reduce((a,b)=>a+b,0),den=under+over;return den>0?(dir==='under'?under:over)/den*100:null}return null}
function rangeProb(lambda,label){const l=norm(label),d=totalDist(lambda,12);if(/^0\s*[-:]\s*1/.test(l))return(d[0]+d[1])*100;if(/^2\s*[-:]\s*3/.test(l))return(d[2]+d[3])*100;if(/^4\s*[-:]\s*5/.test(l))return(d[4]+d[5])*100;if(l.includes('6+'))return d.slice(6).reduce((a,b)=>a+b,0)*100;return null}
function recentTR(s){return String(s||'').replaceAll('W','G').replaceAll('D','B').replaceAll('L','M')}
function roleStat(team,role){return team?.roleStats?.[role]?.played>=2?team.roleStats[role]:null}
function mix(a,b,w=.35){return Number.isFinite(b)?a*(1-w)+b*w:a}
function expectations(form){if(!formOk(form))return null;const h=form.home,a=form.away,hr=roleStat(h,'home'),ar=roleStat(a,'away');const hGF=mix(h.avgGF,hr?.avgGF),hGA=mix(h.avgGA,hr?.avgGA),aGF=mix(a.avgGF,ar?.avgGF),aGA=mix(a.avgGA,ar?.avgGA);const home=clamp((hGF+aGA)/2,.15,4.5),away=clamp((aGF+hGA)/2,.15,4.5);return{home,away,total:home+away}}
function marketResults(cands,match){const r={home:0,draw:0,away:0};for(const c of cands){if(!RESULT_KINDS.has(kindOf(c)))continue;const s=sideOf(c,match);if(s)r[s]=Math.max(r[s],fair(c))}return normalize3(r)}
function formResults(form){if(!formOk(form))return null;const h=form.home,a=form.away,hr=roleStat(h,'home'),ar=roleStat(a,'away');const base={home:(avg(h.wins,h.played)+avg(a.losses,a.played))/2,draw:(avg(h.draws,h.played)+avg(a.draws,a.played))/2,away:(avg(a.wins,a.played)+avg(h.losses,h.played))/2};if(hr&&ar){const rr={home:(avg(hr.wins,hr.played)+avg(ar.losses,ar.played))/2,draw:(avg(hr.draws,hr.played)+avg(ar.draws,ar.played))/2,away:(avg(ar.wins,ar.played)+avg(hr.losses,hr.played))/2};return normalize3({home:base.home*.65+rr.home*.35,draw:base.draw*.65+rr.draw*.35,away:base.away*.65+rr.away*.35})}return normalize3(base)}
function resultProbs(cands,form,match){const mp=marketResults(cands,match),fp=formResults(form);return fp?normalize3({home:mp.home*.4+fp.home*.6,draw:mp.draw*.4+fp.draw*.6,away:mp.away*.4+fp.away*.6}):mp}
function scenario(match,cands,form){const rp=resultProbs(cands,form,match),primary=Object.entries(rp).sort((a,b)=>b[1]-a[1])[0][0],ex=expectations(form);let goalLean=null,bttsLean=null;if(formOk(form)){const over=(avg(form.home.over25,form.home.played)+avg(form.away.over25,form.away.played))/2,kg=(avg(form.home.btts,form.home.played)+avg(form.away.btts,form.away.played))/2;if(over>=.55)goalLean='over';else if(over<=.45)goalLean='under';if(kg>=.55)bttsLean='yes';else if(kg<=.45)bttsLean='no';if(!goalLean&&ex)goalLean=ex.total>=2.65?'over':ex.total<=2.25?'under':null;if(!bttsLean&&ex){const p=(1-Math.exp(-ex.home))*(1-Math.exp(-ex.away));bttsLean=p>=.56?'yes':p<=.44?'no':null}}
 const vals=Object.values(rp).sort((a,b)=>b-a),lead=vals[0]-vals[1],confidence=clamp(Math.round((formOk(form)?50:20)+lead*.65),18,84),sideName=primary==='home'?match.home:primary==='away'?match.away:'beraberlik';return{primary,goalLean,bttsLean,resultProbs:rp,exp:ex,confidence,title:primary==='draw'?'Dengeli / beraberlik ekseni':`${sideName} tarafı önde`}}
function comboCompatible(c,s){const k=kindOf(c),rs=extractResult(c.outcome.label),td=totalDir(c),bd=bttsDir(c);if(k==='result_total_combo')return(!rs||rs===s.primary)&&(!td||!s.goalLean||td===s.goalLean);if(k==='result_btts_combo')return(!rs||rs===s.primary)&&(!bd||!s.bttsLean||bd===s.bttsLean);if(k==='total_btts_combo')return(!td||!s.goalLean||td===s.goalLean)&&(!bd||!s.bttsLean||bd===s.bttsLean);return true}
function rangeCompatible(c,s){const l=norm(c.outcome.label);if(s.goalLean==='over'&&(/^0\s*[-:]\s*1/.test(l)))return false;if(s.goalLean==='under'&&(l.includes('4-5')||l.includes('6+')))return false;return true}
function compatible(c,s,match){const k=kindOf(c);if(RESULT_KINDS.has(k))return sideOf(c,match)===s.primary;if(k==='double_chance'){const sides=dcSides(c.outcome.label);if(!sides)return false;if(s.primary==='home')return sides.has('home')&&!sides.has('away');if(s.primary==='away')return sides.has('away')&&!sides.has('home');return sides.has('draw')}if(k==='htft')return finalSide(htftCombo(c))===s.primary;if(k==='total_goals')return !s.goalLean||totalDir(c)===s.goalLean;if(k==='btts')return !s.bttsLean||bttsDir(c)===s.bttsLean;if(k==='goal_range')return rangeCompatible(c,s);if(k==='first_goal_team'){const side=sideOf(c,match);return side?side===s.primary:true}if(['result_total_combo','result_btts_combo','total_btts_combo'].includes(k))return comboCompatible(c,s);return false}
function blend(raw,fairP,w=.7){return clamp(raw*w+fairP*(1-w),.5,99.5)}
function model(c,s,form,match){if(!formOk(form))return null;const k=kindOf(c),f=fair(c),ex=s.exp;let raw=null,source='';if(RESULT_KINDS.has(k)){const side=sideOf(c,match);if(side){raw=s.resultProbs[side];source='sonuç formu'}}else if(k==='double_chance'){const sides=dcSides(c.outcome.label);if(sides){raw=[...sides].reduce((n,x)=>n+(s.resultProbs[x]||0),0);source='sonuç formu'}}else if(k==='total_goals'&&ex){const line=parseLine(c),dir=totalDir(c),pp=totalProb(ex.total,line,dir);if(pp!==null){if(Math.abs((line||0)-2.5)<.11){const empirical=(avg(form.home.over25,form.home.played)+avg(form.away.over25,form.away.played))/2*100;raw=dir==='over'?empirical:100-empirical;raw=raw*.45+pp*.55}else raw=pp;source='gol formu'}}else if(k==='btts'&&ex){const yes=(1-Math.exp(-ex.home))*(1-Math.exp(-ex.away))*100,emp=(avg(form.home.btts,form.home.played)+avg(form.away.btts,form.away.played))/2*100;const p=yes*.55+emp*.45;raw=bttsDir(c)==='yes'?p:100-p;source='KG formu'}else if(k==='goal_range'&&ex){raw=rangeProb(ex.total,c.outcome.label);source='gol dağılımı'}else if(k==='htft'){const combo=htftCombo(c),hr=form.home?.htftByRole?.home,ar=form.away?.htftByRole?.away,n=Number(hr?.played||0)+Number(ar?.played||0),hits=Number(hr?.counts?.[combo]||0)+Number(ar?.counts?.[combo]||0);if(combo&&n>=4){raw=hits/n*100;source='İY/MS geçmişi'}}else if(k==='first_goal_team'&&ex){const side=sideOf(c,match),noGoal=Math.exp(-ex.total)*100;if(side==='home')raw=(1-noGoal/100)*(ex.home/ex.total)*100;else if(side==='away')raw=(1-noGoal/100)*(ex.away/ex.total)*100;else if(norm(c.outcome.label).includes('gol olmaz'))raw=noGoal;source='ilk gol modeli'}else if(k==='result_total_combo'&&ex){const rs=extractResult(c.outcome.label),tp=totalProb(ex.total,parseLine(c),totalDir(c));if(rs&&tp!==null){raw=(s.resultProbs[rs]/100)*(tp/100)*100;source='sonuç+gol'}}else if(k==='result_btts_combo'&&ex){const rs=extractResult(c.outcome.label),yes=(1-Math.exp(-ex.home))*(1-Math.exp(-ex.away))*100,bd=bttsDir(c);if(rs&&bd){const bp=bd==='yes'?yes:100-yes;raw=(s.resultProbs[rs]/100)*(bp/100)*100;source='sonuç+KG'}}else if(k==='total_btts_combo'&&ex){const tp=totalProb(ex.total,parseLine(c),totalDir(c)),yes=(1-Math.exp(-ex.home))*(1-Math.exp(-ex.away))*100,bd=bttsDir(c);if(tp!==null&&bd){const bp=bd==='yes'?yes:100-yes;raw=(tp/100)*(bp/100)*100;source='gol+KG'}}if(raw===null||!Number.isFinite(raw))return null;const p=blend(raw,f,k==='htft'?.55:.7),av=p-f;const samples=form.home.played+form.away.played;let confidence=clamp(32+samples*1.6,35,76);if(k==='htft')confidence=Math.min(confidence,56);if(['result_total_combo','result_btts_combo','total_btts_combo','first_goal_team'].includes(k))confidence=Math.min(confidence,62);return{fair:f,model:p,av,confidence:Math.round(confidence),source}}
function formSummary(form,match){if(!formOk(form))return'Takım formu bu maç için yeterli doğrulanamadı.';const h=form.home,a=form.away,hr=roleStat(h,'home'),ar=roleStat(a,'away');let t=`${match.home} son ${h.played} maçta ${h.wins} galibiyet, ${h.draws} beraberlik, ${h.losses} mağlubiyet aldı; ${h.avgGF.toFixed(2)} gol atıp ${h.avgGA.toFixed(2)} gol yedi. ${match.away} ise ${a.wins}G ${a.draws}B ${a.losses}M ve ${a.avgGF.toFixed(2)}-${a.avgGA.toFixed(2)} gol ortalamasında.`;if(hr&&ar)t+=` Ev/deplasman ayrımında ${match.home} evinde ${hr.wins}G/${hr.played}, ${match.away} deplasmanda ${ar.wins}G/${ar.played}.`;return t}
function resultReason(c,s,form,match){const h=form.home,a=form.away,hr=roleStat(h,'home'),ar=roleStat(a,'away'),side=sideOf(c,match);let t=formSummary(form,match);if(side==='home'&&hr)t+=` Özellikle ev sahibinin evindeki ${hr.wins}/${hr.played} galibiyet oranı bu seçimi destekliyor.`;if(side==='away'&&ar)t+=` Deplasman ekibinin dış sahadaki ${ar.wins}/${ar.played} galibiyet sayısı bu seçimin ana dayanağı.`;if(side==='draw')t+=` İki tarafın sonuç profili birbirine yakın kaldığı için beraberlik senaryosu öne çıkıyor.`;return t}
function totalReason(c,s,form,match){const h=form.home,a=form.away,line=parseLine(c),dir=totalDir(c),ex=s.exp;const hits=h.over25+a.over25,total=h.played+a.played;return `${match.home} maçlarında ${h.avgGF.toFixed(2)} gol atıp ${h.avgGA.toFixed(2)} gol yiyor; ${match.away} tarafında bu değerler ${a.avgGF.toFixed(2)} ve ${a.avgGA.toFixed(2)}. Son ${total} takım-maç örneğinin ${hits} tanesi 2.5 Üst bitti. Bu iki profilin birleşik gol beklentisi yaklaşık ${ex.total.toFixed(2)}; bu nedenle ${dir==='over'?'Üst':'Alt'} ${line??''} tarafı daha anlamlı görünüyor.`}
function bttsReason(c,s,form,match){const h=form.home,a=form.away,yes=h.btts+a.btts,total=h.played+a.played,dir=bttsDir(c);return `İki takımın son ${total} takım-maç örneğinde KG Var ${yes} kez oluştu. ${match.home} ${h.failedToScore} maçta, ${match.away} ${a.failedToScore} maçta gol atamadı; iki ekip toplam ${h.cleanSheets+a.cleanSheets} kez gol yemeden bitirdi. Bu dağılım ${dir==='yes'?'iki takımın da gol bulması':'en az bir tarafın golde kalması'} senaryosunu destekliyor.`}
function htftReason(c,form,match){const combo=htftCombo(c),hr=form.home?.htftByRole?.home,ar=form.away?.htftByRole?.away,n=Number(hr?.played||0)+Number(ar?.played||0),hits=Number(hr?.counts?.[combo]||0)+Number(ar?.counts?.[combo]||0);return `${match.home}'ın ev sahibi, ${match.away}'ın deplasman rolündeki devre/maç sonucu kayıtlarında ${combo} senaryosu ${n} okunabilir örneğin ${hits} tanesinde görüldü. Bu seçim nadirlik nedeniyle değil, rol uyumlu geçmiş oranı ve ana sonuç yönü birlikte desteklediği için değerlendiriliyor.`}
function goalRangeReason(c,s,form,match){return `${match.home} ve ${match.away} son maçlarında toplam gol üretimi birlikte değerlendirildiğinde model yaklaşık ${s.exp.total.toFixed(2)} toplam gole merkezleniyor. Son formda 2.5 Üst ${form.home.over25+form.away.over25}/${form.home.played+form.away.played}. Bu yüzden ${c.outcome.label} gol aralığı dağılımın yoğunlaştığı bölgelerden biri.`}
function firstGoalReason(c,s,form,match){const side=sideOf(c,match);return `${match.home} maç başına ${form.home.avgGF.toFixed(2)}, ${match.away} ${form.away.avgGF.toFixed(2)} gol üretiyor. Savunma tarafında ortalamalar ${form.home.avgGA.toFixed(2)} ve ${form.away.avgGA.toFixed(2)}. İlk gol modeli ${side==='home'?match.home:side==='away'?match.away:'golsüz başlangıç'} tarafını bu hücum-savunma dengesinden öne çıkarıyor.`}
function comboReason(c,s,form,match){const k=kindOf(c),base=resultReason(c,s,form,match);if(k==='result_total_combo')return `${base} Ayrıca birleşik gol beklentisi ${s.exp.total.toFixed(2)} ve son formdaki Üst oranı ${form.home.over25+form.away.over25}/${form.home.played+form.away.played}; bu nedenle sonuç ve gol yönünün birlikte gerçekleşmesi tek başına sonuç bahisinden daha riskli ama aynı maç hikâyesine bağlı.`;if(k==='result_btts_combo')return `${base} KG Var geçmişi ${form.home.btts+form.away.btts}/${form.home.played+form.away.played}; sonuç yönü ile KG profili aynı seçimde birleşiyor.`;return `${totalReason(c,s,form,match)} KG Var geçmişi ${form.home.btts+form.away.btts}/${form.home.played+form.away.played}; iki koşul birlikte istendiği için risk yükseliyor.`}
function reason(c,s,form,match){const k=kindOf(c);if(RESULT_KINDS.has(k)||k==='double_chance')return resultReason(c,s,form,match);if(k==='total_goals')return totalReason(c,s,form,match);if(k==='btts')return bttsReason(c,s,form,match);if(k==='htft')return htftReason(c,form,match);if(k==='goal_range')return goalRangeReason(c,s,form,match);if(k==='first_goal_team')return firstGoalReason(c,s,form,match);if(['result_total_combo','result_btts_combo','total_btts_combo'].includes(k))return comboReason(c,s,form,match);return''}
function id(c){return `${c.market.id??c.market.typeId}:${c.outcome.n}:${c.odds}`}
function marketId(c){return String(c.market.id??c.market.typeId??c.market.name)}
function pickScore(c,m,role){let z=m.confidence+m.av*4;if(role==='main'){if(RESULT_KINDS.has(kindOf(c)))z+=80;if(c.odds<=2.5)z+=10}if(role==='safe'){if(kindOf(c)==='double_chance')z+=70;if(c.odds<=2.05)z+=25}if(role==='surprise'){if(c.odds>=2&&c.odds<=5.5)z+=45-Math.abs(c.odds-3.2)*4;else z-=20}if(role==='big'){if(c.odds>=4)z+=45+Math.min(18,Math.log2(c.odds)*3);else z-=15}if(role==='special'){z+=Math.max(0,m.av)*8;if(['goal_range','htft','result_total_combo','result_btts_combo','first_goal_team'].includes(kindOf(c)))z+=12}return z}
function choose(rows,s,form,match,role,used,usedMarkets){let pool=rows.filter(c=>!used.has(id(c))&&compatible(c,s,match)).map(c=>({c,m:model(c,s,form,match)})).filter(x=>x.m);if(!pool.length)return null;const diverse=pool.filter(x=>!usedMarkets.has(marketId(x.c)));if(diverse.length)pool=diverse;if(role==='main'){const r=pool.filter(x=>RESULT_KINDS.has(kindOf(x.c)));if(r.length)pool=r}if(role==='safe'){const dc=pool.filter(x=>kindOf(x.c)==='double_chance');if(dc.length)pool=dc;else{const low=pool.filter(x=>x.c.odds<=2.25);if(low.length)pool=low}}if(role==='surprise'){const b=pool.filter(x=>x.c.odds>=2&&x.c.odds<=5.5);if(b.length)pool=b}if(role==='big'){const b=pool.filter(x=>x.c.odds>=4);if(b.length)pool=b;else pool.sort((a,b)=>b.c.odds-a.c.odds)}return pool.map(x=>({...x,z:pickScore(x.c,x.m,role)})).sort((a,b)=>b.z-a.z)[0]}
function makePick(label,x,s,form,match,tag){if(!x)return{label,available:false,tag,av:0,confidencePct:0,reason:'Bu kategori için takım verisiyle doğrulanabilen bir seçim çıkmadı.'};return{label,available:true,tag,market:x.c.market.name,selection:x.c.outcome.label,odds:x.c.odds,av:+x.m.av.toFixed(1),confidencePct:x.m.confidence,model:+x.m.model.toFixed(1),fair:+x.m.fair.toFixed(1),recommended:x.m.av>0.5&&x.m.confidence>=40,kind:kindOf(x.c),reason:reason(x.c,s,form,match)}}
function analyzeMatch(match,form){const cands=flat(match);if(Number(match.sportType)!==1){return{radar:0,form:form||null,scenario:{title:'Tenis modeli ayrı geliştiriliyor',summary:'Bu sürümde futbol analizinin güvenilirliği önceliklendirildi.',formText:'',confidence:0},picks:[],insights:[],analyzedAt:new Date().toISOString(),disclaimer:'Tenis için bağımsız form modeli tamamlanmadan tahmin üretilmez.'}}
 const s=scenario(match,cands,form);if(!formOk(form)){return{radar:10,form:form||null,formStatus:'fallback',scenario:{title:'Takım verisi yetersiz',summary:'Bu maç için yeterli doğrulanmış geçmiş takım verisi bulunamadığı için bahis önerisi üretilmedi.',formText:'Veri eksik olduğu için seçim uydurulmadı.',confidence:12},picks:[],insights:[{title:'Veri notu',text:'Oranlar görüntülenebilir; ancak takım formu doğrulanmadan NEÇ önerisi verilmez.'}],analyzedAt:new Date().toISOString(),disclaimer:'NEÇ artık takım verisi olmayan marketi sırf oranı yüksek diye önermez.'}}
 const used=new Set(),usedMarkets=new Set(),take=role=>{const x=choose(cands,s,form,match,role,used,usedMarkets);if(x){used.add(id(x.c));usedMarkets.add(marketId(x.c))}return x};const main=take('main'),safe=take('safe'),surprise=take('surprise'),big=take('big'),special=take('special');const picks=[makePick('Ana Senaryo',main,s,form,match,'ANA YÖN'),makePick('Temkinli Seçim',safe,s,form,match,'TEMKİNLİ'),makePick('Sürpriz Seçim',surprise,s,form,match,'🎯 SÜRPRİZ'),makePick('Çok Sürpriz',big,s,form,match,'🔥 ÇOK SÜRPRİZ'),makePick('NEÇ Özel',special,s,form,match,'⭐ NEÇ ÖZEL')];const avail=picks.filter(p=>p.available),sp=picks[4];return{radar:clamp(Math.round(28+s.confidence*.55+Math.max(0,...avail.map(p=>p.av))*2.5),1,99),form,scenario:{title:s.title,summary:`${formSummary(form,match)} ${s.goalLean?`Gol yönü ${s.goalLean==='over'?'Üst':'Alt'} tarafında.`:''} ${s.bttsLean?`KG profili ${s.bttsLean==='yes'?'Var':'Yok'} tarafında.`:''}`,formText:`Son 5: ${match.home} ${recentTR(form.home.recent)} (${(form.home.recentScores||[]).join(', ')}); ${match.away} ${recentTR(form.away.recent)} (${(form.away.recentScores||[]).join(', ')}).`,confidence:s.confidence,locks:{result:s.primary,goals:s.goalLean,btts:s.bttsLean},specialComment:sp.available?sp.reason:'NEÇ Özel için yeterli farklı doğrulanmış market çıkmadı.',specialOdds:sp.available?sp.odds:null,specialMarket:sp.available?sp.market:null,specialSelection:sp.available?sp.selection:null,av:sp.available?sp.av:0},picks,insights:[{title:'📋 Maç Formu',text:formSummary(form,match)},{title:'⚽ Gol Profili',text:`Birleşik gol beklentisi yaklaşık ${s.exp?.total.toFixed(2)}. Son ${form.home.played+form.away.played} takım-maç örneğinde 2.5 Üst ${form.home.over25+form.away.over25}, KG Var ${form.home.btts+form.away.btts} kez.`},{title:'🧭 Tutarlılık',text:`Sonuç yönü ${s.primary==='home'?match.home:s.primary==='away'?match.away:'Beraberlik'}; kartlar bu senaryonun tersine çıkamaz.`}],analyzedAt:new Date().toISOString(),disclaimer:'Oyuncu, şut, korner ve ikinci-yarı gibi ayrı istatistik veya kadro teyidi gerektiren marketler doğrulanmadan öneri kartına alınmaz. Oran etiketi doğrulanamayan seçimler analiz dışında bırakılır.'}}
module.exports={analyzeMatch};