const base=require('./analyzer-quality');
function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[ı]/g,'i').replace(/[ş]/g,'s').replace(/[ç]/g,'c').replace(/[ğ]/g,'g').replace(/[ö]/g,'o').replace(/[ü]/g,'u').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function avg(n,d){return d>0?n/d:0}
function verified(o){return o?.labelVerified===true||Boolean(o?.sourceLabel)}
function side(label,m){const l=norm(label),h=norm(m.home),a=norm(m.away);if(l==='1'||l==='ev sahibi'||l==='home'||(h&&(l===h||l.includes(h))))return'home';if(l==='x'||l.includes('beraber')||l==='draw')return'draw';if(l==='2'||l==='deplasman'||l==='away'||(a&&(l===a||l.includes(a))))return'away';return null}
function sideName(x,m){return x==='home'?m.home:x==='away'?m.away:'beraberlik'}
function dc(label){const l=norm(label).replace(/\s/g,'');if(l.startsWith('1x'))return['home','draw'];if(l.startsWith('x2'))return['draw','away'];if(l.startsWith('12'))return['home','away'];return[]}
function htft(label){const z=String(label||'').toUpperCase().match(/([12X])\s*[\/-]\s*([12X])/);if(!z)return null;const cv=x=>x==='1'?'home':x==='2'?'away':'draw';return[cv(z[1]),cv(z[2])]}
function resultPart(label){const z=String(label||'').toUpperCase().match(/(^|\s|\+)(1|X|2)(?=\s|\+|\/|$)/);if(!z)return null;return z[2]==='1'?'home':z[2]==='2'?'away':'draw'}
function totalDir(label){const l=norm(label);if(l.includes('ust')||l.includes('over'))return'over';if(l.includes('alt')||l.includes('under'))return'under';return null}
function bttsDir(label){const l=norm(label);if(l.includes('var')||l.includes('evet')||l.includes('yes'))return'yes';if(l.includes('yok')||l.includes('hayir')||l.includes('no'))return'no';return null}
function lineOf(c){const s=Number(c.market?.spread);if(Number.isFinite(s)&&s>0)return s;const z=String(c.outcome?.label||'').replace(',','.').match(/(\d+(?:\.\d+)?)/);return z?Number(z[1]):2.5}
function rangeMid(label){const l=norm(label),z=l.match(/(\d+)\s*[-:]\s*(\d+)/);if(z)return(+z[1]+ +z[2])/2;if(l.includes('6+'))return 6.5;return null}
function scoreParts(label){const z=String(label||'').match(/^(\d+)\s*[:\-]\s*(\d+)$/);return z?[+z[1],+z[2]]:null}
function fairMarket(m){const xs=(m?.outcomes||[]).filter(o=>Number(o.odds)>1&&verified(o)),raw={home:0,draw:0,away:0},rows=[];for(const o of xs){const x=side(o.label,{home:'1',away:'2'});let s;if(String(o.label).trim()==='1')s='home';else if(String(o.label).trim().toUpperCase()==='X')s='draw';else if(String(o.label).trim()==='2')s='away';else s=x;if(!s)continue;raw[s]=1/Number(o.odds);rows.push({side:s,outcome:o,odds:Number(o.odds)})}const sum=raw.home+raw.draw+raw.away;if(!sum)return null;for(const k of Object.keys(raw))raw[k]=raw[k]/sum*100;return{probs:raw,rows,favorite:Object.entries(raw).sort((a,b)=>b[1]-a[1])[0][0],favoriteOdds:Math.min(...rows.map(r=>r.odds))}}
function formProbs(f){if(!(f?.home?.played>=4&&f?.away?.played>=4))return null;const h=f.home,a=f.away,hr=h.roleStats?.home?.played>=2?h.roleStats.home:null,ar=a.roleStats?.away?.played>=2?a.roleStats.away:null;let home=(avg(h.wins,h.played)+avg(a.losses,a.played))/2,draw=(avg(h.draws,h.played)+avg(a.draws,a.played))/2,away=(avg(a.wins,a.played)+avg(h.losses,h.played))/2;if(hr&&ar){home=home*.6+((avg(hr.wins,hr.played)+avg(ar.losses,ar.played))/2)*.4;draw=draw*.6+((avg(hr.draws,hr.played)+avg(ar.draws,ar.played))/2)*.4;away=away*.6+((avg(ar.wins,ar.played)+avg(hr.losses,hr.played))/2)*.4}const s=home+draw+away||1;return{home:home/s*100,draw:draw/s*100,away:away/s*100}}
function profile(match,form){if(!(form?.home?.played>=4&&form?.away?.played>=4))return null;const h=form.home,a=form.away,total=h.played+a.played||1,expH=clamp(((h.avgGF||0)+(a.avgGA||0))/2,.2,4.2),expA=clamp(((a.avgGF||0)+(h.avgGA||0))/2,.2,4.2);return{h,a,expH,expA,totalExp:expH+expA,over:(h.over25+a.over25)/total,btts:(h.btts+a.btts)/total}}
function story(match,form){const mr=(match.markets||[]).find(m=>['match_result','match_winner'].includes(m.kind)),market=fairMarket(mr),fp=formProbs(form),p=profile(match,form);if(!market||!fp)return null;const w=market.favoriteOdds<=1.55?.82:market.favoriteOdds<=1.9?.70:.58,probs={};for(const k of ['home','draw','away'])probs[k]=market.probs[k]*w+fp[k]*(1-w);let leader=Object.entries(probs).sort((a,b)=>b[1]-a[1])[0][0];const row=market.rows.find(r=>r.side===leader);if(row&&row.odds>4.5)leader=market.favorite;const formLeader=Object.entries(fp).sort((a,b)=>b[1]-a[1])[0][0];return{market,fp,p,probs,leader,formLeader,marketLeader:market.favorite,conflict:formLeader!==market.favorite}}
function roleText(team,key){const r=team?.roleStats?.[key];if(!r?.played)return'';return `${r.played} maçta ${r.wins}G-${r.draws}B-${r.losses}M, ${r.avgGF.toFixed(2)} atıp ${r.avgGA.toFixed(2)} yedi`}
function statLine(form,match){const s=form?.flashStats;if(!s)return'';const fmt=(team,x)=>{const a=[];if(Number.isFinite(x?.xg))a.push(`xG ${x.xg.toFixed(2)}`);if(Number.isFinite(x?.shots))a.push(`${x.shots.toFixed(1)} şut`);if(Number.isFinite(x?.sot))a.push(`${x.sot.toFixed(1)} isabetli şut`);if(Number.isFinite(x?.corners))a.push(`${x.corners.toFixed(1)} korner`);return a.length?`${team}: ${a.join(', ')}`:''};const h=fmt(match.home,s.home),a=fmt(match.away,s.away);return[h,a].filter(Boolean).join(' · ')}
function marketText(st,match){if(!st)return'';return st.market.rows.map(r=>`${r.side==='home'?match.home:r.side==='away'?match.away:'X'} ${r.odds.toFixed(2)}`).join(' · ')}
function narrative(match,form,st){const p=st.p,h=p.h,a=p.a,homeRole=roleText(h,'home'),awayRole=roleText(a,'away'),stats=statLine(form,match),market=marketText(st,match),main=sideName(st.leader,match),formLead=sideName(st.formLeader,match),marketLead=sideName(st.marketLeader,match);let t=`${match.home} son ${h.played} maçta ${h.wins}G-${h.draws}B-${h.losses}M (${h.avgGF.toFixed(2)} atıp ${h.avgGA.toFixed(2)} yedi); ${match.away} ${a.wins}G-${a.draws}B-${a.losses}M (${a.avgGF.toFixed(2)} atıp ${a.avgGA.toFixed(2)} yedi).`;if(homeRole||awayRole)t+=` Rol ayrımında ${match.home} evinde ${homeRole||'örnek yetersiz'}; ${match.away} deplasmanda ${awayRole||'örnek yetersiz'}.`;if(stats)t+=` Flashscore detay ortalamaları: ${stats}.`;t+=` Nesine ana fiyatları ${market}.`;if(st.conflict)t+=` Son form kağıt üzerinde ${formLead} tarafını öne çıkarıyor; ancak bu on maç rakip kalitesini tek başına eşitlemiyor ve piyasa ${marketLead} tarafına çok daha güçlü bir temel seviye veriyor. Bu yüzden ${formLead} galibiyetini ana tahmin yapmak yerine sürpriz risk olarak okuyorum.`;t+=` Benim ana maç hikâyem: ${main} tarafının oyunun ana kontrolünü alması; rakibin son formunu ise bu senaryonun risk unsuru olarak görmek.`;return t}
function fairForMarket(m,o){const xs=(m.outcomes||[]).filter(x=>Number(x.odds)>1&&verified(x)),sum=xs.reduce((s,x)=>s+1/Number(x.odds),0);return sum?((1/Number(o.odds))/sum)*100:100/Number(o.odds)}
function mainFix(result,match,form,st){if(!result||!Array.isArray(result.picks)||!st)return;const idx=result.picks.findIndex(x=>x.label==='Ana Senaryo');if(idx<0)return;const mr=(match.markets||[]).find(m=>['match_result','match_winner'].includes(m.kind));const row=st.market.rows.find(r=>r.side===st.leader);if(!mr||!row)return;const fair=st.market.probs[st.leader],model=st.probs[st.leader],av=clamp(model-fair,-15,15),reason=`NEÇ düşüncesi: ${narrative(match,form,st)} Bu nedenle Ana Senaryo olarak ${mr.name} · ${row.outcome.label} seçiyorum. Burada “en yüksek AV” kovalamıyorum; Ana Senaryo önce maçın en olası omurgasını temsil ediyor.`,confidence=Math.round(clamp(52+model*.22+(st.leader===st.marketLeader?8:0),52,82));result.picks[idx]={...result.picks[idx],market:mr.name,selection:row.outcome.label,odds:row.odds,av:+av.toFixed(1),model:+model.toFixed(1),fair:+fair.toFixed(1),confidencePct:confidence,recommended:model>=45,reason};result.scenario=result.scenario||{};result.scenario.title=st.conflict?`${sideName(st.marketLeader,match)} piyasa üstünlüğü, ${sideName(st.formLeader,match)} form uyarısı`:`${sideName(st.leader,match)} yönünde form + piyasa kesişimi`;result.scenario.summary=narrative(match,form,st);result.scenario.formText=`Gol profili: ${match.home} ${st.p.expH.toFixed(2)} - ${st.p.expA.toFixed(2)} ${match.away}; son örnekte 2.5 Üst %${(st.p.over*100).toFixed(0)}, KG Var %${(st.p.btts*100).toFixed(0)}.${statLine(form,match)?` Detay: ${statLine(form,match)}.`:''}`;result.scenario.confidence=confidence}
function candRows(match){const out=[];for(const m of match.markets||[]){for(const o of m.outcomes||[]){const odds=Number(o.odds);if(odds>1&&verified(o))out.push({market:m,outcome:o,odds})}}return out}
function compatible(c,st,match){const k=c.market.kind,l=c.outcome.label;if(['match_result','match_winner'].includes(k))return side(l,match)===st.leader;if(k==='double_chance')return dc(l).includes(st.leader);if(k==='htft')return htft(l)?.[1]===st.leader;if(['result_total_combo','result_btts_combo'].includes(k)){const r=resultPart(l);return !r||r===st.leader}if(k==='first_goal_team'){const x=side(l,match);return !x||x===st.leader}if(k==='total_goals'){const d=totalDir(l);return !d||(st.p.over>=.55?d==='over':st.p.over<=.45?d==='under':true)}if(k==='btts'){const d=bttsDir(l);return !d||(st.p.btts>=.57?d==='yes':st.p.btts<=.43?d==='no':true)}if(k==='goal_range'){const mid=rangeMid(l);return mid===null||Math.abs(mid-st.p.totalExp)<=1.8}if(Number(c.market.typeId)===777){const s=scoreParts(l);if(!s)return false;const win=s[0]>s[1]?'home':s[0]<s[1]?'away':'draw';return win===st.leader&&Math.abs((s[0]+s[1])-st.p.totalExp)<=2}return !['player_goal','player_first_goal','player_shot','player_sot','player_assist','player_goal_assist','team_shots_total','team_sot_total'].includes(k)}
function evidence(c,st,match){const k=c.market.kind,l=c.outcome.label;let s=0;if(['match_result','match_winner'].includes(k))s=side(l,match)===st.leader?6:-6;else if(k==='double_chance')s=dc(l).includes(st.leader)?5:-4;else if(k==='htft'){const z=htft(l);s=z?.[1]===st.leader?4:-5;if(z?.[0]==='draw')s+=1}else if(k==='total_goals'){const d=totalDir(l);s=d==='over'?(st.p.over-.5)*12:d==='under'?(0.5-st.p.over)*12:0}else if(k==='btts'){const d=bttsDir(l);s=d==='yes'?(st.p.btts-.5)*12:d==='no'?(0.5-st.p.btts)*12:0}else if(k==='goal_range'){const mid=rangeMid(l);s=mid===null?0:5-Math.abs(mid-st.p.totalExp)*2}else if(Number(c.market.typeId)===777){const z=scoreParts(l);if(z){const win=z[0]>z[1]?'home':z[0]<z[1]?'away':'draw';s=(win===st.leader?4:-4)+(3-Math.abs((z[0]+z[1])-st.p.totalExp))}}else s=1;return s}
function roleBand(label,o){if(label==='Temkinli Seçim')return o<=1.95;if(label==='Sürpriz Seçim')return o>=2&&o<=5.5;if(label==='Çok Sürpriz')return o>=3.5&&o<=15;if(label==='NEÇ Özel')return o>=1.65&&o<=12;return true}
function rewriteReason(pick,c,st,match,form){const baseCtx=`${match.home} ${st.p.h.wins}G-${st.p.h.draws}B-${st.p.h.losses}M, ${match.away} ${st.p.a.wins}G-${st.p.a.draws}B-${st.p.a.losses}M; beklenen gol dengesi ${st.p.expH.toFixed(2)}-${st.p.expA.toFixed(2)}.`;const k=c.market.kind;if(k==='htft'){const z=htft(c.outcome.label);return `NEÇ düşüncesi: ${baseCtx} ${c.outcome.label}, ilk yarı ${sideName(z?.[0],match)} / maç sonu ${sideName(z?.[1],match)} demek. Ana hikâyede final yönünü ${sideName(st.leader,match)} olarak koruyorum; ilk yarı şartı oranı yükselten ekstra risk.`}if(k==='total_goals')return `NEÇ düşüncesi: ${baseCtx} Son ${st.p.h.played+st.p.a.played} maçlık örnekte 2.5 Üst ${(st.p.over*100).toFixed(0)}% civarında. ${c.outcome.label} seçimini taraf sonucundan bağımsız tempo fikri olarak görüyorum; ${statLine(form,match)||'detay şut verisi sınırlı'}.`;if(k==='btts')return `NEÇ düşüncesi: ${baseCtx} KG Var sıklığı yaklaşık ${(st.p.btts*100).toFixed(0)}%. ${c.outcome.label} burada “kim kazanır?” sorusundan farklı; iki hücumun da skor üretip üretemeyeceğine oynuyor.`;if(k==='goal_range')return `NEÇ düşüncesi: ${baseCtx} Toplam beklenti ${st.p.totalExp.toFixed(2)} gole yakın. ${c.outcome.label} dar bir skor bandı olduğu için daha zor ama beklentinin merkezine yakınsa sürpriz kartta anlamlı.`;if(Number(c.market.typeId)===777)return `NEÇ düşüncesi: ${baseCtx} Ana final yönünü ${sideName(st.leader,match)} olarak koruyup bunu tam skora sıkıştırıyorum. ${c.outcome.label} bu yüzden yüksek oranlı, düşük toleranslı bir uç senaryo.`;return `NEÇ düşüncesi: ${baseCtx} ${c.market.name} · ${c.outcome.label} ana hikâyeyle çelişmeden farklı bir risk katmanı ekliyor.`}
function cohere(result,match,form,st){if(!st||!Array.isArray(result?.picks))return;const all=candRows(match),used=new Set(result.picks.map(p=>`${p.market}|${p.selection}`));for(const label of ['Temkinli Seçim','Sürpriz Seçim','Çok Sürpriz','NEÇ Özel']){const idx=result.picks.findIndex(p=>p.label===label);if(idx<0)continue;let cur=result.picks[idx],cm=(match.markets||[]).find(m=>m.name===cur.market),co=cm?.outcomes?.find(o=>o.label===cur.selection&&Number(o.odds)===Number(cur.odds)),cc=cm&&co?{market:cm,outcome:co,odds:Number(co.odds)}:null;if(cc&&compatible(cc,st,match)&&roleBand(label,cc.odds)){cur.reason=rewriteReason(cur,cc,st,match,form);continue}used.delete(`${cur.market}|${cur.selection}`);let q=all.filter(c=>!used.has(`${c.market.name}|${c.outcome.label}`)&&compatible(c,st,match)&&roleBand(label,c.odds)&&!['team_shots_total','team_sot_total','player_goal','player_first_goal','player_shot','player_sot','player_assist','player_goal_assist'].includes(c.market.kind));if(label==='Çok Sürpriz')q=q.filter(c=>c.odds>=3.5);q.sort((a,b)=>(evidence(b,st,match)*3+Math.log(b.odds)*2)-(evidence(a,st,match)*3+Math.log(a.odds)*2));const best=q[0];if(!best)continue;used.add(`${best.market.name}|${best.outcome.label}`);const f=fairForMarket(best.market,best.outcome),e=evidence(best,st,match),model=clamp(f+e*1.2,1,99),av=clamp(model-f,-12,12);result.picks[idx]={...cur,market:best.market.name,selection:best.outcome.label,odds:best.odds,av:+av.toFixed(1),model:+model.toFixed(1),fair:+f.toFixed(1),confidencePct:label==='Çok Sürpriz'?38:label==='Sürpriz Seçim'?48:label==='Temkinli Seçim'?62:52,recommended:av>1,reason:rewriteReason(cur,best,st,match,form)}}const sp=result.picks.find(p=>p.label==='NEÇ Özel');if(sp&&result.scenario){result.scenario.specialComment=sp.reason;result.scenario.specialOdds=sp.odds;result.scenario.specialMarket=sp.market;result.scenario.specialSelection=sp.selection}}
function teamOfLabel(label,match){const l=norm(label),h=norm(match.home),a=norm(match.away),ht=h.split(' ').filter(x=>x.length>2),at=a.split(' ').filter(x=>x.length>2);const hs=ht.filter(x=>l.includes(x)).length,as=at.filter(x=>l.includes(x)).length;if(l.startsWith('toplam'))return'total';if(hs>as&&hs>0)return'home';if(as>hs&&as>0)return'away';return null}
function threshold(label){const z=String(label||'').match(/(\d+(?:\.\d+)?)\s*\+/);return z?Number(z[1]):null}
function teamIdeas(match,form){const fs=form?.flashStats;if(!fs)return[];const ideas=[];for(const m of match.markets||[]){const stat=m.kind==='team_shots_total'?'shots':m.kind==='team_sot_total'?'sot':null;if(!stat)continue;for(const o of m.outcomes||[]){if(!(Number(o.odds)>=1.55&&Number(o.odds)<=4.5)||!verified(o))continue;const who=teamOfLabel(o.label,match),line=threshold(o.label);if(!who||line===null)continue;let mean=null,detail='';if(who==='home'&&Number.isFinite(fs.home?.[stat])){mean=fs.home[stat];detail=`${match.home} son detaylı maçlarında ortalama ${mean.toFixed(1)} ${stat==='shots'?'şut':'isabetli şut'}`}else if(who==='away'&&Number.isFinite(fs.away?.[stat])){mean=fs.away[stat];detail=`${match.away} son detaylı maçlarında ortalama ${mean.toFixed(1)} ${stat==='shots'?'şut':'isabetli şut'}`}else if(who==='total'&&Number.isFinite(fs.home?.[stat])&&Number.isFinite(fs.away?.[stat])){mean=fs.home[stat]+fs.away[stat];detail=`İki takımın son detaylı maç ortalamaları toplamı ${mean.toFixed(1)} ${stat==='shots'?'şut':'isabetli şut'}`}if(mean===null)continue;const margin=mean-line;if(margin<-.25)continue;ideas.push({tag:'📈 TAKIM İSTATİSTİĞİ',market:m.name,selection:o.label,odds:Number(o.odds),confidencePct:Math.round(clamp(52+margin*4,48,72)),reason:`${detail}. Nesine çizgisi ${o.label} ve oran ${Number(o.odds).toFixed(2)}. Ortalama çizginin ${margin>=0?`${margin.toFixed(1)} üzerinde`:`${Math.abs(margin).toFixed(1)} altında`} olduğu için bunu ana 5'ten ayrı, veri destekli takım fikri olarak öne çıkarıyorum.`,verifiedBy:'Flashscore son maç detay istatistikleri + Nesine gerçek market',score:margin*3+Math.log(Number(o.odds))*2})}}return ideas.sort((a,b)=>b.score-a.score).filter((x,i,a)=>a.findIndex(y=>y.market===x.market&&y.selection===x.selection)===i).slice(0,3)}
function analyzeMatch(match,form){const result=base.analyzeMatch(match,form);if(Number(match?.sportType)!==1||!form)return result;const st=story(match,form);if(!st)return result;mainFix(result,match,form,st);cohere(result,match,form,st);result.ideas=teamIdeas(match,form);result.insights=Array.isArray(result.insights)?result.insights:[];result.insights.unshift({title:'🧠 Maç Hikâyesi Kuralı',text:`Ana yön artık yalnızca son 10 forma göre seçilmiyor. Piyasa temel seviyesi, ev/deplasman rolü ve Flashscore detayları birlikte okunuyor; 4.50+ underdog otomatik olarak Ana Senaryo olamaz.`});return result}
module.exports={analyzeMatch};
