const legacy=require('./analyzer');
function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim()}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function verified(o){return o?.labelVerified===true||Boolean(o?.sourceLabel)}
function keyOf(c){return `${c.market.id??c.market.typeId}:${c.outcome.n}`}
function fair(c){const xs=(c.market.outcomes||[]).map(o=>Number(o.odds)).filter(x=>x>1);const sum=xs.reduce((s,x)=>s+1/x,0);return sum?((1/c.odds)/sum)*100:100/c.odds}
function rows(match){const out=[];for(const market of match.markets||[])for(const outcome of market.outcomes||[]){const odds=Number(outcome.odds);if(odds>1&&verified(outcome))out.push({market,outcome,odds})}return out}
function side(c,m){const l=norm(c.outcome.label),h=norm(m.home),a=norm(m.away);if(l==='1'||l==='ev sahibi'||l==='home'||(h&&(l===h||l.includes(h))))return'home';if(l==='x'||l.includes('beraber')||l==='draw')return'draw';if(l==='2'||l==='deplasman'||l==='away'||(a&&(l===a||l.includes(a))))return'away';return null}
function sideName(x,m){return x==='home'?m.home:x==='away'?m.away:'beraberlik'}
function totalDir(label){const l=norm(label);if(l.includes('üst')||l.includes('ust')||l.includes('over'))return'over';if(l.includes('alt')||l.includes('under'))return'under';return null}
function bttsDir(label){const l=norm(label);if(l.includes('var')||l.includes('evet')||l.includes('yes'))return'yes';if(l.includes('yok')||l.includes('hayır')||l.includes('hayir')||l.includes('no'))return'no';return null}
function dcParts(label){const l=norm(label).replace(/\s/g,'');if(l.startsWith('1x'))return['home','draw'];if(l.startsWith('x2'))return['draw','away'];if(l.startsWith('12'))return['home','away'];return[]}
function htft(label){const m=String(label||'').toUpperCase().match(/([12X])\s*[\/-]\s*([12X])/);if(!m)return null;const cv=x=>x==='1'?'home':x==='2'?'away':'draw';return[cv(m[1]),cv(m[2])]}
function resultPart(label){const m=String(label||'').toUpperCase().match(/(^|\s|\+)(1|X|2)(?=\s|\+|\/|$)/);if(!m)return null;return m[2]==='1'?'home':m[2]==='2'?'away':'draw'}
function marketForPick(match,p){return (match.markets||[]).find(m=>m.name===p.market)||null}
function roleTail(label){return label==='Temkinli Seçim'?' Bu yüzden bunu daha düşük riskli kartta tutuyorum.':label==='Sürpriz Seçim'?' Oranı yükseldiği için ana seçim değil, sürpriz senaryo olarak görüyorum.':label==='Çok Sürpriz'?' Bu senaryo zor; yüksek oranlı olduğu için ancak maç hikâyesinin uç ihtimali olarak değerlendirilmeli.':label==='NEÇ Özel'?' NEÇ Özel’de güvenli seçimi tekrar etmek yerine aynı maçın farklı fiyatlanan tarafını arıyorum.':''}
function footballReason(match,form,p){const h=form.home,a=form.away,mk=marketForPick(match,p),k=mk?.kind||'',sel=p.selection,tail=roleTail(p.label);const expH=clamp(((h.avgGF||0)+(a.avgGA||0))/2,.2,4.2),expA=clamp(((a.avgGF||0)+(h.avgGA||0))/2,.2,4.2),total=expH+expA,over=h.over25+a.over25,btts=h.btts+a.btts,totalGames=h.played+a.played;
 if(['match_result','match_winner'].includes(k)){const x=side({market:mk,outcome:{label:sel}},match);if(x==='away')return `NEÇ yorumu: ${match.away} son ${a.played} maçın ${a.wins}'ini kazandı, maç başına ${a.avgGF.toFixed(2)} gol attı; ${match.home} ise ${h.losses} kez kaybetti. Bu seçim için model olasılığı %${Number(p.model||0).toFixed(0)}. Bence ${sel}, deplasman formu belirgin biçimde daha güçlü olduğu için mantıklı.${tail}`;if(x==='home')return `NEÇ yorumu: ${match.home} son ${h.played} maçın ${h.wins}'ini kazandı; ${match.away} ${a.losses} mağlubiyet aldı. Model ${sel} için %${Number(p.model||0).toFixed(0)} veriyor. Ben ev sahibini burada sonuç üretme gücü ve rakibin yenilgi profili nedeniyle öne çıkarıyorum.${tail}`;return `NEÇ yorumu: Beraberlik seçimi, iki takımın kazanma ihtimalleri birbirine yaklaştığında değer kazanıyor. Model bu seçim için %${Number(p.model||0).toFixed(0)} hesaplıyor; ${match.home} ${h.draws}, ${match.away} ${a.draws} beraberlik gördü. Bu yüzden ${sel} tarafını tamamen dışlamıyorum.${tail}`}
 if(k==='double_chance'){const names=dcParts(sel).map(x=>sideName(x,match)).join(' / ');return `NEÇ yorumu: ${sel}, ${names} sonuçlarından ikisini kapsıyor. ${match.home} ${h.wins}G-${h.losses}M, ${match.away} ${a.wins}G-${a.losses}M. Tek bir sonuca kilitlenmek yerine ana güçlü tarafı beraberlik ihtimaliyle korumak bu maçta daha mantıklı geliyor.${tail}`}
 if(k==='total_goals'){const d=totalDir(sel);return d==='over'?`NEÇ yorumu: Burada taraf değil tempo oynuyorum. İki takımın son ${totalGames} maçında 2.5 Üst ${over} kez geldi; basit gol beklentisi toplam ${total.toFixed(2)}. Bu yüzden ${sel} seçimini, maçın 3+ gole açılma ihtimali yüksek olduğu için uygun görüyorum.${tail}`:`NEÇ yorumu: ${sel} için maçın beklenenden daha kontrollü kalması gerekiyor. Son ${totalGames} maçta 2.5 Üst ${over} kez oldu ve toplam gol beklentisi ${total.toFixed(2)}. Üst profili aşırı baskın değilse düşük tempolu senaryoyu bu kartta değerlendirmek mantıklı.${tail}`}
 if(k==='btts'){const d=bttsDir(sel);return d==='yes'?`NEÇ yorumu: KG Var için iki tarafın da skor üretmesini arıyorum. Toplam ${totalGames} maçlık örnekte KG Var ${btts} kez oldu; ${match.home} maç başına ${h.avgGF.toFixed(2)}, ${match.away} ${a.avgGF.toFixed(2)} gol atıyor. Bu yüzden ${sel} benim için doğrudan iki hücumun da çalışacağı senaryo.${tail}`:`NEÇ yorumu: KG Yok için taraflardan birinin skor üretememesi gerekiyor. ${match.home} ${h.failedToScore} kez, ${match.away} ${a.failedToScore} kez gol atamadı. Bu nedenle ${sel}, gol sayısından çok bitiricilik/savunma dengesine oynayan ayrı bir fikir.${tail}`}
 if(k==='htft'){const z=htft(sel);if(z)return `NEÇ yorumu: ${sel}, ilk yarı ${sideName(z[0],match)} / maç sonu ${sideName(z[1],match)} demek. Bu seçimde iki aşamalı bir maç istiyorum: başlangıç bir tarafa, final başka tarafa dönebilir. Özellikle 1/2 veya 2/1 gibi dönüşler ana tahmin değil, yüksek oranlı senaryodur. İlk yarı geçmişini ayrıca doğrulayamadığım için bunu güvenli seçim saymıyorum.${tail}`}
 if(k==='goal_range')return `NEÇ yorumu: Gol beklentisi yaklaşık ${total.toFixed(2)}. ${sel} dar bir gol aralığı istediği için normal Üst/Alt seçimine göre daha zor ama oranı da bunun karşılığında yükseliyor. Ben bunu iki takımın birleşik gol profili bu toplam çevresinde toplandığı için sürpriz senaryoda değerlendiriyorum.${tail}`
 if(k==='first_goal_team')return `NEÇ yorumu: İlk gol marketinde maç sonucundan önce kimin daha fazla hücum üreteceğine bakıyorum. Gol beklentisi ${match.home} ${expH.toFixed(2)} - ${expA.toFixed(2)} ${match.away}. Bu dağılım ${sel} tarafına ilk darbeyi vurma şansı veriyor.${tail}`
 if(k==='result_total_combo'){const r=resultPart(sel),d=totalDir(sel);return `NEÇ yorumu: Bu kombine iki şart istiyor: ${r?sideName(r,match):'seçilen taraf'} maç sonucunu alacak ve gol tarafı ${d==='over'?'yüksek':'düşük'} kalacak. Sonuç formu ile ${total.toFixed(2)} toplam gol beklentisini tek kuponda birleştirdiğimiz için oran yükseliyor. Bence bu, ana maç hikâyesinin daha cesur versiyonu.${tail}`}
 if(k==='result_btts_combo')return `NEÇ yorumu: Burada hem maç sonucunu hem de karşılıklı gol şartını aynı anda istiyoruz. Sonuç yönü ile son ${totalGames} maçta ${btts} kez görülen KG profilini birlikte oynuyoruz. Tek başına iki ayrı seçimden daha zor olduğu için bunu ancak sürpriz/özel kartta mantıklı buluyorum.${tail}`
 if(k==='total_btts_combo')return `NEÇ yorumu: Bu market gol sayısı ile KG şartını aynı anda istiyor. Son ${totalGames} maçta 2.5 Üst ${over}, KG Var ${btts} kez gerçekleşti. İki eğilim aynı yöne bakıyorsa ${sel}, aynı gol hikâyesinin daha yüksek oranlı birleşimi oluyor.${tail}`
 return `NEÇ yorumu: ${p.market} · ${sel} seçimini, ${match.home}-${match.away} maçının ana taraf ve gol hikâyesine farklı bir fiyat sunduğu için ayırıyorum. Bu kartın amacı önceki seçimi tekrar etmek değil.${tail}`
}
function rewriteFootball(result,match,form){if(!result||!Array.isArray(result.picks)||!form?.home||!form?.away)return result;result.picks=result.picks.map(p=>({...p,reason:footballReason(match,form,p)}));const sp=result.picks.find(p=>p.label==='NEÇ Özel')||result.picks[result.picks.length-1];if(result.scenario&&sp)result.scenario.specialComment=`NEÇ Özel: ${sp.market} · ${sp.selection}. Bu seçim ana kartın kopyası değil; aynı maç hikâyesinin farklı fiyatlanan senaryosu.`;if(result.insights)result.insights.push({title:'🧠 Seçim Mantığı',text:'Beş kart artık aynı paragrafı tekrar etmez; her seçim kendi market koşuluna göre ayrı gerekçelendirilir.'});return result}
function tennisReason(match,form,p){const mk=marketForPick(match,p),x=mk?side({market:mk,outcome:{label:p.selection}},match):null;if(form?.home&&form?.away&&x){const h=form.home,a=form.away,chosen=x==='home'?match.home:match.away,w=x==='home'?h.wins:a.wins,l=x==='home'?h.losses:a.losses;return `NEÇ yorumu: ${chosen} son ${x==='home'?h.played:a.played} maçta ${w} galibiyet ${l} mağlubiyet aldı. ${p.market} · ${p.selection} seçimini bu form yönü ve %${Number(p.model||0).toFixed(0)} model olasılığı nedeniyle değerlendiriyorum.${roleTail(p.label)}`};return `NEÇ yorumu: ${p.market} · ${p.selection} ${Number(p.odds).toFixed(2)} oranla açılmış. Bu kartı ${p.label==='Çok Sürpriz'?'yüksek oranlı uç senaryo':p.label==='Temkinli Seçim'?'daha düşük riskli alternatif':'ana maç yönünün farklı fiyatı'} olarak ayırıyorum; aynı açıklamayı diğer kartlara kopyalamıyorum.`}
function rewriteTennis(result,match,form){if(!result||!Array.isArray(result.picks))return result;result.picks=result.picks.map(p=>({...p,reason:tennisReason(match,form,p)}));return result}
function marketPrimary(match,all){const r=all.filter(c=>['match_result','match_winner'].includes(c.market.kind));const ps={home:0,draw:0,away:0};for(const c of r){const x=side(c,match);if(x)ps[x]=Math.max(ps[x],fair(c))}return Object.entries(ps).sort((a,b)=>b[1]-a[1])[0][1]>0?Object.entries(ps).sort((a,b)=>b[1]-a[1])[0][0]:'home'}
function compatibleFallback(c,primary,match){const k=c.market.kind;if(['match_result','match_winner'].includes(k))return side(c,match)===primary;if(k==='double_chance')return dcParts(c.outcome.label).includes(primary);if(k==='htft'){const z=htft(c.outcome.label);return !z||z[1]===primary}if(['result_total_combo','result_btts_combo'].includes(k)){const r=resultPart(c.outcome.label);return !r||r===primary}return true}
function fallbackReason(c,primary,match,label){const prices=(c.market.outcomes||[]).filter(o=>Number(o.odds)>1&&verified(o)).map(o=>`${o.label} ${Number(o.odds).toFixed(2)}`).join(' · ');const k=c.market.kind;if(['match_result','match_winner'].includes(k))return `NEÇ yorumu: Son form eşleşmesi henüz gelmedi; bu yüzden bu kartta Nesine ana fiyatını okuyorum: ${prices}. Piyasa ${sideName(primary,match)} tarafını daha güçlü fiyatlıyor. ${c.outcome.label} seçimini geçici ana yön olarak alıyorum, güveni düşük tutuyorum.`;if(k==='double_chance')return `NEÇ yorumu: Ana piyasa yönü ${sideName(primary,match)}. ${c.outcome.label} bu yönü ikinci bir sonuçla koruduğu için daha temkinli alternatif. Fiyat dağılımı: ${prices}.`;if(k==='total_goals')return `NEÇ yorumu: Gol tarafında elimde henüz form yok; bu yüzden ${prices} fiyat dağılımını okuyorum. ${c.outcome.label} piyasanın maç temposuna verdiği ilk sinyal. Form geldiğinde bu seçim yeniden hesaplanacak.${roleTail(label)}`;if(k==='btts')return `NEÇ yorumu: KG marketindeki fiyatlar ${prices}. ${c.outcome.label} seçimini şu anda yalnızca piyasanın iki takımın gol bulma ihtimaline verdiği ağırlık nedeniyle ayırıyorum; bunu form analiziymiş gibi göstermiyorum.${roleTail(label)}`;if(k==='htft'){const z=htft(c.outcome.label);return `NEÇ yorumu: ${c.outcome.label}, ilk yarı ${z?sideName(z[0],match):'seçilen sonuç'} / maç sonu ${z?sideName(z[1],match):'seçilen sonuç'} demek. Ana piyasa yönü ${sideName(primary,match)}; maç sonu ayağı bu yönü koruduğu için yüksek oranlı dönüş senaryosu olarak değerlendiriyorum. Form gelmeden güvenli seçim değil.`};return `NEÇ yorumu: ${c.market.name} · ${c.outcome.label} ${c.odds.toFixed(2)}. Ana piyasa yönü ${sideName(primary,match)}; bu seçim aynı hikâyenin farklı fiyatlanan kolu. Form geldiğinde yeniden tartılacak.${roleTail(label)}`}
function footballFallback(match){const allowed=new Set(['match_result','match_winner','double_chance','total_goals','btts','htft','goal_range','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo']),all=rows(match).filter(c=>allowed.has(c.market.kind));if(!all.length)return null;const primary=marketPrimary(match,all),used=new Set(),defs=[['Ana Senaryo','ANA YÖN','main'],['Temkinli Seçim','TEMKİNLİ','safe'],['Sürpriz Seçim','🎯 SÜRPRİZ','surprise'],['Çok Sürpriz','🔥 ÇOK SÜRPRİZ','big'],['NEÇ Özel','⭐ NEÇ ÖZEL','special']],picks=[];function choose(role){let p=all.filter(c=>!used.has(keyOf(c))&&compatibleFallback(c,primary,match));if(role==='main'){const q=p.filter(c=>['match_result','match_winner'].includes(c.market.kind));if(q.length)p=q}else if(role==='safe'){const q=p.filter(c=>c.market.kind==='double_chance'||c.odds<=1.85);if(q.length)p=q}else if(role==='surprise'){const q=p.filter(c=>c.odds>=2&&c.odds<=5);if(q.length)p=q}else if(role==='big'){const q=p.filter(c=>c.odds>=4);if(q.length)p=q}else if(role==='special'){const q=p.filter(c=>['htft','goal_range','first_goal_team','result_total_combo','result_btts_combo','total_btts_combo'].includes(c.market.kind));if(q.length)p=q}if(!p.length)p=all.filter(c=>!used.has(keyOf(c)));p.sort((a,b)=>role==='big'?b.odds-a.odds:fair(b)-fair(a));return p[0]||null}
 for(const [label,tag,role] of defs){const c=choose(role);if(!c)break;used.add(keyOf(c));const fp=fair(c);picks.push({label,tag,available:true,market:c.market.name,selection:c.outcome.label,odds:c.odds,av:0,confidencePct:role==='main'?42:role==='safe'?40:role==='surprise'?34:role==='big'?28:32,recommended:false,model:+fp.toFixed(1),fair:+fp.toFixed(1),reason:fallbackReason(c,primary,match,label)})}
 const main=all.filter(c=>['match_result','match_winner'].includes(c.market.kind)),priceText=main.length?main.map(c=>`${c.outcome.label} ${c.odds.toFixed(2)}`).join(' · '):'ana sonuç marketi sınırlı',sp=picks.find(p=>p.label==='NEÇ Özel')||picks[picks.length-1];return{radar:38,form:null,formStatus:'market-only-football',scenario:{title:`${sideName(primary,match)} yönlü geçici maç hikâyesi`,summary:`Form eşleşmesi henüz gelmedi ama maç boş bırakılmadı. Nesine ana fiyatları: ${priceText}. İlk piyasa yönü ${sideName(primary,match)}; beş kart farklı risk seviyelerinde üretildi.`,formText:'Form eşleşmesi gelene kadar yalnızca doğrulanmış Nesine oran dağılımı kullanılıyor.',confidence:38,specialComment:sp?`NEÇ Özel: ${sp.market} · ${sp.selection}. Form geldiğinde yeniden hesaplanacak.`:'',specialOdds:sp?.odds??null,specialMarket:sp?.market??null,specialSelection:sp?.selection??null},picks,insights:[{title:'📡 Ana Piyasa',text:priceText},{title:'🧠 NEÇ Notu',text:'Form olmadığı için NEÇ AV 0.0 nötr tutuldu; seçimler yine de boş bırakılmadı.'}],research:{engine:'Nesine market model',sources:[]},analyzedAt:new Date().toISOString(),disclaimer:'Form verisi gelmeden üretilen piyasa okuması daha düşük güvenlidir; sonuç garantisi değildir.'}}
function analyzeMatch(match,form){const sport=Number(match?.sportType);let result=legacy.analyzeMatch(match,form);if(sport===1){if((result?.picks||[]).length)return rewriteFootball(result,match,form);return footballFallback(match)||result}if(sport===5)return rewriteTennis(result,match,form);return result}
module.exports={analyzeMatch};
