const BASES=['https://local-global.flashscore.ninja/2/x/feed/','https://2.flashscore.ninja/2/x/feed/','https://d.flashscore.com/x/feed/'];
const HEADERS={'x-fsign':'SW9D1eZo','User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/151 Safari/537.36','Accept':'*/*','Referer':'https://www.flashscore.com/','Origin':'https://www.flashscore.com'};
const CACHE=new Map();
function clean(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[ı]/g,'i').replace(/[ş]/g,'s').replace(/[ç]/g,'c').replace(/[ğ]/g,'g').replace(/[ö]/g,'o').replace(/[ü]/g,'u').replace(/\b(fc|fk|sk|cf|ac|club|futbol|football)\b/g,' ').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function tokens(s){return clean(s).split(' ').filter(x=>x.length>1)}
function scoreName(a,b){const A=tokens(a),B=tokens(b);if(!A.length||!B.length)return 0;const sa=A.join(' '),sb=B.join(' ');if(sa===sb)return 1;if(sa.includes(sb)||sb.includes(sa))return .92;const setB=new Set(B);const common=A.filter(x=>setB.has(x)).length;return common/Math.max(A.length,B.length)}
function parseFeed(raw){const out=[];for(const block of String(raw||'').split('~')){if(!block.trim())continue;const o={};for(const param of block.split('¬')){if(!param.trim())continue;let idx=param.indexOf('÷');if(idx<0)idx=param.indexOf('·');if(idx<0)continue;const k=param.slice(0,idx),v=param.slice(idx+1);if(o[k]===undefined)o[k]=v;else o[`${k}_2`]=v}if(Object.keys(o).length)out.push(o)}return out}
async function fetchRaw(endpoint,baseHint){const bases=baseHint?[baseHint,...BASES.filter(x=>x!==baseHint)]:BASES;let last=null;for(const base of bases){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),6500);try{const r=await fetch(base+endpoint,{headers:HEADERS,cache:'no-store',signal:ctrl.signal});const t=await r.text();if(r.ok&&t&&t.length>5)return{text:t,base};last=new Error(`Flashscore ${r.status}`)}catch(e){last=e}finally{clearTimeout(timer)}}throw last||new Error('Flashscore feed alınamadı')}
function maybeNum(v){const n=Number(v);return Number.isFinite(n)?n:null}
function eventRows(raw){return parseFeed(raw).filter(x=>x.AA&&x.AE&&x.AF).map(x=>({id:x.AA,home:x.AE,away:x.AF,timestamp:Number(x.AD||0),status:x.AB,league:x.ZA||x.AC||'',homeId:x.AU||null,awayId:x.AV||null,homeScore:maybeNum(x.AG),awayScore:maybeNum(x.AH),raw:x}))}
async function findEvent(match,sportId){const key=`event:${sportId}:${clean(match.home)}|${clean(match.away)}|${match.date||''}`,c=CACHE.get(key);if(c&&Date.now()-c.at<20*60*1000)return c.value;const target=match.startTimestamp?new Date(match.startTimestamp):new Date();const now=new Date();const baseOffset=Math.max(-3,Math.min(3,Math.round((target-now)/86400000)));const offsets=[baseOffset,0,1,-1,2,-2,3].filter((x,i,a)=>a.indexOf(x)===i);const feeds=await Promise.allSettled(offsets.map(async d=>{const r=await fetchRaw(`f_${sportId}_${d}_3_en_1`);return{...r,day:d,rows:eventRows(r.text)}}));let best=null;for(const f of feeds){if(f.status!=='fulfilled')continue;for(const e of f.value.rows){const h=scoreName(e.home,match.home),a=scoreName(e.away,match.away),rev=scoreName(e.home,match.away)+scoreName(e.away,match.home),direct=h+a;if(direct>=1.35&&direct>rev){const tsBonus=e.timestamp&&match.startTimestamp?Math.max(0,1-Math.abs(e.timestamp*1000-match.startTimestamp)/(40*3600000)):0;const total=direct+tsBonus*.35;if(!best||total>best.score)best={...e,score:total,base:f.value.base}}}}if(!best)return null;CACHE.set(key,{at:Date.now(),value:best});return best}
function historySections(raw){const list=parseFeed(raw);let section=0;const groups={1:[],2:[],3:[]};for(const x of list){if(x.KB!==undefined)section++;if(!x.KP||section<1||section>3)continue;const hs=Number(x.KU),as=Number(x.KT);groups[section].push({id:x.KP,timestamp:Number(x.KC||0),home:x.FH||'',away:x.FK||'',homeScore:Number.isFinite(hs)?hs:null,awayScore:Number.isFinite(as)?as:null,league:x.KF||'',country:x.KH||'',score:x.KL||'',main:x.KS||'',resultCode:x.KN||''})}return groups}
function calcRows(rows,team,tennis=false){const picked=rows.filter(r=>Number.isFinite(r.homeScore)&&Number.isFinite(r.awayScore)).slice(0,10).map(r=>{const home=scoreName(r.home,team)>=scoreName(r.away,team),gf=home?r.homeScore:r.awayScore,ga=home?r.awayScore:r.homeScore;return{...r,role:home?'home':'away',gf,ga,result:gf>ga?'W':gf<ga?'L':'D',over25:tennis?(gf+ga>=3):(gf+ga>2.5),btts:gf>0&&ga>0}});if(!picked.length)return null;const calc=xs=>{if(!xs.length)return null;const wins=xs.filter(x=>x.result==='W').length,draws=xs.filter(x=>x.result==='D').length,losses=xs.filter(x=>x.result==='L').length,gf=xs.reduce((s,x)=>s+x.gf,0),ga=xs.reduce((s,x)=>s+x.ga,0);const base={played:xs.length,wins,draws,losses,goalsFor:gf,goalsAgainst:ga,avgGF:gf/xs.length,avgGA:ga/xs.length,over25:xs.filter(x=>x.over25).length,btts:xs.filter(x=>x.btts).length,cleanSheets:xs.filter(x=>x.ga===0).length,failedToScore:xs.filter(x=>x.gf===0).length,recent:xs.slice(0,5).map(x=>x.result).join('-'),recentScores:xs.slice(0,5).map(x=>`${x.gf}-${x.ga}`),pointsPerGame:(wins*3+draws)/xs.length};if(tennis){base.straightWins=xs.filter(x=>x.result==='W'&&x.ga===0).length;base.straightLosses=xs.filter(x=>x.result==='L'&&x.gf===0).length;base.deciders=xs.filter(x=>x.gf+x.ga>=3).length;base.avgSetsWon=gf/xs.length;base.avgSetsLost=ga/xs.length}return base};const base=calc(picked);return{...base,roleStats:{home:calc(picked.filter(x=>x.role==='home')),away:calc(picked.filter(x=>x.role==='away'))},htftByRole:{home:{played:0,counts:{}},away:{played:0,counts:{}}},_rows:picked}}
function statNumber(v){if(v===null||v===undefined)return null;const n=Number(String(v).replace('%','').replace(',','.').replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:null}
function statType(name){const n=clean(name);if(n.includes('expected goals')||n==='xg')return'xg';if(n.includes('shots on goal')||n.includes('shots on target'))return'sot';if(n.includes('total shots'))return'shots';if(n.includes('corner'))return'corners';if(n.includes('yellow card')||n.includes('red card'))return'cards';return null}
async function enrichFootballStats(base,homeSummary,awaySummary,homeName,awayName){const refs=[];for(const [team,s] of [[homeName,homeSummary],[awayName,awaySummary]])for(const r of s?._rows?.slice(0,4)||[])refs.push({team,row:r});const uniq=[];for(const x of refs)if(!uniq.some(y=>y.row.id===x.row.id&&y.team===x.team))uniq.push(x);const settled=await Promise.allSettled(uniq.map(async x=>{const r=await fetchRaw(`df_st_1_${x.row.id}`,base);return{x,stats:parseFeed(r.text)}}));const bags=new Map([[homeName,{}],[awayName,{}]]);for(const s of settled){if(s.status!=='fulfilled')continue;const {x,stats}=s.value,bag=bags.get(x.team)||{};let section='Match';for(const st of stats){if(st.SE!==undefined){section=st.SE;continue}if(section!=='Match'||!st.SG)continue;const type=statType(st.SG);if(!type)continue;const own=x.row.role==='home'?statNumber(st.SH):statNumber(st.SI);if(own===null)continue;(bag[type]||(bag[type]=[])).push(own)}bags.set(x.team,bag)}const avgBag=bag=>Object.fromEntries(Object.entries(bag||{}).map(([k,v])=>[k,v.length?+(v.reduce((a,b)=>a+b,0)/v.length).toFixed(2):null]));return{home:avgBag(bags.get(homeName)),away:avgBag(bags.get(awayName))}}
async function fetchFlashscoreForm(match){const key=`form:1:${match.id}|${clean(match.home)}|${clean(match.away)}`,c=CACHE.get(key);if(c&&Date.now()-c.at<10*60*1000)return c.value;try{const event=await findEvent(match,1);if(!event){console.warn('[flashscore-event-miss]',match.id,match.home,match.away);return null}const hh=await fetchRaw(`df_hh_1_${event.id}`,event.base),groups=historySections(hh.text);const home=calcRows(groups[1],match.home,false),away=calcRows(groups[2],match.away,false);if(!(home?.played>=4&&away?.played>=4)){console.warn('[flashscore-form-short]',match.id,home?.played||0,away?.played||0);return null}let flashStats={home:{},away:{}};try{flashStats=await enrichFootballStats(event.base,home,away,match.home,match.away)}catch(e){console.warn('[flashscore-stats]',match.id,e?.message||e)}delete home._rows;delete away._rows;const value={home,away,source:'Flashscore son maçlar',coverage:'son 10 maç',eventId:event.id,flashscoreUrl:`https://www.flashscore.com/match/${event.id}/`,flashStats};CACHE.set(key,{at:Date.now(),value});console.log('[flashscore-form-ok]',match.id,event.id,home.played,away.played);return value}catch(e){console.warn('[flashscore-direct]',match.id,e?.message||e);return null}}
async function fetchFlashscoreTennisForm(match){const key=`form:2:${match.id}|${clean(match.home)}|${clean(match.away)}`,c=CACHE.get(key);if(c&&Date.now()-c.at10*60*1000)return c.value;try{const event=await findEvent(match,2);if(!event){console.warn('[flashscore-tennis-event-miss]',match.id,match.home,match.away);return null}const hh=await fetchRaw(`df_hh_2_${event.id}`,event.base),groups=historySections(hh.text);const home=calcRows(groups[1],match.home,true),away=calcRows(groups[2],match.away,true);if(!(home?.played>=4&&away?.played>=4)){console.warn('[flashscore-tennis-form-short]',match.id,home?.played||0,away?.played||0);return null}delete home._rows;delete away._rows;const value={home,away,source:'Flashscore tenis son maçları',coverage:'son 10 maç',eventId:event.id,flashscoreUrl:`https://www.flashscore.com/match/${event.id}/`};CACHE.set(key,{at:Date.now(),value});console.log('[flashscore-tennis-ok]',match.id,event.id,home.played,away.played);return value}catch(e){console.warn('[flashscore-tennis]',match.id,e?.message||e);return null}}
async function fetchFlashscoreResult(match){const sportId=Number(match?.sportType)===5?2:1;try{const event=await findEvent(match,sportId);if(!event)return null;return{eventId:event.id,status:event.status,home:event.home,away:event.away,homeScore:event.homeScore,awayScore:event.awayScore,finished:['FT','AET','AP','Finished'].includes(String(event.status||''))||/finished|after/i.test(String(event.status||'')),url:`https://www.flashscore.com/match/${event.id}/`}}catch(e){console.warn('[flashscore-result]',match?.id,e?.message||e);return null}}
module.exports={fetchFlashscoreForm,fetchFlashscoreTennisForm,fetchFlashscoreResult};
