const BULLETIN_URLS=['https://bulten.nesine.com/api/bulten/getprebultenfull','https://bulten.nesine.com/api/bulten/getprebultenall','https://bulten.nesine.com/api/bulten/getprebultenv3'];
const WEB_AUTH=process.env.NESINE_BULLETIN_AUTH||'Basic RDQ3MDc4RDMtNjcwQi00OUJBLTgxNUYtM0IyMjI2MTM1MTZCOkI4MzJCQjZGLTQwMjgtNDIwNS05NjFELTg1N0QxRTZEOTk0OA==';
const SPORT_NAMES={1:'Futbol',5:'Tenis'};
const MARKET_NAMES={1:'Maç Sonucu',3:'Çifte Şans',5:'İlk Yarı/Maç Sonucu',7:'İlk Yarı Sonucu',8:'İlk Yarı Çifte Şans',9:'2. Yarı Sonucu',11:'Alt/Üst',12:'Alt/Üst',13:'Toplam Gol Alt/Üst',14:'İlk Yarı Alt/Üst',15:'İlk Yarı Alt/Üst',20:'Ev Sahibi Alt/Üst',29:'Deplasman Alt/Üst',38:'Karşılıklı Gol',43:'Toplam Gol Aralığı',49:'Tek/Çift',100:'Handikaplı Maç Sonucu',101:'Handikaplı Maç Sonucu',182:'Kim Tur Atlar / Maç Kazananı',183:'1. Set Kazananı',187:'Set Skoru',189:'Toplam Oyun Alt/Üst',185:'Handikap',216:'Toplam Korner Alt/Üst',218:'İlk Yarı Korner Alt/Üst',220:'En Çok Korner',225:'Kırmızı Kart',272:'Sonuç + Alt/Üst',291:'İlk Golü Hangi Takım Atar',299:'Korner Tek/Çift',301:'Kart Puanı Alt/Üst',338:'Toplam Korner Aralığı',342:'Sonuç + Alt/Üst',414:'Maç Sonucu ve Karşılıklı Gol',418:'Asya Handikabı',424:'Toplam Korner Alt/Üst',426:'Korner Handikap',446:'Alt/Üst ve Karşılıklı Gol',452:'1. Yarı Karşılıklı Gol',461:'Sonuç (2 Yollu)',583:'Toplam Korner Alt/Üst',593:'Penaltı Olur Mu',599:'İkinci Yarı Karşılıklı Gol',601:'Ev Sahibi Korner',602:'Deplasman Korner',656:'Sonuç (2 Yollu)',701:'Oyuncu Gol Atar',702:'Oyuncu İlk Golü Atar',703:'Oyuncu Her İki Yarıda Gol Atar',704:'Oyuncu Hat-Trick',705:'Oyuncu Gol Atar ve Takımı Kazanır',706:'Oyuncu Kafa ile Gol Atar',707:'Oyuncu Asist',708:'Oyuncu Frikikten Gol',709:'Oyuncu Kart Görür',710:'Oyuncu Kırmızı Kart',711:'Oyuncu Gol + Kart',712:'Oyuncu Asist',713:'Oyuncu Gol + Asist',714:'Oyuncu Kaleyi Bulan Şut',722:'Oyuncu Kart Görür',740:'Oyuncu Şut',741:'Oyuncu Faul Alır',742:'Oyuncu Faul Yapar',743:'Oyuncu Ofsayt',744:'Oyuncu Pas',763:'Oyuncu İsabetli Pas',764:'Oyuncu Top Çalma',765:'Oyuncu Gol veya Asist',777:'Maç Skoru',779:'İlk Yarı Skoru',798:'Korner Handikap',800:'İlk Yarı Kart Puanı',801:'İY / 2Y Karşılıklı Gol',803:'Kaleci Kurtarış',804:'VAR Monitörü',805:'Takım Şutu Alt/Üst',806:'Takım İsabetli Şut',807:'Takım Faul',808:'Takım Ofsayt',809:'Takım Topa Sahip Olma',822:'Sonuç + Alt/Üst',823:'Sonuç + KG',824:'Sonuç + Alt/Üst + KG',837:'Oyuncu Kart Görür',862:'İlk Yarı Korner Alt/Üst',863:'Kart Puanı Alt/Üst',864:'Takım Korner HCP',866:'Sonraki Gol',867:'Korner 1X2',871:'Takım Kale Vuruşu',872:'Takım Taç Atışı',873:'Takım Top Çalma',874:'Takım Pas Arası',884:'Maç Handikabı',887:'Alt Handikap'};
const CORE_FIXED={1:{1:'1',2:'X',3:'2'},3:{1:'1X',2:'12',3:'X2'},5:{1:'1/1',2:'1/X',3:'1/2',4:'X/1',5:'X/X',6:'X/2',7:'2/1',8:'2/X',9:'2/2'},38:{1:'Var',2:'Yok'},43:{1:'0-1',2:'2-3',3:'4-5',4:'6+'},49:{1:'Tek',2:'Çift'},100:{1:'1',2:'X',3:'2'},101:{1:'1',2:'X',3:'2'}};
const CORE_OU=new Set([11,12,13,14,15,20,29]);
let LAST_GOOD={at:0,data:null,source:null};let INFLIGHT=null;
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v==='string'){const n=Number(v.replace(',','.'));return Number.isFinite(n)?n:null}return null}
function text(v){return String(v??'').replace(/\s+/g,' ').trim()}
function technical(v){const s=text(v).toLocaleLowerCase('tr-TR');return !s||/^(market|bahis|seçenek|secenek|option|outcome|selection)\s*[#:_-]?\s*\d+/i.test(s)}
function human(v){const s=text(v);return s&&!technical(s)?s:null}
function firstHuman(...xs){for(const x of xs){const h=human(x);if(h)return h}return null}
function fmt(v){const n=Number(v);return Number.isInteger(n)?String(n):n.toFixed(1).replace(/\.0$/,'')}
function clone(x){return x?JSON.parse(JSON.stringify(x)):x}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function kind(id,name,sport){const n=text(name).toLocaleLowerCase('tr-TR');if(sport===5){if(id===182||n.includes('maç kazanan')||n.includes('kim tur atlar'))return'match_winner';if(id===183||((n.includes('1. set')||n.includes('birinci set')||n.includes('ilk set'))&&n.includes('kazanan')))return'first_set_winner';if(n.includes('set')&&n.includes('kazanan'))return'set_winner';if(n.includes('set')&&n.includes('handikap'))return'set_handicap';if(n.includes('oyun')&&n.includes('handikap'))return'game_handicap';if(id===189||n.includes('toplam oyun')||n.includes('oyun alt')||n.includes('oyun üst'))return'total_games';if(id===187||n.includes('set skoru')||n.includes('doğru set')||n.includes('set sonucu'))return'set_score';return'tennis_special'}if(id===1)return'match_result';if(id===3)return'double_chance';if(id===5)return'htft';if([11,12,13].includes(id))return'total_goals';if(id===38)return'btts';if(id===43)return'goal_range';if(id===291||id===866)return'first_goal_team';if([272,342,822].includes(id))return'result_total_combo';if([414,823].includes(id))return'result_btts_combo';if(id===446)return'total_btts_combo';if([701,703,704,705,706,708].includes(id))return'player_goal';if(id===702)return'player_first_goal';if([707,712].includes(id))return'player_assist';if([709,710,722,837].includes(id))return'player_card';if([711,713,765].includes(id))return'player_goal_assist';if(id===714)return'player_sot';if(id===740)return'player_shot';if(id===803)return'goalkeeper_saves';if(id===805)return'team_shots_total';if(id===806)return'team_sot_total';if(n.includes('korner'))return'corners_special';if(n.includes('kart'))return'cards_special';if(n.includes('karşılıklı gol'))return'btts_special';if(n.includes('alt')||n.includes('üst'))return'total_special';return'other'}
function fallbackLabel(m,oc,ctx){const id=Number(m?.MTID||0),n=Number(oc?.N||0),spread=num(m?.SOV);if(CORE_FIXED[id]?.[n])return CORE_FIXED[id][n];if(CORE_OU.has(id)&&spread!==null){if(n===1)return`Alt ${fmt(spread)}`;if(n===2)return`Üst ${fmt(spread)}`}if(ctx.sportType===5){if(id===182||id===183){if(n===1)return ctx.home;if(n===2)return ctx.away}if(id===187){if(n===1)return`${ctx.home} 2-0`;if(n===2)return`${ctx.home} 2-1`;if(n===3)return`${ctx.away} 2-0`;if(n===4)return`${ctx.away} 2-1`}if(id===189&&spread!==null){if(n===1)return`Alt ${fmt(spread)}`;if(n===2)return`Üst ${fmt(spread)}`}}return`Nesine seçeneği #${n||'?'}`}
function rawOutcomeLabel(oc){return firstHuman(oc?.ON,oc?.ONA,oc?.NAME,oc?.NME,oc?.ONAME,oc?.SN,oc?.SON,oc?.DN)}
function normalizeMarket(m,ctx){const id=Number(m?.MTID||m?.mtid||m?.typeId||0),rawName=firstHuman(m?.MN,m?.MNA,m?.NAME,m?.NME,m?.name),name=rawName||MARKET_NAMES[id]||`Nesine Market ${id||'?'}`;const rawOut=Array.isArray(m?.OCA)?m.OCA:Array.isArray(m?.outcomes)?m.outcomes:[];const outcomes=rawOut.map(oc=>{const odds=num(oc?.O??oc?.odds);if(!(odds>1))return null;const raw=rawOutcomeLabel(oc)||human(oc?.label);return{n:Number(oc?.N??oc?.n??0),label:raw||fallbackLabel(m,oc,ctx),odds,no:oc?.NO??oc?.no??null,sourceLabel:raw||null}}).filter(Boolean);if(!outcomes.length)return null;return{id:m?.ID??m?.id??null,typeId:id,name,sourceName:rawName||null,kind:kind(id,name,ctx.sportType),known:true,spread:num(m?.SOV??m?.spread),status:m?.MS??m?.status??null,inPlay:m?.INM===1||m?.inPlay===true,outcomes}}
function leagueArray(raw){return raw?.sg?.LA||raw?.SG?.LA||raw?.data?.sg?.LA||raw?.data?.SG?.LA||raw?.leagues||[]}
function leagueMap(raw){const map=new Map();for(const x of leagueArray(raw))if((x?.LID??x?.id)!=null&&(x?.N||x?.name))map.set(x?.LID??x?.id,String(x?.N||x?.name));return map}
function eventArray(raw){const candidates=[raw?.sg?.EA,raw?.SG?.EA,raw?.data?.sg?.EA,raw?.data?.SG?.EA,raw?.data?.EA,raw?.EA,raw?.events,raw?.data?.events];for(const x of candidates)if(Array.isArray(x))return x;return null}
function normalizeEvent(ev,leagues){const sportType=Number(ev?.TYPE??ev?.sportType??0),startTimestamp=num(ev?.ESD??ev?.startTimestamp),ctx={sportType,home:text(ev?.HN??ev?.home),away:text(ev?.AN??ev?.away)},rawMarkets=Array.isArray(ev?.MA)?ev.MA:Array.isArray(ev?.markets)?ev.markets:[],markets=rawMarkets.map(m=>normalizeMarket(m,ctx)).filter(Boolean);return{id:String(ev?.C??ev?.EV??ev?.id??`${ctx.home}-${ctx.away}-${startTimestamp||''}`),eventId:ev?.EV??ev?.eventId??null,sportType,sport:SPORT_NAMES[sportType]||`Spor ${sportType}`,home:ctx.home,away:ctx.away,displayName:text(ev?.ENO??ev?.displayName)||`${ctx.home} - ${ctx.away}`,leagueCode:ev?.LC??ev?.leagueCode??null,league:leagues.get(ev?.LC??ev?.leagueCode)||text(ev?.league)||'Lig bilgisi yok',date:String(ev?.D??ev?.date??''),day:String(ev?.DAY??ev?.day??''),time:String(ev?.T??ev?.time??''),startTimestamp,live:ev?.LE===1||ev?.live===true,markets,marketCount:markets.length,outcomeCount:markets.reduce((s,m)=>s+m.outcomes.length,0)}}
function requestHeaders(auth=true){const h={Accept:'application/json, text/javascript, */*; q=0.01','Accept-Language':'tr-TR,tr;q=0.9,en-US;q=0.7,en;q=0.6','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-cache',Pragma:'no-cache',Origin:'https://www.nesine.com',Referer:'https://www.nesine.com/','Sec-Fetch-Dest':'empty','Sec-Fetch-Mode':'cors','Sec-Fetch-Site':'same-site'};if(auth&&WEB_AUTH)h.Authorization=WEB_AUTH;return h}
async function fetchVariant(url,auth,timeoutMs){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),timeoutMs);try{const res=await fetch(url,{headers:requestHeaders(auth),cache:'no-store',redirect:'follow',signal:ctrl.signal}),body=await res.text();if(!res.ok){const e=new Error(`Kaynak HTTP ${res.status}`);e.status=res.status;e.preview=body.slice(0,220);e.url=url;throw e}let raw;try{raw=JSON.parse(body)}catch{const e=new Error('Nesine bülteni JSON formatında dönmedi');e.preview=body.slice(0,220);throw e}const events=eventArray(raw);if(!Array.isArray(events))throw new Error('Nesine bülten şeması değişti: etkinlik dizisi bulunamadı');const leagues=leagueMap(raw),data=events.filter(ev=>[1,5].includes(Number(ev?.TYPE??ev?.sportType))&&(ev?.HN||ev?.home||ev?.ENO||ev?.displayName)&&(ev?.AN||ev?.away||ev?.ENO||ev?.displayName)).map(ev=>normalizeEvent(ev,leagues)).filter(ev=>ev.markets.length).sort((a,b)=>(a.startTimestamp||9e15)-(b.startTimestamp||9e15));if(!data.length)throw new Error('Nesine kaynağı boş bülten döndürdü');return{data,source:url.split('/').pop()}}finally{clearTimeout(timer)}}
async function fetchOnce(){let last=null;const attempts=[];for(const url of BULLETIN_URLS)attempts.push([url,true]);attempts.push([BULLETIN_URLS[0],false]);for(const [url,auth] of attempts){try{return await fetchVariant(url,auth,5500)}catch(e){last=e;console.warn('[nesine-transport]',url.split('/').pop(),auth?'auth':'plain',e?.status||e?.cause?.code||e?.code||e?.name||e?.message)}}throw last||new Error('Nesine bülteni alınamadı')}
async function refresh(){let last=null;for(let i=0;i<2;i++){try{const hit=await fetchOnce();LAST_GOOD={at:Date.now(),data:hit.data,source:hit.source};return hit.data}catch(e){last=e;console.warn('[nesine-retry]',i+1,e?.cause?.code||e?.code||e?.name||e?.message);if(i<1)await sleep(250)}}if(LAST_GOOD.data&&Date.now()-LAST_GOOD.at<30*60*1000){console.warn('[nesine-stale-cache]',Math.round((Date.now()-LAST_GOOD.at)/1000),'sec');return LAST_GOOD.data}throw last||new Error('Nesine bülteni alınamadı')}
async function fetchBulletin(){if(LAST_GOOD.data&&Date.now()-LAST_GOOD.at<45*1000)return clone(LAST_GOOD.data);if(INFLIGHT)return clone(await INFLIGHT);INFLIGHT=refresh();try{return clone(await INFLIGHT)}finally{INFLIGHT=null}}
module.exports={fetchBulletin};
