function text(v){return String(v??'').replace(/\s+/g,' ').trim()}
function norm(v){return text(v).toLocaleLowerCase('tr-TR')}
function technical(v){const s=norm(v);return !s||/\b(?:seçenek|secenek|seçim|secim|option|outcome|selection)\s*[#:_-]?\s*\d+\b/i.test(s)||/\bmarket\s*\d+\b/i.test(s)||/\bnesine\s+seçeneği\b/i.test(s)||/\bneç\s*av\b/i.test(s)}
function humanMarket(v,typeId){const id=Number(typeId);if(id===798)return'Korner Handikap';const s=text(v);return technical(s)?'':s}
function humanSelection(v){const s=text(v);return technical(s)?'':s}
function riskFromOdds(odds){const o=Number(odds);if(!Number.isFinite(o))return'Risk belirsiz';if(o<1.55)return'Daha düşük risk';if(o<2.4)return'Orta risk';if(o<4.5)return'Yüksek risk';return'Çok yüksek risk'}
function pickKind(p){const m=norm(p?.market);if(m.includes('çifte şans'))return'double';if(m.includes('ilk yarı')&&m.includes('maç'))return'htft';if(m.includes('karşılıklı gol'))return'btts';if(m.includes('alt')||m.includes('üst')||m.includes('gol aral'))return'total';if(m.includes('sonuç')&&(m.includes('alt')||m.includes('üst')||m.includes('karşılıklı')))return'combo';if(m.includes('maç sonucu')||m==='sonuç')return'result';if(m.includes('korner'))return'corner';if(m.includes('şut'))return'shot';return'other'}
function meaning(p){const s=humanSelection(p.selection),m=humanMarket(p.market,p.marketTypeId),k=pickKind({...p,market:m});if(!s||!m)return'';if(k==='result')return`${s} seçimi, yalnızca maç sonucunun bu yönde bitmesini ister.`;if(k==='double')return`${s} seçimi iki olası maç sonucunu kapsar; bu yüzden düz sonuca göre daha temkinlidir.`;if(k==='htft')return`${s} seçiminin gelmesi için ilk yarı ve maç sonu sonuçlarının ikisinin de belirtilen sırayla gerçekleşmesi gerekir.`;if(k==='btts')return`${s} seçimi iki takımın gol katkısına odaklanır; maç sonucundan bağımsızdır.`;if(k==='total')return`${s} seçimi maçın toplam gol temposuna oynar.`;if(k==='combo')return`${s} seçimi birden fazla koşulun aynı anda gerçekleşmesini ister; yüksek oranının ana nedeni budur.`;if(k==='corner')return`${s} seçimi maç skorundan değil korner dengesinden kazanır.`;if(k==='shot')return`${s} seçimi takım/oyuncu şut üretimine odaklanır.`;return`${m} marketindeki ${s} seçiminin belirtilen koşulu sağlaması gerekir.`}
function why(p,scenario){const s=humanSelection(p.selection),m=humanMarket(p.market,p.marketTypeId),k=pickKind({...p,market:m});if(!s||!m)return'';const high=Number(p.odds)>=4.5;if(k==='result')return`Maçın ana yönü bu tarafı desteklediği için ${s} sonucunu değerlendiriyorum. Oran kısa olsa bile yalnızca maç hikâyesiyle uyumluysa öneride kalır.`;if(k==='double')return`Ana maç yönünü korurken beraberlik/ikinci sonuç için hata payı bıraktığı için daha kontrollü bir alternatif.`;if(k==='total')return`Taraf seçmek yerine maçın beklenen temposuna oynuyoruz. Bu seçim, ana maç yorumundaki gol senaryosuyla çelişmediği için listede.`;if(k==='btts')return`Burada soru kimin kazanacağı değil, iki tarafın da skor üretip üretemeyeceği. Ana maç hikâyesi bu gol senaryosunu desteklediği için değerlendiriliyor.`;if(k==='htft')return`İki aşamalı bir maç akışı istediği için doğal olarak yüksek riskli. Ana tahmin değil; yalnızca ilk yarı ile maç sonu arasında bu dönüşümü makul kılan bir senaryo varsa sürpriz seçim olarak tutulur.`;if(k==='combo')return`${m} tek bahiste iki koşul ister. ${high?'Bu yüzden oran yüksek ve bunu ana seçim değil, çok yüksek riskli sürpriz senaryo olarak görüyorum.':'Ana maç yönüyle gol beklentisini aynı senaryoda birleştirdiği için değerlendiriliyor.'}`;if(k==='corner')return`Korner dağılımı ana skor tahmininden farklı bir markettir. Yalnızca korner tarafında okunabilir bir avantaj varsa değerlendirilir.`;if(k==='shot')return`Şut marketi sonuçtan bağımsız ek bir açı verir. Doğrulanmış şut verisi yoksa bu market öneride tutulmaz.`;return`Bu seçim ana maç yorumuyla çelişmediği ve mevcut market yapısında ayrı bir senaryo sunduğu için değerlendiriliyor.`}
function breaks(p){const k=pickKind(p);if(k==='combo')return'Erken karşılıklı gol, beklenmedik kırmızı kart veya maçın taraf/tempo dengesinin bozulması bu iki koşullu bahsi hızlı biçimde bozabilir.';if(k==='htft')return'İlk yarının beklenenden farklı bitmesi seçimi daha devrede kaybettirebilir; bu nedenle çok yüksek risklidir.';if(k==='total'||k==='btts')return'Erken gol, kırmızı kart veya bitiricilikte sıra dışı bir gün maçın gol temposunu tamamen değiştirebilir.';if(k==='result'||k==='double')return'Erken yenilen gol, kartlar ve kadro/rotasyon etkisi maçın taraf dengesini değiştirebilir.';return'Maç içindeki erken gol, kart veya beklenmedik tempo değişimi bu senaryoyu bozabilir.'}
function mainDirection(result,match){const title=text(result?.scenario?.title);for(const n of [match?.home,match?.away])if(n&&norm(title).includes(norm(n)))return n;const p=(result?.picks||[]).find(x=>x?.available!==false&&/maç sonucu/i.test(text(x.market))&&humanSelection(x.selection));if(p){const s=norm(p.selection);if(s==='1'||s===norm(match?.home))return match?.home;if(s==='2'||s===norm(match?.away))return match?.away}return''}
function plainCommentary(result,match){const form=result?.form,dir=mainDirection(result,match),home=text(match?.home),away=text(match?.away);const verified=Number(form?.home?.played)>=4&&Number(form?.away?.played)>=4;if(verified){const h=form.home,a=form.away;const lead=dir?`${dir} tarafı maçın genel dengesinde bir adım önde görünüyor.`:'Taraflar arasında tek başına “banko” denecek kadar net bir fark görmüyorum.';return`${lead} ${home} son ${h.played} maçta ${h.wins} galibiyet aldı ve maç başına ${Number(h.avgGF||0).toFixed(1)} gol üretti; ${away} ise son ${a.played} maçta ${a.wins} galibiyet ve ${Number(a.avgGF||0).toFixed(1)} gol ortalamasıyla geliyor. Ben maçı önce kimin daha fazla kontrol kurabileceği, sonra da bu kontrolün skora ne kadar yansıyacağı üzerinden okuyorum. Aşağıdaki bahisler bu ana hikâyeyle çelişmiyorsa gösteriliyor.`}
 const lead=dir?`${dir} tarafı mevcut oran yapısında bir adım önde görünüyor.`:'Mevcut oran yapısı bu maçta çok net bir taraf üstünlüğü göstermiyor.';return`${lead} Ancak bu analizde iki takımın güncel formu bağımsız bir kaynaktan doğrulanamadı; bu yüzden “son maçlarda şöyleydi” diye veri uydurmuyorum. Maç yorumunu mevcut yasal marketlerin birbirleriyle verdiği sinyaller üzerinden yapıyorum: önce taraf dengesi, sonra tempo ve gol ihtimali. Bu nedenle yüksek oranlı seçimler ana tahmin değil, yalnızca aynı maç hikâyesinin daha zor gerçekleşen sürpriz versiyonlarıdır.`}
function cleanPick(p,scenario){if(!p||p.available===false)return null;const market=humanMarket(p.market,p.marketTypeId),selection=humanSelection(p.selection);if(!market||!selection)return null;const display=`${market} · ${selection}`;if(technical(display))return null;return{...p,market,selection,displayName:display,riskText:riskFromOdds(p.odds),meaning:meaning({...p,market,selection}),reason:why({...p,market,selection},scenario),whatCanBreak:breaks({...p,market,selection}),av:undefined,model:undefined,fair:undefined}}
function cleanUserAnalysis(result,match){if(!result||typeof result!=='object')return result;const scenario={...(result.scenario||{})};scenario.matchCommentary=plainCommentary(result,match);scenario.riskText=result.formStatus&&String(result.formStatus).includes('market-only')?'Güncel form doğrulanamadığı için bu maçtaki taraf ve tempo yorumu daha düşük güvenle okunmalı. Erken gol veya kart oyunun beklenen akışını değiştirebilir.':'Form verisi destek olsa da erken gol, kart, rotasyon veya maç içi tempo değişimi ana senaryoyu bozabilir.';scenario.betOpinionTitle='NEÇ Kısa Görüş';scenario.betOpinion=text(scenario.betOpinion)||'Ana maç yorumuyla uyumlu, adı açıkça doğrulanmış bir oran varsa değerlendir; aksi halde pas geç.';const picks=(result.picks||[]).map(p=>cleanPick(p,scenario)).filter(Boolean);return{...result,scenario,picks,userFacingVersion:2}}
module.exports={cleanUserAnalysis,technical,humanMarket,humanSelection};