const { analyzeMatch } = require('../lib/analyzer-v6');
const { fetchFlashscoreForm, fetchFlashscoreTennisForm } = require('../lib/flashscore');
const { fetchWebResearch } = require('../lib/research-strict');
const { mergeResearch } = require('../lib/research-merge');
const RESULT_DEPENDENT_SPECIALS=new Set([214,215,442,444,588,589,590,591,592,705]);
function withTimeout(promise,ms){return Promise.race([promise,new Promise(resolve=>setTimeout(()=>resolve(null),ms))])}
function analysisMatch(match){if(Number(match?.sportType)!==1)return match;return{...match,markets:(match.markets||[]).filter(m=>!RESULT_DEPENDENT_SPECIALS.has(Number(m?.typeId)))}}
function emergencyAnalysis(match,message){return{radar:0,form:null,formStatus:'fallback',scenario:{title:'Analiz üretilemedi',summary:'Nesine oranları görünmeye devam ediyor; analiz motoru bu istekte sonuç üretemedi.',formText:'',confidence:0,specialComment:'',specialOdds:null},picks:[],ideas:[],insights:[{title:'⚠️ Teknik not',text:message||'Analiz servisi yanıt vermedi.'}],analyzedAt:new Date().toISOString(),degraded:true,disclaimer:'Teknik hata halinde sahte seçim üretilmez.'}}
module.exports=async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});res.setHeader('Cache-Control','no-store, max-age=0');
 try{
  const original=typeof req.body==='string'?JSON.parse(req.body):req.body;if(!original||!original.id||!Array.isArray(original.markets))return res.status(400).json({error:'Geçersiz maç verisi'});const match=analysisMatch(original),sport=Number(match.sportType);let form=null,research=null,sourceMode='market-only';
  if(sport===1){[form,research]=await Promise.all([withTimeout(fetchFlashscoreForm(match),18000).catch(e=>{console.warn('[flashscore-promise]',match.id,e?.message||e);return null}),withTimeout(fetchWebResearch(match),37000).catch(e=>{console.warn('[web-research-promise]',match.id,e?.message||e);return null})]);sourceMode=form?'flashscore-direct':'market-only-football'}
  else if(sport===5){form=await withTimeout(fetchFlashscoreTennisForm(match),15000).catch(e=>{console.warn('[flashscore-tennis-promise]',match.id,e?.message||e);return null});sourceMode=form?'flashscore-tennis':'market-only'}
  try{let result=analyzeMatch(match,form)||emergencyAnalysis(original,'Analiz adayı oluşturulamadı');if(research)result=mergeResearch(result,research,match);result.fullMarketCount=original.marketCount||original.markets.length;result.analysisMarketCount=match.markets.length;result.researchMode=Boolean(research)||Boolean(form&&String(form.source||'').toLowerCase().includes('flashscore'));result.formStatus=result.formStatus||sourceMode;if(sport===1&&!form)result.researchWarning='Flashscore son formu bu istekte eşleşmedi; ana yön piyasa temeliyle düşük güvenli kuruldu. Oyuncu/şut verisi uydurulmadı.';if(sport===1&&form&&!research)result.researchWarning='Flashscore form ve takım detayları kullanıldı; web araştırma katmanı doğrulanmış oyuncu sonucu üretmediği için oyuncu marketi önerilmedi.';if(sport===5&&!form)result.researchWarning='Flashscore tenis formu alınamadı; doğrulanmış Nesine piyasa dağılımı kullanıldı.';if(form?.eventId)result.flashscore={verified:true,eventId:form.eventId,url:form.flashscoreUrl,stats:form.flashStats||{}};console.log('[analyze-ok]',match.id,sourceMode,'research',Boolean(research),'picks',(result.picks||[]).length,'ideas',(result.ideas||[]).length,'main',result.picks?.find(p=>p.label==='Ana Senaryo')?.selection||'none');return res.status(200).json(result)}catch(e){console.error('[analyzer]',match.id,e);return res.status(200).json(emergencyAnalysis(original,e?.message||'NEÇ analiz motoru çalıştırılamadı'))}
 }catch(e){console.error('[analyze-request]',e);return res.status(200).json(emergencyAnalysis(req.body||{},e?.message||'Analiz isteği işlenemedi'))}
};