const { fetchBulletin }=require('../lib/nesine');
const { fetchFlashscoreForm,fetchFlashscoreTennisForm }=require('../lib/flashscore');
const { analyzeFootball }=require('../lib/analyzer-football');
const { analyzeTennis }=require('../lib/analyzer-tennis');
const CORE_FOOTBALL=new Set([1,3,5,11,12,13,14,38,43,49,100,101]);
const CORE_TENNIS=new Set([182]);
function dateTR(ts){if(!ts)return null;return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(ts))}
function verify(match){const markets=[];for(const m of match.markets||[]){const outcomes=[];for(const o of m.outcomes||[]){o.labelVerified=Boolean(o.sourceLabel)||(Number(match.sportType)===1&&CORE_FOOTBALL.has(Number(m.typeId)))||(Number(match.sportType)===5&&CORE_TENNIS.has(Number(m.typeId)));if(o.labelVerified&&Number(o.odds)>1)outcomes.push(o)}if(outcomes.length){m.outcomes=outcomes;markets.push(m)}}match.markets=markets;return match}
module.exports=async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'GET only'});res.setHeader('Cache-Control','no-store');try{const q=String(req.query?.search||'').toLocaleLowerCase('tr-TR').trim(),date=String(req.query?.date||'').trim(),sport=Number(req.query?.sport||1);let matches=(await fetchBulletin()).filter(m=>Number(m.sportType)===sport);if(date)matches=matches.filter(m=>dateTR(m.startTimestamp)===date||m.date===date);if(q)matches=matches.filter(m=>`${m.home} ${m.away} ${m.league}`.toLocaleLowerCase('tr-TR').includes(q));matches=matches.slice(0,8);const attempts=[];for(const raw of matches){const match=verify(raw),started=Date.now();let form=null;if(sport===1)form=await Promise.race([fetchFlashscoreForm(match).catch(()=>null),new Promise(r=>setTimeout(()=>r(null),8000))]);else form=await Promise.race([fetchFlashscoreTennisForm(match).catch(()=>null),new Promise(r=>setTimeout(()=>r(null),7000))]);const a=sport===1?analyzeFootball(match,form):analyzeTennis(match,form),available=(a?.picks||[]).filter(p=>p.available!==false);attempts.push({match:`${match.home} - ${match.away}`,form:form?'flashscore':'market-only',picks:available.length,main:available[0]?`${available[0].market} · ${available[0].selection} @ ${available[0].odds}`:'none',opinion:a?.scenario?.betOpinion||'',ms:Date.now()-started});if(available.length)return res.status(200).json({ok:true,sport,match:{id:match.id,home:match.home,away:match.away,league:match.league},formMode:form?'flashscore':'market-only',analysis:{picks:available.map(p=>({label:p.label,market:p.market,selection:p.selection,odds:p.odds,av:p.av,confidence:p.confidencePct,reason:p.reason})),title:a.scenario?.title,summary:a.scenario?.summary,betOpinion:a.scenario?.betOpinion,insights:a.insights,ideas:a.ideas||[]},attempts})}return res.status(200).json({ok:false,error:'Eşleşen maçlarda seçim üretilemedi',attempts,totalMatches:matches.length})}catch(e){console.error('[selftest]',e);return res.status(500).json({ok:false,error:e.message||String(e)})}};
